---
title: "Annual Report 2024"
author: "Nishka, Hrishikesh"
date: "2024-03-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# get packages, global variables and datasets
```{r load-lib-helper-files-data-global-var}

# read in the helper file
source("R/july.2024.helper.script.R")

```

# AR Section 1: Global
```{r}

# Global section figure 1.1: GBD ============
# create a version of the figure with the same diseases as used in the same figure in last year's report
ar_global_fig1.1_data <- gbd_results_master_2022 %>%
  filter(country == "Global", cause_of_death %in% c("PM2.5 relative to WHO guideline", "Tobacco", "Alcohol use", 
                                                    "Unsafe water, sanitation, and handwashing", 
                                                    "Transport injuries", 
                                                    "HIV/AIDS and sexually transmitted infections", 
                                                    "Neglected tropical diseases and malaria", 
                                                    "Nutritional deficiencies", 
                                                    "Child and maternal malnutrition"))
colnames(ar_global_fig1.1_data)[3] <- c("llpp_who_2022")

ar_global_fig1.1_data <- ar_global_fig1.1_data %>%
    mutate(lyl_bucket = ifelse((llpp_who_2022 >= 0) & (llpp_who_2022 < 0.1), "0 - < 0.1 years", NA), 
         lyl_bucket = ifelse((llpp_who_2022 >= 0.1) & (llpp_who_2022 <= 0.5), "0.1 - 0.5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2022 > 0.5) & (llpp_who_2022 <= 1), "> 0.5 - 1", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2022 > 1) & (llpp_who_2022 <= 2), "> 1 - 2", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2022 > 2) & (llpp_who_2022 <= 3), "> 2 - 3", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2022 > 3) & (llpp_who_2022 <= 4), "> 3 - 4", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2022 > 4) & (llpp_who_2022 <= 5), "> 4 - 5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2022 > 5) & (llpp_who_2022 < 6), "> 5 - < 6", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2022 >= 6), ">= 6", lyl_bucket)) %>%
  mutate(order_lyl_bucket = ifelse(lyl_bucket == "0 - < 0.1 years", 1, NA), 
         order_lyl_bucket = ifelse(lyl_bucket == "0.1 - 0.5", 2, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 0.5 - 1", 3, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 1 - 2", 4, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 2 - 3", 5, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 3 - 4", 6, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 4 - 5", 7, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 5 - 6", 8, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == ">= 6", 9, order_lyl_bucket))

# ar_fig1.1 plot
ar_global_fig1.1 <- ar_global_fig1.1_data %>%
  ggplot() + 
  geom_col(mapping = aes(x = forcats::fct_reorder(cause_of_death, llpp_who_2022), 
                         y = llpp_who_2022, fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), 
           width = 0.4, color = "black") +
  labs(x = "Threats to Life Expectancy", y = "Life years lost", fill = "Life years lost", 
       title = "") +
  coord_flip() + 
  ggthemes::theme_tufte() +
  themes_aqli_base +
  theme(legend.position = "bottom",
        axis.text = element_text(size = 14),
        axis.title.y = element_text(size = 16, margin = margin(r = 0.6, unit = "cm")),
        axis.title.x = element_text(size = 16, margin = margin(t = 0.6, b = 0.6, unit = "cm")),
        plot.caption = element_text(hjust = 0, size = 8, margin = margin(t = 0.8, unit = "cm")),
        plot.title = element_text(hjust = 0.5, size = 20, margin = margin(b = 0.8, unit = "cm")),
        plot.subtitle = element_text(hjust = 0.5, size = 10, margin = margin(b = 0.8, unit = "cm")),
        legend.box.background = element_rect(color = "black"),
        plot.background = element_rect(fill = "white", color = "white"),
        axis.line = element_line(), 
        legend.text = element_text(size = 11), 
        legend.title = element_text(size = 14),
        panel.grid.major.y = element_blank()) +
  scale_y_continuous(breaks = seq(0, 7, 1)) +
  scale_fill_manual(values = c("0 - < 0.1 years" = "#FFFFFF", 
                               "0.1 - 0.5" = "#FFE6B3", 
                               "> 0.5 - 1" = "#FFD25D", 
                               "> 1 - 2" = "#FFBA00", 
                               "> 2 - 3" = "#FF9600", 
                               "> 3 - 4" = "#FF6908", 
                               "> 4 - 5" = "#E63D23", 
                               "> 5 - < 6" = "#BD251C", 
                               ">= 6" = "#8C130E")) + 
  guides(fill = guide_legend(nrow = 1)) 


# Global section figure 1.2 ============
trendlines_aqli_data_global <- gadm2_aqli_2022 %>%
  filter(!is.na(population)) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2022_weighted , names_to = "years",
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))),
         region = "Global") %>%
  select(region, years, pop_weighted_avg_pm2.5)

# create an identifer for South Asia  
ar_global_fig1.2_data <- gadm2_aqli_2022 %>%
  filter(!is.na(population)) %>%
  mutate(region = ifelse(country %in% south_asia_def, "South Asia", country), 
         region = ifelse(region %in% "China", "China", region), 
         region = ifelse(region %in% c("China", "South Asia"), region, "Rest of the World"))

# convert data from wode to long
ar_global_fig1.2_data <- ar_global_fig1.2_data %>%
  group_by(region) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2022_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+")))) 

# add global trendlines data to the above dataset
ar_global_fig1.2_data <- ar_global_fig1.2_data %>%
  rbind(trendlines_aqli_data_global)

ar_global_fig1.2_data$region <- factor(ar_global_fig1.2_data$region, levels = c("South Asia", "China", "Rest of the World", "Global"))

ar_global_fig1.2 <- ar_global_fig1.2_data %>%
  ggplot() +  
  geom_line(mapping = aes(x = years, y = pop_weighted_avg_pm2.5, color = interaction(region), 
                          linetype = interaction(region), lwd = 0.7), lwd = 2) +
  labs(x = "Year", y = expression("Annual Average " ~ PM[2.5] ~ " concentrations (in µg/m³)"), 
       color = "") +
  ggthemes::theme_fivethirtyeight() +
  scale_color_manual(values = c("South Asia" = "darkred", 
                                "China" = "orange", 
                                "Rest of the World" = "khaki", 
                                "Global" = "snow4"), 
                     breaks = c("South Asia", 
                                "China", 
                                "Rest of the World", 
                                "Global"), 
                     name = "legend") +
  scale_linetype_manual(values = c("South Asia" = "dashed", 
                                   "China" = "dashed", 
                                   "Rest of the World" = "dashed", 
                                   "Global" = "solid"), 
                        name = "legend") +
  theme(legend.position = "bottom", legend.title = element_blank(), 
        legend.text = element_text(size = 7), 
        axis.title.y = element_text(size = 9), 
        axis.title.x = element_text(size = 9)) +
  scale_y_continuous(breaks = seq(0, 60, 10), limits = c(0, 60)) +
  scale_x_continuous(breaks = c(seq(1998, 2022, 3))) +
  guides(guide_legend(reverse = TRUE)) +
  themes_aqli_base +
  theme(plot.background = element_rect(fill = "white", color = "white"), 
        legend.title = element_blank(), 
        legend.key.width = unit(1, "cm"))


# Global section figure 1.3 ============
#' 10 most populated countries in the world: population, life expectancy gains, 
#' total potential life years gained, 3 panel graph
ar_fig1.3_dataset <- gadm2_aqli_2022 %>%
  gadm_level_summary(c("country"), c(2022), 10) %>%
  slice_max(population, n = 10) %>%
  mutate(pop_millions = round(population/1000000, 1), 
         total_person_years_gained_billions = (llpp_who_2022*population)/1000000000)

ar_fig1.3_dataset$country <- factor(ar_fig1.3_dataset$country, levels = c("China", "India", "United States", "Indonesia", 
                                                              "Pakistan", "Nigeria", "Brazil", 
                                                              "Bangladesh", "Russia", 
                                                              "México"))


# population plot of the top 10 most populous
plt_top10_most_populous_population <- ar_fig1.3_dataset %>%
  ggplot() +
  geom_col(mapping = aes(x = forcats::fct_reorder(country, total_lyl_who_2022_millions), 
                         y = pop_millions, fill = country), 
           width = 0.7) +
  labs(x = "Country", y = "Population (in millions)") +
  scale_y_continuous(breaks = seq(0, 1500, 200)) +
  coord_flip() +
  ggthemes::theme_tufte() +
  themes_aqli_base +
  scale_fill_viridis_d(option = "inferno") +
  theme(legend.position = "none", 
        plot.background = element_rect(fill = "white", color = "white"))

# Average Life Expectancy Gains experienced by a person in top 10 most populous countries if PM2.5 is reduced to the WHO guideline
plt_top10_most_populous_le_gains_per_person <- ar_fig1.3_dataset %>%
  ggplot() +
  geom_col(mapping = aes(x = forcats::fct_reorder(country, total_lyl_who_2022_millions), 
                         y = llpp_who_2022, fill = country), 
           width = 0.7) +
  labs(x = "", y = "Average Life Expectancy Gains (Years)") +
  scale_y_continuous(breaks = seq(0, 8, 1)) +
  ggthemes::theme_tufte() +
  themes_aqli_base +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
  coord_flip() +
  scale_fill_viridis_d(option = "inferno") + 
  theme(legend.position = "none", 
        plot.background = element_rect(fill = "white", color = "white"))

# Total person years gained on the country level for the top 10 most populous regions in the world (if PM2.5 is reduced to the WHO guideline)

plt_top10_most_populous_tot_person_years_gained <- ar_fig1.3_dataset %>%
  ggplot() +
  geom_col(mapping = aes(x = forcats::fct_reorder(country, total_lyl_who_2022_millions), 
                         y = total_person_years_gained_billions, fill = country), 
           width = 0.7) +
  labs(x = "", y = "Total Person Years Gained (Billion Years)") +
  scale_y_continuous(breaks = seq(0, 8, 1)) +
  ggthemes::theme_tufte() +
  themes_aqli_base +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
  coord_flip() +
  scale_fill_viridis_d(option = "inferno") + 
  theme(legend.position = "none", 
        plot.background = element_rect(fill = "white", color = "white"))

# Combine all 3 graphs in a panel
ar_global_fig1.3 <- gridExtra::grid.arrange(plt_top10_most_populous_population , 
                                            plt_top10_most_populous_le_gains_per_person, 
                                            plt_top10_most_populous_tot_person_years_gained, 
                                            nrow = 1)

```

# AR Section 2: South Asia 
```{r}

# South Asia figure 2.1 ============

# south asia figure 2.1 dataset
ar_south_asia_fig2.1_data <- gadm2_aqli_2022 %>%
  filter(country %in% south_asia_def) %>%
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# south asia fig 2.1
ar_south_asia_fig2.1 <- ar_south_asia_fs_fig2.1_data %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), color = "aliceblue", lwd = 0.05) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 %in% south_asia_def), color = "azure4", fill = "transparent", lwd = 0.1) +
  geom_sf(data = gadm0_aqli_2022_shp %>% filter(name0 %in% south_asia_def), color = "cornsilk4", fill = "transparent", lwd = 0.3) +
  ggthemes::theme_map() +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  ggthemes::theme_map() +
  labs(fill = "Potential gain in life expectancy (Years)  ", title = "", 
       subtitle = "") + 
  theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15), 
        # legend.key = element_rect(color = "black"),
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 12), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
        legend.key = element_rect(color = "black"), 
        legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal", 
        plot.background = element_rect(fill = "white", color = "white")) +
  guides(fill = guide_legend(nrow = 1))


# South Asia figure 2.2 ============
# GBD results filtered for relevant cause of death and countries 
gbd_results_sa_fig2.2 <- gbd_results_master_2022 %>%
  filter(cause_of_death %in% c("PM2.5 relative to WHO guideline",
                               "Cardiovascular diseases", "Child and maternal malnutrition", 
                               "Tobacco", "High systolic blood pressure"), country %in% c("Bangladesh", "Nepal", "India", "Pakistan"))

# making the 'location' column of type factor
gbd_results_sa_fig2.2$country <- factor(gbd_results_sa_fig2.2$country, 
                                        levels = c("Bangladesh", "Nepal", "India", "Pakistan"))


# Converting 'cause_of_death' to type factor
gbd_results_sa_fig2.2$cause_of_death <- as.factor(gbd_results_sa_fig2.2$cause_of_death)

# Rearranging 'cause of death' levels
levels(gbd_results_sa_fig2.2$cause_of_death) <- c("Cardiovascular diseases", "Child and maternal malnutrition", "High systolic blood pressure", "PM2.5 relative to WHO guideline", "Tobacco")

# wrapping x-axis labels text 
levels(gbd_results_sa_fig2.2$cause_of_death) <- str_wrap(levels(gbd_results_sa_fig2.2$cause_of_death), 30)

# getting country wise population
country_wise_population <- gadm2_aqli_2022 %>%
  filter(country %in% south_asia_def) %>%
  gadm_level_summary(c("country"), c(2022), 10) %>%
  filter(country %in% c("Bangladesh", "India", "Nepal", "Pakistan")) %>%
  arrange(desc(population))

# reorder within each location as per the total life years lost column
gbd_results_sa_fig2.2 <- gbd_results_sa_fig2.2 %>% 
  mutate(cause_of_death = reorder_within(cause_of_death, lyl, country))

# clean the "cause of death" column and save the cwafrica factsheet figure 2
gbd_results_sa_fig2.2 <- gbd_results_sa_fig2.2 %>%
  mutate(cause_of_death = str_remove(cause_of_death, "___.+"))

# plot 
ar_south_asia_fig2.2 <- gbd_results_sa_fig2.2 %>%
  ggplot(mapping = aes(x = reorder_within(cause_of_death, lyl, country), y = lyl)) + 
  geom_col(mapping = aes(fill = cause_of_death), width = 0.5, color = "white") +
  scale_x_reordered() +
  facet_wrap(~factor(country, levels = c("Bangladesh", "Nepal", "India", 
                  "Pakistan")), scales = "free_x", ncol = 4) +
  scale_fill_manual(values = c("#D3D9E0", "#7BC1D9", "#808A94", "#8F3931",
                               "darkkhaki")) +
  labs(x = "Threats to Life Expectancy", y = "Life Years Lost", title = "", 
       subtitle = "", fill = "Threats to Life Expectancy") +
  themes_aqli_base +
  theme(axis.text.x = element_blank(), legend.position = "bottom", axis.ticks = element_blank(), 
         strip.text = element_text(size = 14), 
         plot.background = element_rect(fill = "white", color = "white")) 

```

# AR Section 3: South East Asia

```{r}
# southeast asia definition
se_asia_def <-  c("Brunei", "Myanmar", "Cambodia", "Timor-Leste", "Indonesia",
                  "Laos", "Malaysia", "Philippines", "Singapore", "Thailand",
                  "Vietnam")

# southeast asia figure 3.1 ===================================

# southeast asia figure 3.1 dataset
ar_se_asia_fig3.1_data <- gadm2_aqli_2022 %>%
  filter(country %in% se_asia_def) %>%
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# southeast asia figure 3.1: map
ar_se_asia_fig3.1 <- ar_se_asia_fig3.1_data %>%
  ggplot() +
  geom_sf(mapping = aes(fill = reorder(lyl_bucket, order_lyl_bucket)), color = "aliceblue", lwd = 0.05) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 %in% se_asia_vec), color = "azure4", fill = "transparent", lwd = 0.1) +
  geom_sf(data = gadm0_aqli_2022_shp %>% filter(name0 %in% se_asia_vec), color = "cornsilk4", fill = "transparent", lwd = 0.3) +
  ggthemes::theme_map() +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff",
                               "0.1 to < 0.5" = "#ffeda0",
                               "0.5 to < 1" = "#fed976",
                               "1 to < 2" = "#feb24c",
                               "2 to < 3" = "#fd8d3c",
                               "3 to < 4" = "#fc4e2a",
                               "4 to < 5" = "#e31a1c",
                               "5 to < 6" = "#bd0026",
                               ">= 6" = "#800026")) +
  ggthemes::theme_map() +
  labs(fill = "Potential gain in life expectancy (Years)") +
  theme(legend.position = "bottom",
        legend.justification = c(0.5, 3),
        legend.background = element_rect(color = "black"),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15),
        plot.title = element_text(hjust = 0.5, size = 15),
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 7),
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"),
        legend.key = element_rect(color = "black"),
        legend.box.spacing = unit(0, "cm"),
        legend.direction = "horizontal",
        plot.background = element_rect(fill = "white", color = "white")) +
  guides(fill = guide_legend(nrow = 1))

# southeast asia figure 3.2 ================================

# southeast asia figure 3.2 data
ar_se_asia_fig3.2_data <- gadm2_aqli_2022 %>%
  filter(country %in% se_asia_def) %>%
  select(country, name_1, name_2, population, pm2022, llpp_who_2022) %>%
  group_by(name_1) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         pm2022_pop_weighted = pop_weights*pm2022,
         llpp_who_2022_pop_weighted = pop_weights*llpp_who_2022) %>%
  summarise(tot_pop = sum(population, na.rm = TRUE),
            avg_pm2.5_2022 = sum(pm2022_pop_weighted, na.rm = TRUE),
            le_gain = (avg_pm2.5_2022 - who_guideline)*le_constant,
            llpp_who_2022 = sum(llpp_who_2022_pop_weighted, na.rm = TRUE),
            le_gain = ifelse(le_gain < 0 , 0, le_gain)) %>%
  slice_max(tot_pop, n = 10) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022")

# southeast asia figure 3.2: 10 most populous regions
ar_se_asia_fig3.2 <- ar_se_asia_fig3.2_data %>%
  ggplot() +
  geom_col(mapping = aes(x = reorder(name_1, llpp_who_2022), y = llpp_who_2022, fill = lyl_bucket), width = 0.5) +
  labs(x = "Region", y = "Potential Gain in Life Expectancy (Years)", fill = "Potential gain in life expectancy (Years)") +
  scale_y_continuous(breaks = seq(0, 3, 1), limits = c(0, 3)) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff",
                               "0.1 to < 0.5" = "#ffeda0",
                               "0.5 to < 1" = "#fed976",
                               "1 to < 2" = "#feb24c",
                               "2 to < 3" = "#fd8d3c",
                               "3 to < 4" = "#fc4e2a",
                               "4 to < 5" = "#e31a1c",
                               "5 to < 6" = "#bd0026",
                               ">= 6" = "#800026")) +
  coord_flip() +
  ggthemes::theme_tufte() +
  themes_aqli_base +
  theme(plot.background = element_rect(color = "white", fill = "white"))

# southeast asia figure 3.3 ===============================================

#filter for relevant countries
country_list <- c("Indonesia", "Vietnam", "Thailand", "Myanmar", "Malaysia")
# filter for relevant cause of death
diseases_list <- c("PM2.5 relative to WHO guideline",
                   "Respiratory infections and tuberculosis",
                   "Diabetes and kidney diseases",
                   "Child and maternal malnutrition",
                   "High LDL cholesterol")

ar_se_asia_fig3.3_data <- gbd_results_master_2022 %>%
  filter(cause_of_death %in% diseases_list, country %in% country_list)

# making the 'location' column of type factor
ar_se_asia_fig3.3_data$country <- factor(ar_se_asia_fig3.3_data$country,
                                         levels = country_list)

# Converting 'cause_of_death' to type factor
ar_se_asia_fig3.3_data$cause_of_death <- factor(ar_se_asia_fig3.3_data$cause_of_death, levels = diseases_list)

# wrapping x-axis labels text
levels(ar_se_asia_fig3.3_data$cause_of_death) <- str_wrap(levels(ar_se_asia_fig3.3_data$cause_of_death), 30)

# reorder within each location as per the total life years lost column
ar_se_asia_fig3.3_data <- ar_se_asia_fig3.3_data %>%
  mutate(cause_of_death = reorder_within(cause_of_death, lyl, country))

# clean the "cause of death" column and save the cwafrica factsheet figure 2
ar_se_asia_fig3.3_data <- ar_se_asia_fig3.3_data %>%
  mutate(cause_of_death = str_remove(cause_of_death, "___.+"))

# southeast asia figure 3.3: GBD
ar_se_asia_fig3.3 <- ar_se_asia_fig3.3_data %>%
  ggplot(mapping = aes(x = reorder_within(cause_of_death, lyl, country), y = lyl)) +
  geom_col(mapping = aes(fill = cause_of_death), width = 0.5, color = "white") +
  scale_x_reordered() +
  facet_wrap(~factor(country, levels = country_list), scales = "free_x", ncol = 5) +
  scale_fill_manual(labels = ~ stringr::str_wrap(.x, width = 30),
                    values = c("#B4CDD9", "#707F8C", "#ADE9FA", "#8F3931", "#CBE8F3")) +
  labs(x = "Threats to Life Expectancy", y = "Life Years Lost", title = "",
       subtitle = "", fill = "Threats to Life Expectancy") +
  themes_aqli_base +
  theme(axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        strip.text = element_text(size = 14),
        plot.background = element_rect(fill = "white", color = "white")) +
  scale_y_continuous(breaks = seq(0, 7, 0.5))


```


# AR Section 4: Central and West Africa

```{r}
# Central and West Africa figure 4.1 ============

# cw africa figure 4.1 dataset
ar_cw_africa_fig4.1_data <- gadm2_aqli_2022 %>%
  filter(country %in% central_and_west_african_countries) %>%
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# cw africa fig1 (burlywood4)
ar_cw_africa_fig4.1 <- ar_cw_africa_fig4.1_data %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), color = "aliceblue", lwd = 0.05) +
   geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 %in% central_and_west_african_countries), color = "azure4", fill = "transparent", lwd = 0.1) +
 geom_sf(data = gadm0_aqli_2022_shp %>% filter(name0 %in% central_and_west_african_countries), color = "cornsilk4", fill = "transparent", lwd = 0.3) +
  ggthemes::theme_map() +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  ggthemes::theme_map() +
  labs(fill = "Potential gain in life expectancy (Years)", 
       title = "", subtitle = "") +
  theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15), 
        # legend.key = element_rect(color = "black"),
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 12), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
        legend.key = element_rect(color = "black"), 
        legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal", 
        plot.background = element_rect(fill = "white", color = "white")) +
  guides(fill = guide_legend(nrow = 1))


# Central and West Africa figure 4.2 ============

# GBD results filtered for relevant cause of death and countries 
gbd_results_cwafrica_fig4.2 <- gbd_results_master_2022 %>%
  filter(cause_of_death %in% c("PM2.5 relative to WHO guideline",
                               "Neglected tropical diseases and malaria", "Unsafe water, sanitation, and handwashing", 
                               "HIV/AIDS and sexually transmitted infections"), country %in% c("Nigeria", "Democratic Republic of the Congo", "Angola", "Ghana", "Cameroon"))

# making the 'location' column of type factor
gbd_results_cwafrica_fig4.2$country <- factor(gbd_results_cwafrica_fig4.2$country, 
                                        levels = c("Nigeria", "Democratic Republic of the Congo", "Angola", "Ghana", "Cameroon"))

# Rename Democratic Republic of the Congo to DRC
gbd_results_cwafrica_fig4.2$country <-  str_replace(gbd_results_cwafrica_fig4.2$country, 
            "Democratic Republic of the Congo", "DR Congo")

# Converting 'cause_of_death' to type factor
gbd_results_cwafrica_fig4.2$cause_of_death <- as.factor(gbd_results_cwafrica_fig4.2$cause_of_death)

# Rearranging 'cause of death' levels
levels(gbd_results_cwafrica_fig4.2$cause_of_death) <- c( "HIV/AIDS and sexually transmitted infections", "Neglected tropical diseases and malaria", "PM2.5 relative to WHO guideline", "Unsafe water, sanitation, and handwashing")

# wrapping x-axis labels text 
levels(gbd_results_cwafrica_fig4.2$cause_of_death) <- str_wrap(levels(gbd_results_cwafrica_fig4.2$cause_of_death), 30)

# getting country wise population
country_wise_population <- gadm2_aqli_2022 %>%
  filter(country %in% central_and_west_african_countries) %>%
  gadm_level_summary(c("country"), c(2022), 10) %>%
  filter(country %in% c("Cameroon", "Nigeria", "Angola", "Ghana", 
                  "Democratic Republic of the Congo")) %>%
  arrange(desc(population))

# reorder within each location as per the total life years lost column
gbd_results_cwafrica_fig4.2 <- gbd_results_cwafrica_fig4.2 %>% 
  mutate(cause_of_death = reorder_within(cause_of_death, lyl, country))

# clean the "cause of death" column and save the cwafrica factsheet figure 2
gbd_results_cwafrica_fig4.2 <- gbd_results_cwafrica_fig4.2 %>%
  mutate(cause_of_death = str_remove(cause_of_death, "___.+"))

# plot 
ar_cw_africa_fig4.2_plt <- gbd_results_cwafrica_fig4.2 %>%
  ggplot(mapping = aes(x = reorder_within(cause_of_death, lyl, country), y = lyl)) + 
  geom_col(mapping = aes(fill = cause_of_death), width = 0.5, color = "white") +
  scale_x_reordered() +
  facet_wrap(~factor(country, levels = c("Angola", "Cameroon", "DR Congo", 
                  "Ghana", "Nigeria")), scales = "free_x", ncol = 5) +
  scale_fill_manual(values = c("#D3D9E0", "#7BC1D9", "#8F3931",
                               "#808A94")) +
  labs(x = "Threats to Life Expectancy", y = "Life Years Lost", title = "", 
       subtitle = "", fill = "Threats to Life Expectancy") +
  themes_aqli_base +
   theme(axis.text.x = element_blank(), legend.position = "bottom", axis.ticks = element_blank(), 
         strip.text = element_text(size = 14), 
         plot.background = element_rect(fill = "white", color = "white")) 

```


# AR Section 5: Latin America

```{r}
# Latin America definition
latin_america_countries_vec <- c("México", "Guatemala", "Honduras", "El Salvador",
                                 "Nicaragua", "Costa Rica", "Panama", "Colombia",
                                 "Venezuela", "Ecuador", "Peru", "Bolivia",
                                 "Brazil", "Paraguay", "Chile", "Argentina",
                                 "Uruguay", "Cuba", "Haiti", "Dominican Republic",
                                 "Puerto Rico")

# Latin America figure 5.1 ===========

# AR Figure 5.1 dataset
ar_fig5.1_dataset <- gadm2_aqli_2022 %>%
  filter(country %in% latin_america_countries_vec ) %>%
  select(country, name_1, name_2, population, pm2022, llpp_who_2022)

#ar_fig5.1_dataset <- gadm2_aqli_2022_latin_america %>%
 # mutate(name_1_country = str_c(name_1, "(", country, ")", sep = ""))

# Plot AR figure 5.1
ar_fig5.1 <- ar_fig5.1_dataset %>%
  group_by(name_1) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         pm2022_pop_weighted = pop_weights*pm2022) %>%
  summarise(tot_pop = sum(population, na.rm = TRUE), avg_pm2.5_pop_weighted = sum(pm2022_pop_weighted, na.rm = TRUE),
            gain_in_le = (avg_pm2.5_pop_weighted - who_guideline) * le_constant,
            gain_in_le = ifelse(gain_in_le < 0, 0, gain_in_le)) %>%
  ungroup() %>%
  slice_max(tot_pop, n = 15) %>%
      add_aqli_color_scale_buckets(scale_type = "lyl", col_name = "gain_in_le") %>%
      ggplot() +
      geom_col(mapping = aes(x = forcats::fct_reorder(!!as.symbol("name_1"), !!as.symbol("gain_in_le")), y = !!as.symbol("gain_in_le"), fill = forcats::fct_reorder(!!as.symbol("lyl_bucket"), !!as.symbol("order_lyl_bucket"))), color = "black") +
      scale_fill_manual(values = c("0 to < 0.1" = "#ffffff",
                                   "0.1 to < 0.5" = "#ffeda0",
                                   "0.5 to < 1" = "#fed976",
                                   "1 to < 2" = "#feb24c",
                                   "2 to < 3" = "#fd8d3c",
                                   "3 to < 4" = "#fc4e2a",
                                   "4 to < 5" = "#e31a1c",
                                   "5 to < 6" = "#bd0026",
                                   ">= 6" = "#800026")) +
      labs(x = "Region", y = "Potential Gain in Life Expectancy (Years)", title = "", subtitle = "", caption = "", fill = "Potential gain in life expectancy (Years)") +
      themes_aqli_base +
  theme(plot.background = element_rect(color = "white", fill = "white")) +
      coord_flip()


# Latin America figure 5.2 ===========

# data
ar_fig5.2_data <- gadm2_aqli_2022 %>%
  filter(country %in% latin_america_countries_vec) %>%
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# plot
ar_fig5.2 <- ar_fig5.2_data %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), color = "aliceblue", lwd = 0.05) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 %in% latin_america_countries_vec), color = "azure4", fill = "transparent", lwd = 0.1) +
  geom_sf(data = gadm0_aqli_2022_shp %>% filter(name0 %in% latin_america_countries_vec), color = "cornsilk4", fill = "transparent", lwd = 0.3) +
  ggthemes::theme_map() +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff",
                               "0.1 to < 0.5" = "#ffeda0",
                               "0.5 to < 1" = "#fed976",
                               "1 to < 2" = "#feb24c",
                               "2 to < 3" = "#fd8d3c",
                               "3 to < 4" = "#fc4e2a",
                               "4 to < 5" = "#e31a1c",
                               "5 to < 6" = "#bd0026",
                               ">= 6" = "#800026")) +
  ggthemes::theme_map() +
  labs(fill = "Potential gain in life expectancy (Years)  ", title = "",
       subtitle = "") +
  theme(legend.position = "bottom",
        legend.justification = c(0.5, 3),
        legend.background = element_rect(color = "black"),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15),
        plot.title = element_text(hjust = 0.5, size = 15),
        # legend.key = element_rect(color = "black"),
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 12),
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"),
        legend.key = element_rect(color = "black"),
        legend.box.spacing = unit(0, "cm"),
        legend.direction = "horizontal",
        plot.background = element_rect(fill = "white", color = "white")) +
  guides(fill = guide_legend(nrow = 1))


# Latin America figure 5.3 ===========

diseases_list <- c("Unsafe water, sanitation, and handwashing",
                               "HIV/AIDS and sexually transmitted infections",
                               "Child and maternal malnutrition",
                     "Self-harm and interpersonal violence",
                   "PM2.5 relative to WHO guideline")

country_list <- c("El Salvador", "Guatemala", "Brazil", "Mexico", "Colombia")

# GBD results filtered for relevant cause of death (given Europe) and countries
ar_fig5.3_data <- gbd_results_master_2022 %>%
  filter(cause_of_death %in% diseases_list, country %in% country_list)

# making the 'location' column of type factor
ar_fig5.3_data$country <- factor(ar_fig5.3_data$country,
                                        levels = country_list)

# Converting 'cause_of_death' to type factor
ar_fig5.3_data$cause_of_death <- factor(ar_fig5.3_data$cause_of_death, levels = diseases_list)

# wrapping x-axis labels text
levels(ar_fig5.3_data$cause_of_death) <- str_wrap(levels(ar_fig5.3_data$cause_of_death), 30)

# reorder within each location as per the total life years lost column
ar_fig5.3_data <- ar_fig5.3_data %>%
  mutate(cause_of_death = reorder_within(cause_of_death, lyl, country))

# clean the "cause of death" column and save the cwafrica factsheet figure 2
ar_fig5.3_data <- ar_fig5.3_data %>%
  mutate(cause_of_death = str_remove(cause_of_death, "___.+"))

# plot
ar_fig5.3 <- ar_fig5.3_data %>%
  ggplot(mapping = aes(x = reorder_within(cause_of_death, lyl, country), y = lyl)) +
  geom_col(mapping = aes(fill = cause_of_death), width = 0.5, color = "white") +
  scale_x_reordered() +
  facet_wrap(~factor(country, levels = country_list), scales = "free_x", ncol = 5) +
  scale_fill_manual(values = c("#B4CDD9", "#707F8C", "#8F3931",
                                "#ADE9FA", "#CBE8F3")) +
  labs(x = "Threats to Life Expectancy", y = "Life Years Lost", title = "",
       subtitle = "", fill = "Threats to Life Expectancy") +
  themes_aqli_base +
  theme(axis.text.x = element_blank(), legend.position = "bottom", axis.ticks = element_blank(),
         strip.text = element_text(size = 14),
         plot.background = element_rect(fill = "white", color = "white"))

```


# AR Section 6: China

```{r}

# filter China data and add broad region identifiers. common for figures 6.1 and 6.3
color_2022_china <- gadm2_aqli_2022 %>%
  filter(country == "China", !is.na(population))

# BTH region (name_1)
bth_region <- c("Beijing", "Tianjin", "Hebei")

# YRD (name_1)
yrd_region <- c("Shanghai", "Jiangsu", "Zhejiang")

# PRD (name_1, name_2)
prd_region_name_2_guandong_regions <- c("Dongguan", "Foshan", "Guangzhou", 
                                        "Huizhou", "Jiangmen", "Shenzhen", 
                                        "Zhaoqing", "Zhongshan", "Zhuhai")
prd_region_name_1 <- c("Hong Kong", "Macau")
prd <- c(prd_region_name_2_guandong_regions, prd_region_name_1)

# add region column
color_2022_china  <- color_2022_china %>%
  mutate(region = ifelse(name_1 %in% bth_region, "BTH", "others"), 
         region = ifelse(name_1 %in% yrd_region,  "YRD", region), 
         region = ifelse(name_1 %in% prd_region_name_1, "PRD", region), 
         region = ifelse(name_2 %in% prd_region_name_2_guandong_regions, "PRD", region)) 

# China figure 6.1 ============

# China section fig1 data part-1: trend lines figure region wise (BTH, YRD, PRD) dataset
trendlines_china_region_wise_df <- color_2022_china %>%
  group_by(region) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2022_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+")))) %>%
  select(years, region, pop_weighted_avg_pm2.5) %>%
  filter(region %in% c("YRD", "BTH", "PRD"))

# China section fig1 data (part-2): trend line national average dataset
trendline_national_avg_df <- color_2022_china %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2022_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))), 
         region = "China") %>% 
  select(years, region, pop_weighted_avg_pm2.5)

# China section figure 1 data final
ar_china_fig6.1_data <- rbind(trendlines_china_region_wise_df, trendline_national_avg_df)

ar_china_fig6.1_data <- ar_china_fig6.1_data %>%
    mutate(region_order = ifelse(region == "China", 1, NA), 
         region_order = ifelse(region == "PRD", 2, region_order), 
         region_order = ifelse(region == "YRD", 3, region_order), 
         region_order = ifelse(region == "BTH", 4, region_order))

ar_china_fig6.1_data$region <- factor(ar_china_fig6.1_data$region, levels = c("BTH", "China", "YRD", "PRD"))

# plot china factsheet figure 3
ar_china_fig6.1 <- ar_china_fig6.1_data %>%
  ggplot() +
  geom_line(mapping = ggplot2::aes(x = years, y = pop_weighted_avg_pm2.5, color = interaction(region), 
                                   linetype = interaction(region)), lwd = 1.1) +
  geom_hline(mapping = aes(yintercept = 5), lwd = 0.5, linetype = "dashed") +
  geom_vline(mapping = aes(xintercept = 2014), lwd = 0.5, linetype = "dashed") +
  scale_y_continuous(breaks = seq(0, 100, 10), limits = c(0, 100)) +
  scale_x_continuous(breaks = c(seq(1998, 2022, 3))) +
  scale_color_manual(values = c("PRD" = "#7197be", "China" = "#5f7aa5", "BTH" = "#5f7aa5", "YRD" = "#7197be"), name = "legend") +
  scale_linetype_manual(values = c("PRD" = "dashed", "China" = "solid", "BTH" = "dashed", "YRD" = "dashed"), name = "legend") +
  ggthemes::theme_clean() +
  themes_aqli_base +
  labs(x = "Year", 
       y = expression("Annual Average  " ~ PM[2.5] ~ " Concentration (in µg/m³)"), 
       title = "", 
    subtitle = "", 
    color = "Region") +
  theme(legend.position = "bottom", legend.title = element_blank(), 
        plot.background = element_rect(fill = "white", color = "white"), 
        legend.key.width = unit(2, "cm")) + 
  geom_text(x = 2002.1, y = 8.1, label = expression("WHO" ~ PM[2.5] ~ "Guideline (last updated: 2021): 5 µg/m³")) + 
  geom_text(x = 2015.8, y = 92.8, label = str_wrap("China announces war on pollution", width = 18)) 


# China figure 6.2 ============

# filter data for china and create shapefile
ar_china_fig6.2_data <- gadm2_aqli_2022 %>%
  filter(country == "China") %>%
  mutate(lyl2014minus2022 = round((pm2014 - pm2022)*0.098, 1)) %>% # to reflect gain in life expectancy
  add_aqli_color_scale_buckets(scale_type = "lyldiff", col_name = "lyl2014minus2022") %>% 
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# china figure 2
ar_china_fig6.2 <- ar_china_fig6.2_data %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyldiff_bucket, order_lyldiff_bucket)), color = "aliceblue", lwd = 0.05) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 == "China"), color = "azure4", fill = "transparent", lwd = 0.15) +
  geom_sf(data = gadm0_aqli_2022_shp %>% filter(name0 == "China"), color = "cornsilk", fill = "transparent", lwd = 0.5) +
  ggthemes::theme_map() + 
  scale_fill_manual(values = c(">= 2" = "#4575b4",
                               "0.5 to (< 2)" = "#74add1",
                               "0.1 to (< 0.5)" = "#abd9e9",
                               "0 to (< 0.1)" = "#e0f3f8",
                               "-0.1 to (< 0)" = "#fee090",
                               "-0.5 to (< -0.1)" = "#fdae61",
                               "-2 to (< -0.5)" = "#f46d43",
                               "< -2" = "#d73027")) +
  ggthemes::theme_map() +
  labs(fill = "Change in life expectancy between 1998 and 2022 \n(Years; blue values indicate improvement)", title = "") + 
  theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15),
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 7), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"),
        legend.key = element_rect(color = "black"), 
        legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal",
        plot.background = element_rect(fill = "white", color = "white")) +
  guides(fill = guide_legend(nrow = 1))


# China figure 6.4 ============

# top 5 most deadly diseases
ar_china_fig6.4_dataset <- gbd_results_master_2022 %>%
  filter(country == "China") %>%
  slice_max(lyl, n = 5)

colnames(ar_china_fig6.4_dataset)[3] <- c("llpp_who_2022")

ar_china_fig6.4_dataset <- ar_china_fig6.4_dataset %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022")

# figure 4 plot 
ar_china_fig6.4 <- ar_china_fig6.4_dataset %>%
  ggplot() + 
  geom_col(mapping = aes(x = forcats::fct_reorder(cause_of_death, llpp_who_2022), 
                         y = llpp_who_2022, fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), 
           width = 0.4, color = "black") +
  labs(x = "Threats to Life Expectancy", y = "Life Years Lost", fill = "Life years lost", 
       title = "") +
  coord_flip() + 
  ggthemes::theme_tufte() +
  themes_aqli_base +
  theme(legend.position = "bottom",
        axis.text = element_text(size = 14),
        axis.title.y = element_text(size = 16, margin = margin(r = 0.6, unit = "cm")),
        axis.title.x = element_text(size = 16, margin = margin(t = 0.6, b = 0.6, unit = "cm")),
        plot.caption = element_text(hjust = 0, size = 8, margin = margin(t = 0.8, unit = "cm")),
        plot.title = element_text(hjust = 0.5, size = 20, margin = margin(b = 0.8, unit = "cm")),
        plot.subtitle = element_text(hjust = 0.5, size = 10, margin = margin(b = 0.8, unit = "cm")),
        legend.box.background = element_rect(color = "black"),
        axis.line = element_line(), 
        legend.text = element_text(size = 11), 
        legend.title = element_text(size = 14),
        panel.grid.major.y = element_blank(), 
        plot.background = element_rect(fill = "white", color = "white")) +
  scale_y_continuous(breaks = seq(0, 7, 1)) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) + 
  guides(fill = guide_legend(nrow = 1)) 

```


# AR Section 7: US and Europe

```{r}
# US + Europe figure 7.1 ======

# percent reduction in pollution since 1970
caa_pct_reduction <- 0.67 

# set directory to where Clean Air Act folder files (as downloaded from the AQLI website)

# US state level shapefile
us_states_shp <- gadm1_aqli_2022_shp %>%
  filter(!(name1 %in% c("Alaska", "Hawaii")))

# US county level shape file
county_shp <- gadm2_aqli_2022_shp %>%
  filter(name0 == "United States")

# use county pm25 for aqli csv file
county_data <- read_csv("~/Desktop/AQLI/2024 AQLI Update/CleanAirAct/final/county_pm25_foraqli_stats.csv")

# Change in life expectancy map (change geo_name to name_2) and remove any counties that belong to Hawaii or Alaska
county_shp <- inner_join(county_shp, county_data, by = c("obidgadm2"="objectid_gadm2")) %>%
  filter(!(name2 %in% c("Anchorage", "Honolulu")))

# fig 7.1 data
us_1970_2022_map_data <- county_shp %>%
  add_aqli_color_scale_buckets("lyldiff", "lifeyears_saved") %>%
  select(-geometry, geometry)

# fig 7.1
ar_fig7.1 <- us_1970_2022_map_data %>%
  st_as_sf() %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyldiff_bucket, order_lyldiff_bucket)), color = "aliceblue", lwd = 0.05) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 == "United States", name1 %notin% c("Alaska", "Hawaii")), color = "azure4", fill = "transparent", lwd = 0.5) +
  ggthemes::theme_map() +
  scale_fill_manual(values = c(">= 2" = "#4575b4",
                               "0.5 to (< 2)" = "#74add1",
                               "0.1 to (< 0.5)" = "#abd9e9",
                               "0 to (< 0.1)" = "#e0f3f8",
                               "-0.1 to (< 0)" = "#fee090",
                               "-0.5 to (< -0.1)" = "#fdae61",
                               "-2 to (< -0.5)" = "#f46d43",
                               "< -2" = "#d73027")) +
  ggthemes::theme_map() +
  labs(fill = "Change in life expectancy between 1970 and 2022 (Years; blue values indicate improvement)", title = "") +
  theme(legend.position = "bottom",
        legend.justification = c(0.5, 3),
        legend.background = element_rect(color = "black"),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15),
        plot.title = element_text(hjust = 0.5, size = 15),
        # legend.key = element_rect(color = "black"),
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 7),
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"),
        legend.key = element_rect(color = "black"),
        legend.box.spacing = unit(0, "cm"),
        legend.direction = "horizontal",
        plot.background = element_rect(fill = "white", color = "white")) +
  guides(fill = guide_legend(nrow = 1))


# US + Europe figure 7.2 ======

# get USA country level data from the color file
color_data_usa <- gadm2_aqli_2022 %>%
  filter(country == "United States", name_1 != "Alaska", name_1 != "Hawaii")

# filter colormap (county level) shape file to only include United States
colormap_shp_usa <- gadm2_aqli_2022_shp %>%
  filter(name0  == "United States", name1 != "Alaska", name1 != "Hawaii")

# rename columns in the USA county level shape file
colormap_shp_usa <- colormap_shp_usa %>%
  rename(country = name0,
         name_1 = name1, 
         name_2 = name2)

# chart5 dataset: join colormap and USA county level shape file and adding a grouping column
ar_fig7.2_data <- colormap_shp_usa %>%
  left_join(color_data_usa, by = c("country", "name_1", "name_2")) %>%
  mutate(pollution_category = ifelse(pm2021 >= 0 & pm2021 <= 5, "0 - 5", pm2021), 
         pollution_category = ifelse(pm2021 > 5 & pm2021 <= 10, "> 5 - 10", pollution_category), 
         pollution_category = ifelse(pm2021 > 10 & pm2021 <= 15, "> 10 - 15", pollution_category), 
         pollution_category = ifelse(pm2021 > 15, "> 15", pollution_category)) %>%
  mutate(order_pollution_category = ifelse(pollution_category == "0 - 5", 1, 0), 
         order_pollution_category = ifelse(pollution_category == "> 5 - 10", 2, order_pollution_category), 
         order_pollution_category = ifelse(pollution_category == "> 10 - 15", 3, order_pollution_category), 
         order_pollution_category = ifelse(pollution_category == "> 15", 4, order_pollution_category))

# fig 7.2 
ar_fig7.2 <- ggplot(data = ar_fig7.2_data) +
  geom_sf(mapping = aes(fill = fct_reorder(pollution_category, order_pollution_category)), color = "aliceblue") + 
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 == "United States", name1 != "Alaska", name1 != "Hawaii"), fill = "transparent", color = "white", lwd = 1) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 == "United States", name1 == "California", name1 != "Alaska", name1 != "Hawaii"), fill = "transparent", color = "white", lwd = 1) +
  ggthemes::theme_map() +
  labs(fill = expression("Annual Average" ~ PM[2.5] ~ " Concentration (in  µg/m³)"), title = "") +
  scale_fill_manual(values = c("0 - 5" = "powderblue", "> 5 - 10" = "#FFCC66", "> 10 - 15" = "chocolate2", "> 15" = "darkred")) +
  theme(plot.background = element_rect(colour = "white", fill = "white"), 
        legend.position = "bottom", 
        legend.justification = "center", 
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 16),
        legend.box.background = element_rect(color = "black")) 


# Europe definition and shapefile for figures 7.3 and 7.4
# exclude the following countries to keep the map less wide and to show a stark difference between eastern and western europe
exclude_countries <-  c("Russia", "Turkey", "Sweden", "Finland", "Norway", 
                        "Kazakhstan", "Iceland", "Georgia", "Azerbaijan", 
                        "Armenia", "Cyprus", "Northern Cyprus", 
                        "Svalbard and Jan Mayen")

countries_except_excluded <- european_countries %>% 
  filter(Country %notin% exclude_countries)

europe_gadm1_shp <- gadm1_aqli_2022_shp %>% 
  filter(name0 %in% unlist(countries_except_excluded)) %>% 
  filter(!(name0 == "Spain" & name1 == "Islas Canarias")) %>%
  filter(!(name0 == "Portugal" & name1 == "Azores")) %>%
  filter(!(name0 == "Portugal" & name1 == "Madeira"))

# very important: this code is run to obtian a country level shapefile of Europe without
# Islas Canarias, Azores and Madeira
europe_gadm0_shp <- europe_gadm1_shp %>% 
  count(name0)

# US + Europe figure 7.3 ======

# europe dataset
ar_fig7.3_data <- gadm2_aqli_2022 %>%
  filter(country %in% unlist(countries_except_excluded)) %>%
  filter(!(country == "Spain" & name_1 == "Islas Canarias")) %>%
  filter(!(country == "Portugal" & name_1 == "Azores")) %>%
  filter(!(country == "Portugal" & name_1 == "Madeira")) %>%
  mutate(lyl1998minus2022 = round((pm1998 - pm2022)*0.098, 2)) %>% # to reflect gain in life expectancy
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  add_aqli_color_scale_buckets("lyldiff", "lyl1998minus2022") %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# europe fig 7.3
ar_fig7.3 <- ar_fig7.3_data %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyldiff_bucket, order_lyldiff_bucket)), color = "aliceblue", lwd = 0.05) +
  geom_sf(data = europe_gadm1_shp, color = "azure4", fill = "transparent", lwd = 0.1) +
  geom_sf(data = europe_gadm0_shp, color = "cornsilk4", fill = "transparent", lwd = 0.3) +
  ggthemes::theme_map()  +
  scale_fill_manual(values = c(">= 2" = "#4575b4",
                               "0.5 to (< 2)" = "#74add1",
                               "0.1 to (< 0.5)" = "#abd9e9",
                               "0 to (< 0.1)" = "#e0f3f8",
                               "-0.1 to (< 0)" = "#fee090",
                               "-0.5 to (< -0.1)" = "#fdae61",
                               "-2 to (< -0.5)" = "#f46d43",
                               "< -2" = "#d73027")) +
  ggthemes::theme_map() +
  labs(fill = "Change in life expectancy between 1998 and 2022 \n(Years; blue values indicate improvement)", title = "", 
       subtitle = "") + 
  theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15), 
        # legend.key = element_rect(color = "black"),
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 12), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
        legend.key = element_rect(color = "black"), 
        legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal", 
        plot.background = element_rect(fill = "white", color = "white")) +
  guides(fill = guide_legend(nrow = 1)) 


# US + Europe figure 7.4 ======

# generate large east and west Europe polygons, then find their intersection to 
# mark their border
eastern_europe_large_polygon <- europe_gadm1_shp %>%
  filter(name0 %notin% western_european_countries) %>% 
  st_union()
  
western_europe_large_polygon <- europe_gadm1_shp %>%
  filter(name0 %in% western_european_countries) %>% 
  st_union()

east_west_border <- st_intersection(eastern_europe_large_polygon, western_europe_large_polygon, model = "closed")

# europe dataset
ar_fig7.4_data <- gadm2_aqli_2022 %>%
  filter(country %in% unlist(countries_except_excluded)) %>%
  filter(!(country == "Spain" & name_1 == "Islas Canarias")) %>%
  filter(!(country == "Portugal" & name_1 == "Azores")) %>%
  filter(!(country == "Portugal" & name_1 == "Madeira")) %>%
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# europe fs fig 7.4
ar_fig7.4 <- ar_fig7.4_data %>%
  filter(country %notin% c("Svalbard and Jan Mayen")) %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), color = "aliceblue", lwd = 0.05) +
  geom_sf(data = europe_gadm1_shp, color = "azure4", fill = "transparent", lwd = 0.1) +
  geom_sf(data = europe_gadm0_shp, color = "cornsilk4", fill = "transparent", lwd = 0.3) +
  geom_sf(data = east_west_border, color = "black", fill = NA, lwd = 1) +
  ggthemes::theme_map()  +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  ggthemes::theme_map() +
  labs(fill = "Potential gain in life expectancy (Years)  ", title = "", 
       subtitle = "") + 
  annotate("text", x = 33, y = 61, label = "Eastern Europe: 13 µg/m³, \n9.4 months potential gain") +
  annotate("text", x =-11, y = 35, label = "Western Europe: 10 µg/m³, \n4.8 months potential gain") +
  theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15), 
        # legend.key = element_rect(color = "black"),
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 12), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
        legend.key = element_rect(color = "black"), 
        legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal", 
        plot.background = element_rect(fill = "white", color = "white")) +
  guides(fill = guide_legend(nrow = 1)) 

```

# AR Section 8: Middle East and North Africa

```{r}
# MENA figure 8.1 ============

# MENA figure 8.1 dataset
ar_mena_fig8.1_data <- gadm2_aqli_2022 %>%
  filter(country %in% mena_countries) %>%
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# MENA fig1 (burlywood4)
ar_mena_fig8.1 <- ar_mena_fig8.1_data %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), color = "aliceblue", lwd = 0.05) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 %in% mena_countries), color = "azure4", fill = "transparent", lwd = 0.1) +
  geom_sf(data = gadm0_aqli_2022_shp %>% filter(name0 %in% mena_countries), color = "cornsilk4", fill = "transparent", lwd = 0.3) +
  ggthemes::theme_map() +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  ggthemes::theme_map() +
  labs(fill = "Potential gain in life expectancy (Years)", 
       title = "", subtitle = "") +
  theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15), 
        # legend.key = element_rect(color = "black"),
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 12), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
        legend.key = element_rect(color = "black"), 
        legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal", 
        plot.background = element_rect(fill = "white", color = "white")) +
  guides(fill = guide_legend(nrow = 1))


# MENA figure 8.2 ============

# GBD results filtered for relevant cause of death and countries 
gbd_results_mena_fig8.2 <- gbd_results_master_2022 %>%
  filter(cause_of_death %in% c("Neoplasms", "PM2.5 relative to WHO guideline", 
                               "Tobacco", "Transport injuries"), 
         country %in% c("Algeria", "Egypt", "Iraq", "Qatar", "Saudi Arabia"))

# making the 'location' column of type factor
gbd_results_mena_fig8.2$country <- factor(gbd_results_mena_fig8.2$country, 
                                              levels = c("Algeria", "Egypt", "Iraq", "Qatar", "Saudi Arabia"))

# Converting 'cause_of_death' to type factor
gbd_results_mena_fig8.2$cause_of_death <- as.factor(gbd_results_mena_fig8.2$cause_of_death)

# Rearranging 'cause of death' levels
levels(gbd_results_mena_fig8.2$cause_of_death) <- c("Neoplasms", "PM2.5 relative to WHO guideline", "Tobacco", "Transport injuries")

# wrapping x-axis labels text 
levels(gbd_results_mena_fig8.2$cause_of_death) <- str_wrap(levels(gbd_results_mena_fig8.2$cause_of_death), 30)

# getting country wise population
country_wise_population <- gadm2_aqli_2022 %>%
  filter(country %in% mena_countries) %>%
  gadm_level_summary(c("country"), c(2022), 10) %>%
  filter(country %in% c("Algeria", "Egypt", "Iraq", "Qatar", "Saudi Arabia")) %>%
  arrange(desc(population))

# reorder within each location as per the total life years lost column
gbd_results_mena_fig8.2 <- gbd_results_mena_fig8.2 %>% 
  mutate(cause_of_death = reorder_within(cause_of_death, lyl, country))

# clean the "cause of death" column and save the cwafrica factsheet figure 2
gbd_results_mena_fig8.2 <- gbd_results_mena_fig8.2 %>%
  mutate(cause_of_death = str_remove(cause_of_death, "___.+"))

# plot 
ar_mena_fig8.2 <- gbd_results_mena_fig8.2 %>%
  ggplot(mapping = aes(x = reorder_within(cause_of_death, lyl, country), y = lyl)) + 
  geom_col(mapping = aes(fill = cause_of_death), width = 0.5, color = "white") +
  scale_x_reordered() +
  facet_wrap(~factor(country, levels = c("Algeria", "Egypt", "Iraq", "Qatar", 
                                         "Saudi Arabia")), scales = "free_x", ncol = 5) +
  scale_fill_manual(values = c("#D3D9E0", "#8F3931", "#7BC1D9",
                               "#808A94")) +
  labs(x = "Threats to Life Expectancy", y = "Life Years Lost", title = "", 
       subtitle = "", fill = "Threats to Life Expectancy") +
  themes_aqli_base +
  theme(axis.text.x = element_blank(), legend.position = "bottom", axis.ticks = element_blank(), 
        strip.text = element_text(size = 14), 
        plot.background = element_rect(fill = "white", color = "white")) 

```

# AR appendix table + appendix graphs

```{r}

# appendix table ============
ar_appendix_table <- gadm0_aqli_2022 %>%
  mutate(across(where(is.numeric), ~round(., digits = 1))) %>%
  select(-c(continent)) %>%
mutate(across(starts_with("llpp_nat"), ~as.character(case_when(
    is.na(.x) ~ "*",
    TRUE ~ as.character(.x)
  )))) %>%
  mutate(across(starts_with("natstandard"), ~as.character(case_when(
    is.na(.x) ~ "*",
    TRUE ~ as.character(.x)
  )))) %>%
  select(country, pm2022, natstandard, llpp_who_2022, llpp_nat_2022) %>%
  mutate(across(starts_with("llpp_who_2022"), ~as.character(case_when(
    is.na(.x) ~ "*",
    TRUE ~ as.character(.x)
  )))) %>%
  mutate(across(starts_with("pm"), ~as.character(case_when(
    is.na(.x) ~ "*",
    TRUE ~ as.character(.x)
  )))) %>%
  rename(Country = country, "PM2.5 concentration 2022 (in µg/m³)" = pm2022, 
         "National Standard (in µg/m³)" = natstandard, 
         "Life Expectancy Gains (in years) from reducing PM2.5 from 2022 Concentrations to the WHO Guideline of 5 µg/m³" = llpp_who_2022, 
         "Life Expectancy Gains (in years) from reducing PM2.5 from 2022 Concentrations to the National Standard" = llpp_nat_2022)


# appendix section graph (Fig A.1) ============
pm_weighted_col_start <- "pm1998_weighted"

pm_weighted_col_end <- "pm2022_weighted"
fig_a1_plt_part1 <- gadm2_aqli_2022 %>%
  filter(!is.na(population)) %>%
  mutate(country = "foo") %>%
  group_by(country) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = !!as.symbol(pm_weighted_col_start):!!as.symbol(pm_weighted_col_end), 
               names_to = "years", values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))),
         region = "National Average") %>%
  select(years, region, pop_weighted_avg_pm2.5) %>%
  mutate(ref_dataset = "2022 dataset")

pm_weighted_col_end <- "pm2021_weighted"
fig_a1_plt_part2 <- color_2021 %>%
  filter(!is.na(population)) %>%
  mutate(country = "foo") %>%
  group_by(country) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = !!as.symbol(pm_weighted_col_start):!!as.symbol(pm_weighted_col_end), 
               names_to = "years", values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))),
         region = "National Average") %>%
  select(years, region, pop_weighted_avg_pm2.5) %>%
  mutate(ref_dataset = "2021 dataset")

pm_weighted_col_end <- "pm2020_weighted"
fig_a1_plt_part3 <- color_2020 %>%
  filter(!is.na(population)) %>%
  mutate(country = "foo") %>%
  group_by(country) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = !!as.symbol(pm_weighted_col_start):!!as.symbol(pm_weighted_col_end), 
               names_to = "years", values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))),
         region = "National Average") %>%
  select(years, region, pop_weighted_avg_pm2.5) %>%
  mutate(ref_dataset = "2020 dataset")

pm_weighted_col_end <- "pm2019_weighted"
fig_a1_plt_part4 <- color_2019 %>%
  filter(!is.na(population)) %>%
  mutate(country = "foo") %>%
  group_by(country) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = !!as.symbol(pm_weighted_col_start):!!as.symbol(pm_weighted_col_end), 
               names_to = "years", values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))),
         region = "National Average") %>%
  select(years, region, pop_weighted_avg_pm2.5) %>%
  mutate(ref_dataset = "2019 dataset")

pm_weighted_col_end <- "pm2016_weighted"
fig_a1_plt_part5 <- color_2016 %>%
  filter(!is.na(population)) %>%
  mutate(country = "foo") %>%
  group_by(country) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = !!as.symbol(pm_weighted_col_start):!!as.symbol(pm_weighted_col_end), 
               names_to = "years", values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))),
         region = "National Average") %>%
  select(years, region, pop_weighted_avg_pm2.5) %>%
  mutate(ref_dataset = "2016 dataset")

final_fig_a1_dataset <- rbind(fig_a1_plt_part1, fig_a1_plt_part2, fig_a1_plt_part3, fig_a1_plt_part4, fig_a1_plt_part5)

plt <- final_fig_a1_dataset %>%
  ggplot(mapping = aes(x = years, y = pop_weighted_avg_pm2.5, color = ref_dataset)) +
  geom_line(lwd = 1.5) +
  scale_y_continuous(breaks = seq(0, 40, 5), limits = c(0, 40)) +
  scale_x_continuous(breaks = c(seq(1998, 2022, 3))) +
  themes_aqli_base +
  scale_color_viridis_d() +
  scale_linetype_manual(values = c("2016 dataset" = "dashed",
                                   "2019 dataset" = "dashed",
                                   "2020 dataset" = "dashed",
                                   "2021 dataset" = "dashed",
                                   "2022 dataset" = "solid")) +
  labs(x = "Year", y = expression("Annual Average " ~ PM[2.5] ~ " Concentration (in µg/m³)"), color = "") +
  theme(legend.key.width = unit(1, "cm"), 
        legend.key.height = unit(1, "cm"), 
        plot.background = element_rect(color = "white", fill = "white")) 

```
