---
title: "Factsheets 2022"
author: "Aarsh"
date: '2022-07-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# get packages, global variables and datasets
```{r load-lib-helper-files-data-global-var}

# read in the helper file
source("./appPublic/aqli.data.explorer.helper.script.R")

```

# This script contains code for graphs and some calculations that were not computed by the
# AQLI Data Explorer dashboard: https://aarsh.shinyapps.io/aqli-epic-data-explorer/.

#========================================================================================================


## India Factsheet 

```{r india_fs_2023}

#> Since [year], [x%] of the world's increase in pollution camer from [country]-----------------

country_select <- "India"

# Since 2013 all gadm2 places where pollution has increased - > average pm2.5 in 2013, 2021
 avg_pm2.5_global <- gadm2_aqli_2021 %>% 
  mutate(diff_pm2021_pm2013 = pm2021 - pm2013) %>%
  filter(diff_pm2021_pm2013 > 0) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         pm2013_pop_weighted = pm2013*pop_weights, 
         pm2021_pop_weighted = pm2021*pop_weights) %>%
  summarise(avg_pm2.5_2013 = sum(pm2013_pop_weighted, na.rm = TRUE), 
            avg_pm2.5_2021 = sum(pm2021_pop_weighted, na.rm = TRUE))

 actual_diff_global <- avg_pm2.5_global$avg_pm2.5_2021 - avg_pm2.5_global$avg_pm2.5_2013
 
# Assuming that of the places (gadm2 regions) where pollution increased, if amongst those places, 
# all Indian gadm2 regions had the same pollution in 2021 as it had in 2013, how would the global
# average PM2.5 look in 2021.
 
avg_pm2.5_global_adjusted <- gadm2_aqli_2021 %>% 
  mutate(diff_pm2021_pm2013 = pm2021 - pm2013) %>%
  filter(diff_pm2021_pm2013 > 0) %>%
   mutate(pm2021 = ifelse(country == country_select, pm2013, pm2021)) %>%
     mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         pm2013_pop_weighted = pm2013*pop_weights, 
         pm2021_pop_weighted = pm2021*pop_weights) %>%
  summarise(avg_pm2.5_2013 = sum(pm2013_pop_weighted, na.rm = TRUE), 
            avg_pm2.5_2021 = sum(pm2021_pop_weighted, na.rm = TRUE))

# difference between adjusted and actual global average, i.e. India's contribution
adjusted_diff_global <- avg_pm2.5_global_adjusted$avg_pm2.5_2021 - avg_pm2.5_global_adjusted$avg_pm2.5_2013
 
# final answer
final_answer <- round(((actual_diff_global - adjusted_diff_global)/actual_diff_global)*100, 1)

#> Indo Gangetic Plain, population and average PM2.5----------------------------------

# average pm2.5 and total population in Indo-Gangetic plains in 2021
summary_indo_gangetic_plain <- gadm2_aqli_2021 %>%
  filter(country == "India", name_1 %in% indo_gangetic_plains_states) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         pm2021_pop_weighted = pm2021*pop_weights) %>%
  summarise(avg_pm2.5_2021 = sum(pm2021_pop_weighted, na.rm = TRUE), 
            total_population = sum(population, na.rm = TRUE))

#> Fig 1: Potential gain in Life Expectancy from permanently reducing PM2.5 from 2021 levels to the-------- 
# WHO PM2.5 guideline.

# separately getting Gilgit Baltistan and Azad Kashmir
azad_kashmir_gilgit_baltistan <- gadm2_aqli_2021 %>%
  filter(country == "Pakistan", name_1 %in% c("Azad Kashmir", "Gilgit Baltistan"))

# plot 3 data
india_fs_fig1_data <- gadm2_aqli_2021 %>%
  filter(country == "India") %>%
  bind_rows(azad_kashmir_gilgit_baltistan) %>%
  left_join(gadm2_aqli_2021_shp, by = c("objectid_gadm2" = "objidgadm2")) %>%
  mutate(lyl_bucket = ifelse((llpp_who_2021 >= 0) & (llpp_who_2021 < 0.1), "0 - < 0.1", NA), 
         lyl_bucket = ifelse((llpp_who_2021 >= 0.1) & (llpp_who_2021 <= 0.5), "0.1 - 0.5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 0.5) & (llpp_who_2021 <= 1), "> 0.5 - 1", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 1) & (llpp_who_2021 <= 2), "> 1 - 2", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 2) & (llpp_who_2021 <= 3), "> 2 - 3", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 3) & (llpp_who_2021 <= 4), "> 3 - 4", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 4) & (llpp_who_2021 <= 5), "> 4 - 5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 5) & (llpp_who_2021 < 6), "> 5 - < 6", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 >= 6), ">= 6", lyl_bucket)) %>%
  mutate(order_lyl_bucket = ifelse(lyl_bucket == "0 - < 0.1", 1, NA), 
         order_lyl_bucket = ifelse(lyl_bucket == "0.1 - 0.5", 2, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 0.5 - 1", 3, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 1 - 2", 4, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 2 - 3", 5, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 3 - 4", 6, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 4 - 5", 7, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 5 - < 6", 8, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == ">= 6", 9, order_lyl_bucket)) %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# change lyl_bucket and order_lyl_bucket columns to factor
# india_fs_fig1_data$lyl_bucket <- factor(india_fs_fig1_data$lyl_bucket)
# india_fs_fig1_data$order_lyl_bucket <- factor(india_fs_fig1_data$order_lyl_bucket)

# india factsheet figure 1
india_fs_fig1 <- india_fs_fig1_data %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), color = "transparent") +
  geom_sf(data = india_state, color = "black", fill = "transparent", lwd = 0.5) +
  ggthemes::theme_map() + 
 scale_fill_manual(values = c("0 - < 0.1 years" = "#FFFFFF", 
                               "0.1 - 0.5" = "#FFE6B3", 
                               "> 0.5 - 1" = "#FFD25D", 
                               "> 1 - 2" = "#FFBA00", 
                               "> 2 - 3" = "#FF9600", 
                               "> 3 - 4" = "#FF6908", 
                               "> 4 - 5" = "#E63D23", 
                               "> 5 - < 6" = "#BD251C", 
                               ">= 6" = "#8C130E")) +
  ggthemes::theme_map() +
  labs(fill = "Life years lost (years)  ", title = expression("Potential Gains in Life Expectancy through Permanently Reducing" ~ PM[2.5] ~ "from 2021 concentrations to the WHO guideline")) + 
 theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15), 
       # legend.key = element_rect(color = "black"),
       legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 7), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
       legend.key = element_rect(color = "black"), 
       legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal") +
  guides(fill = guide_legend(nrow = 1))


svglite("india_fs_fig1")
ggsave("./september.2023/factsheets/india/india_fs_fig1.svg", width = 15, height = 10)

india_fs_fig1_data %>% write_sf("./september.2023/factsheets/india/india_fs_fig1.shp")




# Figure 1.1: state wise figures (uses figure 1's data)-------------------------------------------

# separately getting Gilgit Baltistan and Azad Kashmir
azad_kashmir_gilgit_baltistan <- gadm2_aqli_2021 %>%
  filter(country == "Pakistan", name_1 %in% c("Azad Kashmir", "Gilgit Baltistan"))

# plot 3 data
india_fs_fig1.1_data <- gadm2_aqli_2021 %>%
  filter(country == "India") %>%
  bind_rows(azad_kashmir_gilgit_baltistan) %>%
  left_join(gadm2_aqli_2021_shp, by = c("objectid_gadm2" = "objidgadm2")) %>%
  mutate(lyl_bucket = ifelse((llpp_who_2021 >= 0) & (llpp_who_2021 < 0.1), "0 - < 0.1", NA), 
         lyl_bucket = ifelse((llpp_who_2021 >= 0.1) & (llpp_who_2021 <= 0.5), "0.1 - 0.5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 0.5) & (llpp_who_2021 <= 1), "> 0.5 - 1", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 1) & (llpp_who_2021 <= 2), "> 1 - 2", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 2) & (llpp_who_2021 <= 3), "> 2 - 3", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 3) & (llpp_who_2021 <= 4), "> 3 - 4", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 4) & (llpp_who_2021 <= 5), "> 4 - 5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 5) & (llpp_who_2021 < 6), "> 5 - < 6", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 >= 6), ">= 6", lyl_bucket)) %>%
  mutate(order_lyl_bucket = ifelse(lyl_bucket == "0 - < 0.1", 1, NA), 
         order_lyl_bucket = ifelse(lyl_bucket == "0.1 - 0.5", 2, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 0.5 - 1", 3, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 1 - 2", 4, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 2 - 3", 5, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 3 - 4", 6, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 4 - 5", 7, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 5 - < 6", 8, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == ">= 6", 9, order_lyl_bucket)) %>%
  select(-geometry, geometry) %>%
  st_as_sf()



states_to_plot <- c("Jammu and Kashmir", "Haryana", "Andhra Pradesh", "Assam", "West Bengal", "Maharashtra", 
                "Tamil Nadu", "Azad Kashmir")

# india factsheet figure 1.1 (state wise)
india_fs_fig1.1 <- india_fs_fig1.1_data %>%
  filter(name_1 %in% states_to_plot) %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), color = "transparent") +
  geom_sf(data = india_state, color = "grey", fill = "transparent", lwd = 0.1) +
  geom_sf(data = india_state %>% filter(NAME_1 %in% states_to_plot), color = "black", fill = "transparent", lwd = 0.8) +
    geom_sf(data = india_fs_fig1.1_data %>% filter(name_2 == "Chennai"), color = "black", lwd = 1) +
   ggthemes::theme_map() +
    ggsflabel::geom_sf_label_repel(data = india_state %>% filter(NAME_1 %in% states_to_plot), mapping = aes(label = NAME_1), force = 50, nudge_x = -10, nudge_y = -1.6, seed = 10, size = 3.5) +
   ggsflabel::geom_sf_label_repel(data = india_fs_fig1.1_data %>% filter(name_2 == "Chennai"), mapping = aes(label = name_2), force = 50, nudge_x = 3, seed = 10, size = 2.8) +
  ggthemes::theme_map() + 
 scale_fill_manual(values = c("0 - < 0.1 years" = "#FFFFFF", 
                               "0.1 - 0.5" = "#FFE6B3", 
                               "> 0.5 - 1" = "#FFD25D", 
                               "> 1 - 2" = "#FFBA00", 
                               "> 2 - 3" = "#FF9600", 
                               "> 3 - 4" = "#FF6908", 
                               "> 4 - 5" = "#E63D23", 
                               "> 5 - < 6" = "#BD251C", 
                               ">= 6" = "#8C130E")) +
  labs(fill = "Life years lost  ", title = expression("Potential Gains in Life Expectancy through Permanently Reducing" ~ PM[2.5] ~ "from 2021 concentrations to the WHO guideline"), 
       subtitle = "") + 
 theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15), 
       plot.subtitle = element_text(hjust = 0.5, size = 9, margin = margin(b = 0.5, unit = "cm")),
       # legend.key = element_rect(color = "black"),
       legend.box.margin = margin(b = 1, unit = "cm"),
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
       legend.key = element_rect(color = "black"), 
       legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal") +
  guides(fill = guide_legend(nrow = 1)) 
   
   
#> Fig 1.2: individual state wise maps

state <- "Jammu and Kashmir"
two_states <- c("Jammu and Kashmir", "Azad Kashmir")

india_fs_fig1.2 <- india_fs_fig1.1_data %>%
  filter(name_1 %in% two_states) %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), color = "black", lwd = 0.1) +
      #geom_sf(data = india_fs_fig1.1_data %>% filter(name_2 == "Chennai"), color = "black", lwd = 1, fill = "transparent") +
     #ggsflabel::geom_sf_label_repel(data = india_fs_fig1.1_data %>% filter(name_2 == "Chennai"), mapping = aes(label = name_2), force = 100, nudge_x = -1, nudge_y = 0.5, seed = 10, size = 2.8) +
  #geom_sf(data = india_state, color = "lightgrey", fill = "transparent", lwd = 0.1) +
  #geom_sf(data = india_state %>% filter(NAME_1 %in% state), color = "black", fill = "transparent", lwd = 0.8) +
   ggthemes::theme_map() +
    #ggsflabel::geom_sf_label_repel(data = india_state %>% filter(NAME_1 %in% states_to_plot), mapping = aes(label = NAME_1), force = 50, nudge_x = -10, nudge_y = -1.6, seed = 10, size = 4) +
  ggthemes::theme_map() + 
 scale_fill_manual(values = c("0 - < 0.1 years" = "#FFFFFF", 
                               "0.1 - 0.5" = "#FFE6B3", 
                               "> 0.5 - 1" = "#FFD25D", 
                               "> 1 - 2" = "#FFBA00", 
                               "> 2 - 3" = "#FF9600", 
                               "> 3 - 4" = "#FF6908", 
                               "> 4 - 5" = "#E63D23", 
                               "> 5 - < 6" = "#BD251C", 
                               ">= 6" = "#8C130E")) +
  labs(fill = "Life years lost  ", title = expression("Potential Gains in Life Expectancy through Permanently Reducing" ~ PM[2.5] ~ "from 2021 concentrations to the WHO guideline"), 
       subtitle = str_c("(", state, ")")) + 
 theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15, margin = margin(b = 0.3, unit = "cm")), 
       plot.subtitle = element_text(hjust = 0.5, size = 14, margin = margin(b = 0.8, unit = "cm")),
       # legend.key = element_rect(color = "black"),
       legend.box.margin = margin(b = 1, unit = "cm"),
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
       legend.key = element_rect(color = "black"), 
       legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal") +
  guides(fill = guide_legend(nrow = 1)) 


#> Fig 2: Potential gain in life expectancy in top 10 most populous states in India----------

india_fs_fig2_data <- gadm_level_summary(gadm2_aqli_2021, c("country", "name_1"), c(2021),  10) %>%
  filter(country == "India") %>% 
  slice_max(population, n = 10) %>%
  mutate(lyl_bucket = ifelse((llpp_who_2021 >= 0) & (llpp_who_2021 < 0.1), "0 - < 0.1 years", NA), 
         lyl_bucket = ifelse((llpp_who_2021 >= 0.1) & (llpp_who_2021 <= 0.5), "0.1 - 0.5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 0.5) & (llpp_who_2021 <= 1), "> 0.5 - 1", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 1) & (llpp_who_2021 <= 2), "> 1 - 2", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 2) & (llpp_who_2021 <= 3), "> 2 - 3", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 3) & (llpp_who_2021 <= 4), "> 3 - 4", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 4) & (llpp_who_2021 <= 5), "> 4 - 5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 5) & (llpp_who_2021 < 6), "> 5 - < 6", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 >= 6), ">= 6 years", lyl_bucket)) %>%
  mutate(order_lyl_bucket = ifelse(lyl_bucket == "0 - < 0.1 years", 1, NA), 
         order_lyl_bucket = ifelse(lyl_bucket == "0.1 - 0.5", 2, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 0.5 - 1", 3, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 1 - 2", 4, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 2 - 3", 5, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 3 - 4", 6, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 4 - 5", 7, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 5 - < 6", 8, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == ">= 6 years", 9, order_lyl_bucket))

india_fs_fig2_data$lyl_bucket <- as.factor(india_fs_fig2_data$lyl_bucket)

india_fs_fig2_plt <- india_fs_fig2_data %>%
  ggplot() +
   geom_col(mapping = aes(x = forcats::fct_reorder(name_1, llpp_who_2021), y = llpp_who_2021, fill = lyl_bucket), width = 0.5) +
  labs(x = "State", y = "Average Life Expectancy Gains (Years)",
       title = "State wise Average Life Expectancy Gains",
       subtitle = expression("(Reducing" ~ PM[2.5] ~ "pollution from 2021 levels to the WHO guideline in top 10 most populated states of India)"), 
       caption = "* Top 10 most populated states are ordered from most populated (Uttar Pradesh) to least populated (Tamil Nadu).") +
  scale_y_continuous(breaks = seq(0, 9, 1), limits = c(0, 9)) +
    scale_fill_manual(values = c("0 - < 0.1 years" = "#FFFFFF", 
                               "0.1 - 0.5" = "#FFE6B3", 
                               "> 0.5 - 1" = "#FFD25D", 
                               "> 1 - 2" = "#FFBA00", 
                               "> 2 - 3" = "#FF9600", 
                               "> 3 - 4" = "#FF6908", 
                               "> 4 - 5" = "#E63D23", 
                               "> 5 - < 6" = "#BD251C", 
                               ">= 6 years" = "#8C130E")) +
  coord_flip() +
  ggthemes::theme_tufte() +
  theme(legend.position = "none", 
        plot.title = element_text(hjust = 0.5, size = 16), 
        plot.subtitle = element_text(hjust =  0.5, size = 10, face = "italic", margin = margin(b = 0.8, unit = "cm")), 
        plot.caption = element_text(size = 8, hjust = 0, face = "italic"),
        axis.line = element_line(), 
        axis.text = element_text(size = 11), 
        axis.title = element_text(size = 13), 
        axis.title.y = element_text(margin = margin(r = 0.7, unit = "cm")), 
        axis.title.x = element_text(margin = margin(t = 0.6, b = 0.6, unit = "cm")), 
        axis.ticks = element_blank()) 


svglite("india_fs_fig2")
ggsave("./september.2023/factsheets/india/india_fs_fig2.svg", width = 12, height = 9)

india_fs_fig2_data %>%
  write_csv("./september.2023/factsheets/india/fig2/india_fs_fig2_data.csv")


#> GBD India graph--------------------------------------------

# top 5 most deadly diseases
india_fs_fig3_dataset <- gbd_results_master_2021 %>%
  filter(country == "India")

colnames(india_fs_fig3_dataset)[3] <- c("llpp_who_2021")

india_fs_fig3_dataset <- india_fs_fig3_dataset %>%
    mutate(lyl_bucket = ifelse((llpp_who_2021 >= 0) & (llpp_who_2021 < 0.1), "0 - < 0.1 years", NA), 
         lyl_bucket = ifelse((llpp_who_2021 >= 0.1) & (llpp_who_2021 <= 0.5), "0.1 - 0.5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 0.5) & (llpp_who_2021 <= 1), "> 0.5 - 1", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 1) & (llpp_who_2021 <= 2), "> 1 - 2", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 2) & (llpp_who_2021 <= 3), "> 2 - 3", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 3) & (llpp_who_2021 <= 4), "> 3 - 4", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 4) & (llpp_who_2021 <= 5), "> 4 - 5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 5) & (llpp_who_2021 < 6), "> 5 - < 6 years", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 >= 6), ">= 6 years", lyl_bucket)) %>%
  mutate(order_lyl_bucket = ifelse(lyl_bucket == "0 - < 0.1 years", 1, NA), 
         order_lyl_bucket = ifelse(lyl_bucket == "0.1 - 0.5", 2, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 0.5 - 1", 3, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 1 - 2", 4, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 2 - 3", 5, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 3 - 4", 6, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 4 - 5", 7, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 5 - 6 years", 8, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == ">= 6 years", 9, order_lyl_bucket))


# getting disease (ordered from most deadly to least deadly) in a vector (to be used later in the
# scale_x_discrete function).

# cause_of_death_ordered <- india_fs_fig3_dataset %>%
#   arrange(llpp_who_2021) %>%
#   pull(cause_of_death) %>%
#   unlist()





#> figure 3 plot

# figure 3 caption removed: Source: Global Burden of Disease (https://vizhub.healthdata.org/gbd-results/) causes and risks data and WHO Life Tables (https://apps.who.int/gho/data/node.main.LIFECOUNTRY?lang=en) were used combined with the Life table method to arrive at these results. 'PM2.5 relative to WHO Guideline' bar displays life years lost relative to the WHO guideline as calculated by latest AQLI (2021) data, which will be published in September 2023.

india_fs_fig3 <- india_fs_fig3_dataset %>%
  ggplot() + 
  geom_col(mapping = aes(x = forcats::fct_reorder(cause_of_death, llpp_who_2021), y = llpp_who_2021, fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), width = 0.5, color = "black") +
  labs(x = "Cause of Death", y = "Life Years Lost", fill = "Life years lost", 
       title = expression("Life Expectancy Impact of" ~ PM[2.5] ~ "and Unassociated Causes/Risks of Deaths in India")) +
  coord_flip() + 
  ggthemes::theme_tufte() +
  theme(legend.position = "bottom",
        axis.text = element_text(size = 14),
        axis.title.y = element_text(size = 16, margin = margin(r = 0.6, unit = "cm")),
        axis.title.x = element_text(size = 16, margin = margin(t = 0.6, b = 0.6, unit = "cm")),
        plot.caption = element_text(hjust = 0, size = 8, margin = margin(t = 0.8, unit = "cm")),
        plot.title = element_text(hjust = 0.5, size = 20, margin = margin(b = 0.8, unit = "cm")),
        plot.subtitle = element_text(hjust = 0.5, size = 10, margin = margin(b = 0.8, unit = "cm")),
        legend.box.background = element_rect(color = "black"),
        plot.background = element_rect(color = "white"),
        axis.line = element_line(), 
        legend.text = element_text(size = 11), 
        legend.title = element_text(size = 14),
        panel.grid.major.y = element_blank()) +
  scale_y_continuous(breaks = seq(0, 6, 0.5)) +
 # scale_x_discrete(limits = cause_of_death_ordered[seq(1, length(cause_of_death_ordered), by = 2)]) +
  scale_fill_manual(values = c("0 - < 0.1 years" = "#FFFFFF", 
                               "0.1 - 0.5" = "#FFE6B3", 
                               "> 0.5 - 1" = "#FFD25D", 
                               "> 1 - 2" = "#FFBA00", 
                               "> 2 - 3" = "#FF9600", 
                               "> 3 - 4" = "#FF6908", 
                               "> 4 - 5" = "#E63D23", 
                               "> 5 - < 6 years" = "#BD251C", 
                               ">= 6 years" = "#8C130E")) + 
  guides(fill = guide_legend(nrow = 1))

svglite("india_fs_fig3")
ggsave("./september.2023/factsheets/india/fig3/india_fs_fig3.svg", width = 15, height = 12)

india_fs_fig3_dataset %>%
   write_csv("./september.2023/factsheets/india/fig3/india_fs_fig3_data.csv")


#> Figure 4: Average PM2.5 concentration in India from 1998 to 2021------------------------

# adding a north India/rest of india region column (specifically Indo gangetic plain)
north_india <- c("West Bengal", "Uttar Pradesh", "Punjab", "Haryana", 
                 "Chandigarh", "Bihar", "NCT of Delhi")

india_fs_fig4_data_part1 <- gadm2_aqli_2021 %>%
  filter(country == "India") %>%
  mutate(region = ifelse(name_1 %in% north_india, "North India", "All other regions (excluding North India)"))


# creating India's region wise average PM2.5 data from 1998 to 2021 
india_fs_fig4_data_part1 <- india_fs_fig4_data_part1 %>%
  group_by(region) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2021_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+")))) %>%
  select(years, region, pop_weighted_avg_pm2.5)

# creating a national average PM2.5 trendlines data from 1998 to 2021
india_fs_fig4_data_part2 <- gadm2_aqli_2021 %>%
  filter(country == "India") %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2021_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))), 
         region = "National Average") %>% 
  select(years, region, pop_weighted_avg_pm2.5)

# India factsheet figure 4 dataset
india_fs_fig4_data <- rbind(india_fs_fig4_data_part1, india_fs_fig4_data_part2)

india_fs_fig4_data %>%
   write_csv("./september.2023/factsheets/india/fig4/india_fs_fig4_data.csv")

# India factsheet figure 4
# fig4 caption removed: "* We define the Indo-Gangetic plain region as containing the following seven states and union territories: Bihar, Chandigarh, NCT of Delhi, Haryana, Punjab, Uttar Pradesh, and West Bengal."

india_fs_fig4 <- ggplot(india_fs_fig4_data) +
  geom_line(mapping = ggplot2::aes(x = years, y = pop_weighted_avg_pm2.5, color = region), lwd = 1.3) +
    geom_hline(mapping = aes(yintercept = 5), lwd = 0.8, linetype = "dotted") +
  scale_y_continuous(breaks = seq(0, 100, 10), limits = c(0, 100)) +
  scale_x_continuous(breaks = c(seq(1998, 2019, 3), 2021)) +
    scale_color_manual(values = c("National Average" = "darkgrey", "North India" = "darkred", "All other regions (excluding North India)" = "orange")) +
  ggthemes::theme_tufte() +
  labs(x = "Year", 
       y = expression("Annual Average   " ~ PM[2.5] ~ "(in µg/m³)"), 
       title = expression("Annual Average" ~ PM[2.5] ~ "concentrations in India, 1998 to 2021")) +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 11),
        legend.title = element_blank(),
        axis.title.y = element_text(size = 13, margin = margin(r = 0.6, unit = "cm")), 
        axis.title.x = element_text(size = 13, margin = margin(t = 0.6, b = 0.6, unit = "cm")), 
        axis.line = element_line(), 
        legend.box.background = element_rect(color = "black"),
        plot.title = element_text(hjust = 0.5, size = 16, margin = margin(b = 0.7, unit = "cm")), 
        plot.subtitle = element_text(hjust = 0.5, size = 8, face = "italic"), 
        plot.caption = element_text(size = 7, margin = margin(t = 0.8, unit = "cm"), hjust = 0, face = "italic"),
        axis.text = element_text(size = 12), 
        plot.background = element_rect(color = "white"), 
        axis.ticks = element_blank()) +
     geom_text(x = 2000.5, y = 7.9, label = expression("WHO" ~ PM[2.5] ~ "Guideline (last updated: 2021): 5 µg/m³"), size = 4.5)


svglite("india_fs_fig4")
ggsave("./september.2023/factsheets/india/india_fs_fig4.svg", width = 12, height = 9)


# Appendix table

appendix_table_raw_india <- gadm_level_summary(gadm2_aqli_2021, c("country", "name_1"), c(2021), 10) %>%
filter(country == "India") %>%
   mutate(population_lakhs = round(population/100000, 1)) %>%
  select(name_1, population_lakhs, pm2021, llpp_who_2021, llpp_nat_2021) %>%
  rename("State/UT" = name_1, 
         "Population (Lakhs)" = population_lakhs, 
         "Annual Average 2021 PM2.5 Concentration (µg/m³)" = pm2021, 
         "Life Expectancy Gains from reducing PM2.5 from 2021 concentration to WHO PM2.5 guideline of 5 µg/m³" = llpp_who_2021, 
         "Life Expectancy Gains from reducing PM2.5 from 2021 concentration to National PM2.5 guideline of 40 µg/m³" = llpp_nat_2021)

# Experimental figure



```


# South Korea factsheet

```{r}

#> quick stats

# South Korea ranking amongst other countries in terms of pollution
gadm_level_summary(gadm2_aqli_2021, c("country"), c(2021), 10) %>%
  slice_max(pm2021, n = 50) %>%
  View()

# most populated region
gadm_level_summary(gadm2_aqli_2021, c("country", "name_1"), c(2021), 10) %>%
  filter(country == "South Korea") %>%
  slice_max(population, n = 10)

#> plot 1: map screenshot for South Korea

# south korea figure1 dataset
south_korea_fs_fig1_data <- gadm2_aqli_2021 %>%
  filter(country == "South Korea") %>%
  left_join(gadm2_aqli_2021_shp, by = c("objectid_gadm2" = "objidgadm2")) %>%
  mutate(lyl_bucket = ifelse((llpp_who_2021 >= 0) & (llpp_who_2021 < 0.1), "0 - < 0.1", NA), 
         lyl_bucket = ifelse((llpp_who_2021 >= 0.1) & (llpp_who_2021 <= 0.5), "0.1 - 0.5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 0.5) & (llpp_who_2021 <= 1), "> 0.5 - 1", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 1) & (llpp_who_2021 <= 2), "> 1 - 2", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 2) & (llpp_who_2021 <= 3), "> 2 - 3", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 3) & (llpp_who_2021 <= 4), "> 3 - 4", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 4) & (llpp_who_2021 <= 5), "> 4 - 5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 5) & (llpp_who_2021 < 6), "> 5 - < 6", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 >= 6), ">= 6", lyl_bucket)) %>%
  mutate(order_lyl_bucket = ifelse(lyl_bucket == "0 - < 0.1", 1, NA), 
         order_lyl_bucket = ifelse(lyl_bucket == "0.1 - 0.5", 2, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 0.5 - 1", 3, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 1 - 2", 4, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 2 - 3", 5, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 3 - 4", 6, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 4 - 5", 7, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 5 - < 6", 8, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == ">= 6", 9, order_lyl_bucket)) %>%
  select(-geometry, geometry) %>%
  st_as_sf()

south_korea_fs_fig1_data %>%
  sf::write_sf("./september.2023/factsheets/southkorea/fig1/sk_fs_fig1.shp")


# south korea figure 1
south_korea_fs_fig1 <- south_korea_fs_fig1_data %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), color = "transparent") +
  geom_sf(data = gadm1_aqli_2021_shp %>% filter(name0 == "South Korea"), color = "black", fill = "transparent", lwd = 0.5) +
  ggthemes::theme_map() + 
 scale_fill_manual(values = c("0 - < 0.1 years" = "#FFFFFF", 
                               "0.1 - 0.5" = "#FFE6B3", 
                               "> 0.5 - 1" = "#FFD25D", 
                               "> 1 - 2" = "#FFBA00", 
                               "> 2 - 3" = "#FF9600", 
                               "> 3 - 4" = "#FF6908", 
                               "> 4 - 5" = "#E63D23", 
                               "> 5 - < 6" = "#BD251C", 
                               ">= 6" = "#8C130E")) +
  ggthemes::theme_map() +
  labs(fill = "Life years lost  ", title = expression("Potential Gains in Life Expectancy through Permanently Reducing" ~ PM[2.5] ~ "from 2021 concentrations to the WHO guideline")) + 
 theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15), 
       # legend.key = element_rect(color = "black"),
       legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 7), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
       legend.key = element_rect(color = "black"), 
       legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal") +
  guides(fill = guide_legend(nrow = 1))

ggsave("./september.2023/factsheets/southkorea/sk_fs_fig1.svg", width = 15, height = 10)

#> plot 2: Gain in LE in reducing 2021 pollution to WHO guideline in top 10 most populous regions

# fig2 dataset
southkorea_fs_fig2_dataset <- gadm2_aqli_2021 %>%
  filter(country == "South Korea") %>%
  add_aqli_color_scale_buckets(scale_type = "lyl", col_name = "llpp_who_2021") %>%
  slice_max(population, n = 10)

southkorea_fs_fig2_dataset %>%
   write_csv("./september.2023/factsheets/southkorea/fig2/sk_fs_fig2_data.csv")


# fig 2

south_korea_fs_fig2 <- southkorea_fs_fig2_dataset %>%
  aqli_bar(scale_type = "lyl", x_var = "name_2", y_var = "llpp_who_2021", title = expression("Potential Gain in Life Expectancy from Reducing 2021 " ~ PM[2.5] ~ "concentrations to the WHO Guideline"), subtitle = "(Top 10 most populous regions of South Korea)", x_label = "Region", y_label = "Average Life Expectancy Gains (years)", legend_title = "LE gains (years)", caption = "")
 
# plot 3: Trendlines: 1998 to 2021

# southkorea factsheet figure 3 dataset
southkorea_fs_fig3_dataset <- gadm2_aqli_2021 %>%
  filter(country == "South Korea") %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2021_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))), 
         region = "National Average") %>% 
  select(years, region, pop_weighted_avg_pm2.5)


southkorea_fs_fig3_dataset %>%
   write_csv("./september.2023/factsheets/southkorea/fig3/sk_fs_fig3_data.csv")


  southkorea_fs_fig3 <- southkorea_fs_fig3_dataset %>%
    ggplot() +
  geom_line(mapping = ggplot2::aes(x = years, y = pop_weighted_avg_pm2.5), lwd = 1.1, 
            color = "darkred") +
    geom_hline(mapping = aes(yintercept = 5), lwd = 0.8, linetype = "dashed") +
    geom_hline(mapping = aes(yintercept = 15), lwd = 0.8, linetype = "dashed") + 
  scale_y_continuous(breaks = seq(0, 35, 5), limits = c(0, 35)) +
  scale_x_continuous(breaks = c(seq(1998, 2020, 2), 2021)) +
    scale_color_manual(values = c("National Average" = "darkgrey")) +
  ggthemes::theme_clean() +
  labs(x = "Years", 
       y = expression("Annual average " ~ PM[2.5] ~ "concentrations (in µg/m³)")) +
  theme(legend.position = "bottom", legend.title = element_blank(), 
        legend.text = element_text(size = 7), 
        axis.title.y = element_text(size = 9), 
        axis.title.x = element_text(size = 9)) +  
    geom_text(x = 2001.8, y = 6.1, label =  expression("WHO " ~ PM[2.5] ~ "Guideline (last updated in 2021): 5 µg/m³"), size = 5) +
    geom_text(x = 2001.8, y = 16.1, label = expression("South Korea National" ~ PM[2.5] ~ "Guideline: 15 µg/m³"), size = 5) +
    themes_aqli_base
  
  
  ggsave("./september.2023/factsheets/southkorea/fig3/sk_fs_fig3.svg", width = 15, height = 10)



  # appendix table (gadm level 2)
  gadm2_aqli_2021 %>%
    filter(country == "South Korea") %>%
    select(name_2, population, pm2021, llpp_who_2021, llpp_nat_2021) %>%
    mutate(pop_millions = round(population/1000000, 1), 
           pm2021 = round(pm2021, 1), 
           llpp_who_2021 = round(llpp_who_2021, 1), 
           llpp_nat_2021 = round(llpp_nat_2021, 1)) %>%
    slice_max(population, n = 25) %>% 
    select(name_2, pop_millions, pm2021, llpp_who_2021, llpp_nat_2021) %>%
    rename(`Population (Millions)` = pop_millions, 
           "Region" = name_2, 
           "PM 2.5 concentration 2021 (in µg/m³)" = pm2021, 
           "From 2021 Concentration to the National Guideline of 15 µg/m³" = llpp_nat_2021, 
           "From 2021 Concentration to the WHO Guideline of 5 µg/m³" = llpp_who_2021) %>%
    write_csv("./[updatedOnJune012023]South Korea Factsheet 2023 appendix table.csv")
    

```

# China factsheet

```{r}

# sanity checks

# total life years lost for regions out of compliance with China's national standard
tmp_data <- gadm_level_summary(gadm2_aqli_2021, c("country", "name_1", "name_2"), c(2021), 10) %>%
  filter(country == "China") %>%
  filter(pm2021 > 35) 

tmp_data %>%
  gadm_level_summary(c("country"), c(2021), 10) %>%
  View()

#> plot 1: map screenshot--------------------

# south korea figure1 dataset
china_fs_fig1_data <- gadm2_aqli_2021 %>%
  filter(country == "China") %>%
  left_join(gadm2_aqli_2021_shp, by = c("objectid_gadm2" = "objidgadm2")) %>%
  mutate(lyl_bucket = ifelse((llpp_who_2021 >= 0) & (llpp_who_2021 < 0.1), "0 - < 0.1", NA), 
         lyl_bucket = ifelse((llpp_who_2021 >= 0.1) & (llpp_who_2021 <= 0.5), "0.1 - 0.5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 0.5) & (llpp_who_2021 <= 1), "> 0.5 - 1", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 1) & (llpp_who_2021 <= 2), "> 1 - 2", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 2) & (llpp_who_2021 <= 3), "> 2 - 3", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 3) & (llpp_who_2021 <= 4), "> 3 - 4", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 4) & (llpp_who_2021 <= 5), "> 4 - 5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 5) & (llpp_who_2021 < 6), "> 5 - < 6", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 >= 6), ">= 6", lyl_bucket)) %>%
  mutate(order_lyl_bucket = ifelse(lyl_bucket == "0 - < 0.1", 1, NA), 
         order_lyl_bucket = ifelse(lyl_bucket == "0.1 - 0.5", 2, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 0.5 - 1", 3, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 1 - 2", 4, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 2 - 3", 5, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 3 - 4", 6, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 4 - 5", 7, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 5 - < 6", 8, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == ">= 6", 9, order_lyl_bucket)) %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# china_fs_fig1_data %>%
#   sf::write_sf("./september.2023/factsheets/southkorea/fig1/sk_fs_fig1.shp")


# south korea figure 1
china_fs_fig1 <- china_fs_fig1_data %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), color = "transparent") +
 geom_sf(data = gadm1_aqli_2021_shp %>% filter(name0 == "China"), color = "black", fill = "transparent", lwd = 0.5) +
  ggthemes::theme_map() + 
 scale_fill_manual(values = c("0 - < 0.1" = "#FFFFFF", 
                               "0.1 - 0.5" = "#FFE6B3", 
                               "> 0.5 - 1" = "#FFD25D", 
                               "> 1 - 2" = "#FFBA00", 
                               "> 2 - 3" = "#FF9600", 
                               "> 3 - 4" = "#FF6908", 
                               "> 4 - 5" = "#E63D23", 
                               "> 5 - < 6" = "#BD251C", 
                               ">= 6" = "#8C130E")) +
  ggthemes::theme_map() +
  labs(fill = "Life years lost  ", title = expression("Potential Gains in Life Expectancy through Permanently Reducing" ~ PM[2.5] ~ "from 2021 concentrations to the WHO guideline")) + 
 theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15), 
       # legend.key = element_rect(color = "black"),
       legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 7), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
       legend.key = element_rect(color = "black"), 
       legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal") +
  guides(fill = guide_legend(nrow = 1))






#> plot 2: Potential Gain in Life Expectancy from Reducing PM2.5 from 2021 to the WHO Guideline in 10 most populous regions of China -----------------------------------------

china_fs_fig2_dataset <- gadm2_aqli_2021 %>%
  filter(country == "China") %>%
  add_aqli_color_scale_buckets(scale_type = "lyl", col_name = "llpp_who_2021") %>%
  slice_max(population, n = 10)

china_fs_fig2 <- china_fs_fig2_dataset %>%
  aqli_bar(scale_type = "lyl", x_var = "name_2", y_var = "llpp_who_2021", title = expression("Potential Gain in Life Expectancy from Reducing 2021 " ~ PM[2.5] ~ "concentrations to the WHO Guideline"), subtitle = "(Top 10 most populous prefectures of China)", x_label = "Prefecture", y_label = "Average Life Expectancy Gains (years)", legend_title = "LE gains (years)", caption = "")


#> plot 3: PM2.5 Concentrations in Major Regions in Mainland China Over Time (1998 to 2021)-----------------

# filtering the color file for China
color_2021_china <- gadm2_aqli_2021 %>%
  filter(country == "China")

# BTH region (name_1)
bth_region <- c("Beijing", "Tianjin", "Hebei")

# YRD (name_1)
yrd_region <- c("Shanghai", "Jiangsu", "Zhejiang")

# PRD (name_1, name_2)

prd_region_name_2_guandong_regions <- c("Dongguan", "Foshan", "Guangzhou", 
                                        "Huizhou", "Jiangmen", "Shenzhen", 
                                        "Zhaoqing", "Zhongshan", "Zhuhai")

prd_region_name_1 <- c("Hong Kong", "Macau")

prd <- c(prd_region_name_2_guandong_regions, prd_region_name_1)


# add region column
color_2021_china  <- color_2021_china %>%
  mutate(region = ifelse(name_1 %in% bth_region, "BTH", "others"), 
         region = ifelse(name_1 %in% yrd_region,  "YRD", region), 
         region = ifelse(name_1 %in% prd_region_name_1, "PRD", region), 
         region = ifelse(name_2 %in% prd_region_name_2_guandong_regions, "PRD", region)) 


# China factsheet figure 3 (part-1): trend lines figure region wise (BTH, YRD, PRD) dataset
trendlines_china_region_wise_df <- color_2021_china %>%
  group_by(region) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2021_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+")))) %>%
  select(years, region, pop_weighted_avg_pm2.5) %>%
  filter(region %in% c("YRD", "BTH", "PRD"))

# China factsheet figure 3 (part-2): trend line national average dataset
trendline_national_avg_df <- color_2021_china %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2021_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))), 
         region = "China") %>% 
  select(years, region, pop_weighted_avg_pm2.5)

# China factsheet figure 3 dataset final
china_fs_fig3_dataset <- rbind(trendlines_china_region_wise_df, trendline_national_avg_df)

china_fs_fig3_dataset <-  china_fs_fig3_dataset %>%
    mutate(region_order = ifelse(region == "China", 1, NA), 
         region_order = ifelse(region == "PRD", 2, region_order), 
         region_order = ifelse(region == "YRD", 3, region_order), 
         region_order = ifelse(region == "BTH", 4, NA))

# save China factsheet figure 3 dataset
# china_fs_fig3_dataset %>%
#   write_csv("./june.2022/factsheets/china/graph.wise.datasets/china_fs_fig3.csv")

# plot china factsheet figure 3
china_fs_fig3 <- china_fs_fig3_dataset %>%
  ggplot() +
  geom_line(mapping = ggplot2::aes(x = years, y = pop_weighted_avg_pm2.5, color = forcats::fct_reorder(region, region_order)), lwd = 1.1) +
    geom_hline(mapping = aes(yintercept = 5), lwd = 0.5, linetype = "dashed") +
    geom_vline(mapping = aes(xintercept = 2014), lwd = 0.5, linetype = "dashed") +
  scale_y_continuous(breaks = seq(0, 100, 10), limits = c(0, 100)) +
  scale_x_continuous(breaks = c(seq(1998, 2020, 2), 2021)) +
    scale_color_manual(values = c("PRD" = "burlywood1", "China" = "darkgrey", "BTH" = "darkred", "YRD" = "darkorange")) +
  ggthemes::theme_clean() +
  labs(x = "Year", 
       y = expression("Annual average " ~ PM[2.5] ~ "concentrations (in µg/m³)"), 
       title = expression("Annual average" ~ PM[2.5] ~ "Concentrations in Major Regions in Mainland China Over Time"), 
    subtitle = "(1998 to 2021)", 
    color = "Region") +
  theme(legend.position = "bottom", legend.title = element_blank(), 
        legend.text = element_text(size = 6.5), 
        axis.title.y = element_text(size = 9), 
        axis.title.x = element_text(size = 9)) + 
    geom_text(x = 2001, y = 10, label = expression(paste("WHO PM2.5 Guideline (last updated: 2021): 5 ", mu, "g","/", m^3, ""))) + 
    geom_text(x = 2015.3, y = 93, label = str_wrap("China announces war on pollution", width = 18)) +
  themes_aqli_base
  





#> plot 4: GBD----------------------------------------- 

# china GBD
china_fs_fig4_dataset <- gbd_results_master_2021 %>%
  filter(country == "China")

colnames(china_fs_fig4_dataset)[3] <- c("llpp_who_2021")

china_fs_fig4_dataset <- china_fs_fig4_dataset %>%
    mutate(lyl_bucket = ifelse((llpp_who_2021 >= 0) & (llpp_who_2021 < 0.1), "0 - < 0.1 years", NA), 
         lyl_bucket = ifelse((llpp_who_2021 >= 0.1) & (llpp_who_2021 <= 0.5), "0.1 - 0.5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 0.5) & (llpp_who_2021 <= 1), "> 0.5 - 1", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 1) & (llpp_who_2021 <= 2), "> 1 - 2", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 2) & (llpp_who_2021 <= 3), "> 2 - 3", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 3) & (llpp_who_2021 <= 4), "> 3 - 4", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 4) & (llpp_who_2021 <= 5), "> 4 - 5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 5) & (llpp_who_2021 < 6), "> 5 - < 6 years", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 >= 6), ">= 6 years", lyl_bucket)) %>%
  mutate(order_lyl_bucket = ifelse(lyl_bucket == "0 - < 0.1 years", 1, NA), 
         order_lyl_bucket = ifelse(lyl_bucket == "0.1 - 0.5", 2, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 0.5 - 1", 3, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 1 - 2", 4, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 2 - 3", 5, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 3 - 4", 6, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 4 - 5", 7, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 5 - 6 years", 8, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == ">= 6 years", 9, order_lyl_bucket))


#> figure 4 plot

# figure 4 caption removed: Source: Global Burden of Disease (https://vizhub.healthdata.org/gbd-results/) causes and risks data and WHO Life Tables (https://apps.who.int/gho/data/node.main.LIFECOUNTRY?lang=en) were used combined with the Life table method to arrive at these results. 'PM2.5 relative to WHO Guideline' bar displays life years lost relative to the WHO guideline as calculated by latest AQLI (2021) data, which will be published in September 2023.

china_fs_fig4 <- china_fs_fig4_dataset %>%
  ggplot() + 
  geom_col(mapping = aes(x = forcats::fct_reorder(cause_of_death, llpp_who_2021), y = llpp_who_2021, fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), width = 0.5, color = "black") +
  labs(x = "Cause of Death", y = "Life Years Lost", fill = "Life years lost", 
       title = expression("Life Expectancy Impact of" ~ PM[2.5] ~ "and Unassociated Causes/Risks of Deaths in China")) +
  coord_flip() + 
  ggthemes::theme_tufte() +
  theme(legend.position = "bottom",
        axis.text = element_text(size = 14),
        axis.title.y = element_text(size = 16, margin = margin(r = 0.6, unit = "cm")),
        axis.title.x = element_text(size = 16, margin = margin(t = 0.6, b = 0.6, unit = "cm")),
        plot.caption = element_text(hjust = 0, size = 8, margin = margin(t = 0.8, unit = "cm")),
        plot.title = element_text(hjust = 0.5, size = 20, margin = margin(b = 0.8, unit = "cm")),
        plot.subtitle = element_text(hjust = 0.5, size = 10, margin = margin(b = 0.8, unit = "cm")),
        legend.box.background = element_rect(color = "black"),
        plot.background = element_rect(color = "white"),
        axis.line = element_line(), 
        legend.text = element_text(size = 11), 
        legend.title = element_text(size = 14),
        panel.grid.major.y = element_blank()) +
  scale_y_continuous(breaks = seq(0, 7, 0.5)) +
 # scale_x_discrete(limits = cause_of_death_ordered[seq(1, length(cause_of_death_ordered), by = 2)]) +
  scale_fill_manual(values = c("0 - < 0.1 years" = "#FFFFFF", 
                               "0.1 - 0.5" = "#FFE6B3", 
                               "> 0.5 - 1" = "#FFD25D", 
                               "> 1 - 2" = "#FFBA00", 
                               "> 2 - 3" = "#FF9600", 
                               "> 3 - 4" = "#FF6908", 
                               "> 4 - 5" = "#E63D23", 
                               "> 5 - < 6 years" = "#BD251C", 
                               ">= 6 years" = "#8C130E")) + 
  guides(fill = guide_legend(nrow = 1))



#> appendix table-------------------------------

china_fs_appendix_table <- gadm2_aqli_2021 %>%
gadm_level_summary(c("country", "name_1", "name_2"), c(2014, 2021), 10) %>%
  filter(country == "China") %>%
  slice_max(population, n = 25) %>%
  mutate(pop_millions = round(population/1000000, 1), 
         le_gain_2014_to_2021 = round((pm2014 - pm2021)*0.098, 1)) %>%
  select(name_2, pop_millions, pm2021, le_gain_2014_to_2021,
         llpp_who_2021, llpp_nat_2021) %>%
  rename(Prefecture = name_2, `Population (Millions)` = pop_millions, 
         `PM 2.5 concentration 2021 (µg/m³)` = pm2021, 
         `Life Expectancy Gains From reducing PM2.5 from 2014 concentrations to 2021 concentrations` = le_gain_2014_to_2021,
         `Life Expectancy gain from reducing PM2.5 concentrations from 2021 Concentration to WHO Guideline of 5 µg/m³` = llpp_who_2021, 
         `Life Expectancy gains from reducing PM2.5 concentrations from 2021 Concentration to the National Standard of 35 µg/m³` = llpp_nat_2021)

china_fs_appendix_table %>% 
  write_csv("[June022023]china_fs_appendix_table.csv")


```


# North India Fact Sheet 2023

```{r}

# Filtering color dataset for India
color_2021_india <- gadm2_aqli_2021 %>%
  filter(country == "India") 

# adding a north India/rest of india region column (specifically Indo gangetic plain)
north_india <- c("West Bengal", "Uttar Pradesh", "Punjab", "Haryana", 
                 "Chandigarh", "Bihar", "NCT of Delhi")

# adding North India column
color_2021_india <- color_2021_india %>%
  mutate(region = ifelse(name_1 %in% north_india, "North India", "All other regions (excluding North India)"))

# quick stats
color_2021_india %>%
  filter(region == "North India") %>%
  gadm_level_summary(c("country"), c(2021), 10)


foo <- color_2021_india %>%
  filter(region == "North India") %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         pm2021_pop_weighted = pop_weights*pm2021) %>%
  summarise(avg_pm2.5_2021 = sum(pm2021_pop_weighted, na.rm = TRUE), 
            tot_pop = sum(population, na.rm = TRUE))



```


# sanity checks

```{r}

# Nepal

nepal_fs_fig1_data <- gadm2_aqli_2021 %>%
  filter(country == "Nepal") %>%
  left_join(gadm2_aqli_2021_shp, by = c("objectid_gadm2" = "objidgadm2")) %>%
  mutate(lyl_bucket = ifelse((llpp_who_2021 >= 0) & (llpp_who_2021 < 0.1), "0 - < 0.1", NA), 
         lyl_bucket = ifelse((llpp_who_2021 >= 0.1) & (llpp_who_2021 <= 0.5), "0.1 - 0.5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 0.5) & (llpp_who_2021 <= 1), "> 0.5 - 1", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 1) & (llpp_who_2021 <= 2), "> 1 - 2", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 2) & (llpp_who_2021 <= 3), "> 2 - 3", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 3) & (llpp_who_2021 <= 4), "> 3 - 4", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 4) & (llpp_who_2021 <= 5), "> 4 - 5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 5) & (llpp_who_2021 < 6), "> 5 - < 6", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 >= 6), ">= 6", lyl_bucket)) %>%
  mutate(order_lyl_bucket = ifelse(lyl_bucket == "0 - < 0.1", 1, NA), 
         order_lyl_bucket = ifelse(lyl_bucket == "0.1 - 0.5", 2, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 0.5 - 1", 3, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 1 - 2", 4, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 2 - 3", 5, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 3 - 4", 6, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 4 - 5", 7, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 5 - < 6", 8, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == ">= 6", 9, order_lyl_bucket)) %>%
  select(-geometry, geometry) %>%
  st_as_sf()

south_korea_fs_fig1_data %>%
  sf::write_sf("./september.2023/factsheets/southkorea/fig1/sk_fs_fig1.shp")


# south korea figure 1
nepal_fs_fig1 <- nepal_fs_fig1_data %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), color = "transparent") +
  geom_sf(data = gadm1_aqli_2021_shp %>% filter(name0 == "Nepal"), color = "black", fill = "transparent", lwd = 0.5) +
  ggthemes::theme_map() + 
 scale_fill_manual(values = c("0 - < 0.1 years" = "#FFFFFF", 
                               "0.1 - 0.5" = "#FFE6B3", 
                               "> 0.5 - 1" = "#FFD25D", 
                               "> 1 - 2" = "#FFBA00", 
                               "> 2 - 3" = "#FF9600", 
                               "> 3 - 4" = "#FF6908", 
                               "> 4 - 5" = "#E63D23", 
                               "> 5 - < 6" = "#BD251C", 
                               ">= 6" = "#8C130E")) +
  ggthemes::theme_map() +
  labs(fill = "Life years lost  ", title = expression("Potential Gains in Life Expectancy through Permanently Reducing" ~ PM[2.5] ~ "from 2021 concentrations to the WHO guideline")) + 
 theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15), 
       # legend.key = element_rect(color = "black"),
       legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 7), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
       legend.key = element_rect(color = "black"), 
       legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal") +
  guides(fill = guide_legend(nrow = 1))


# nepal fs figure 3

# top 5 most deadly diseases
nepal_fs_fig3_dataset <- gbd_results_master_2021 %>%
  filter(country == "Nepal")

colnames(nepal_fs_fig3_dataset)[3] <- c("llpp_who_2021")

nepal_fs_fig3_dataset <- nepal_fs_fig3_dataset %>%
    mutate(lyl_bucket = ifelse((llpp_who_2021 >= 0) & (llpp_who_2021 < 0.1), "0 - < 0.1 years", NA), 
         lyl_bucket = ifelse((llpp_who_2021 >= 0.1) & (llpp_who_2021 <= 0.5), "0.1 - 0.5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 0.5) & (llpp_who_2021 <= 1), "> 0.5 - 1", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 1) & (llpp_who_2021 <= 2), "> 1 - 2", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 2) & (llpp_who_2021 <= 3), "> 2 - 3", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 3) & (llpp_who_2021 <= 4), "> 3 - 4", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 4) & (llpp_who_2021 <= 5), "> 4 - 5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 5) & (llpp_who_2021 < 6), "> 5 - < 6 years", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 >= 6), ">= 6 years", lyl_bucket)) %>%
  mutate(order_lyl_bucket = ifelse(lyl_bucket == "0 - < 0.1 years", 1, NA), 
         order_lyl_bucket = ifelse(lyl_bucket == "0.1 - 0.5", 2, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 0.5 - 1", 3, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 1 - 2", 4, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 2 - 3", 5, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 3 - 4", 6, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 4 - 5", 7, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 5 - 6 years", 8, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == ">= 6 years", 9, order_lyl_bucket))


# getting disease (ordered from most deadly to least deadly) in a vector (to be used later in the
# scale_x_discrete function).

# cause_of_death_ordered <- india_fs_fig3_dataset %>%
#   arrange(llpp_who_2021) %>%
#   pull(cause_of_death) %>%
#   unlist()


# figure 3 plot
nepal_fs_fig3 <- nepal_fs_fig3_dataset %>%
  ggplot() + 
  geom_col(mapping = aes(x = forcats::fct_reorder(cause_of_death, llpp_who_2021), y = llpp_who_2021, fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), width = 0.5, color = "black") +
  labs(x = "Cause of Death", y = "Life Years Lost", fill = "Life years lost", 
       caption = str_wrap("* Source: Global Burden of Disease (https://vizhub.healthdata.org/gbd-results/) causes and risks data and WHO Life Tables (https://apps.who.int/gho/data/node.main.LIFECOUNTRY?lang=en) were used combined with the Life table method to arrive at these results. 'PM2.5 relative to WHO Guideline' bar displays life years lost relative to the WHO guideline as calculated by latest AQLI (2021) data, which will be published in September 2023.", width = 130), title = expression("Life Expectancy Impact of" ~ PM[2.5] ~ "and Unassociated Causes/Risks of Deaths in India")) +
  coord_flip() + 
  ggthemes::theme_tufte() +
  theme(legend.position = "bottom",
        axis.text = element_text(size = 14),
        axis.title.y = element_text(size = 16, margin = margin(r = 0.6, unit = "cm")),
        axis.title.x = element_text(size = 16, margin = margin(t = 0.6, b = 0.6, unit = "cm")),
        plot.caption = element_text(hjust = 0, size = 8, margin = margin(t = 0.8, unit = "cm")),
        plot.title = element_text(hjust = 0.5, size = 20, margin = margin(b = 0.8, unit = "cm")),
        plot.subtitle = element_text(hjust = 0.5, size = 10, margin = margin(b = 0.8, unit = "cm")),
        legend.box.background = element_rect(color = "black"),
        plot.background = element_rect(color = "white"),
        axis.line = element_line(), 
        legend.text = element_text(size = 11), 
        legend.title = element_text(size = 14),
        panel.grid.major.y = element_blank()) +
  scale_y_continuous(breaks = seq(0, 6, 0.5)) +
 # scale_x_discrete(limits = cause_of_death_ordered[seq(1, length(cause_of_death_ordered), by = 2)]) +
  scale_fill_manual(values = c("0 - < 0.1 years" = "#FFFFFF", 
                               "0.1 - 0.5" = "#FFE6B3", 
                               "> 0.5 - 1" = "#FFD25D", 
                               "> 1 - 2" = "#FFBA00", 
                               "> 2 - 3" = "#FF9600", 
                               "> 3 - 4" = "#FF6908", 
                               "> 4 - 5" = "#E63D23", 
                               "> 5 - < 6 years" = "#BD251C", 
                               ">= 6 years" = "#8C130E")) + 
  guides(fill = guide_legend(nrow = 1))



```
