---
title: "Factsheets 2024"
author: "Nishka Sharma, Hrishikesh Chandra Gautam"
output: html_document
date: "2024-03-08"
---

## SetUp
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-lib-helper-files-data-global-var}
# read in the helper file
source("R/july.2024.helper.script.R")
```

## India Factsheet 
```{r india_fs_2024}


# Indo Gangetic Plain, population and average PM2.5
# average pm2.5 and total population in Indo-Gangetic plains in 2022
summary_indo_gangetic_plain <- gadm2_aqli_2022 %>%
  filter(country == "India", name_1 %in% indo_gangetic_plains_states) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         pm2022_pop_weighted = pm2022*pop_weights) %>%
  summarise(avg_pm2.5_2022 = sum(pm2022_pop_weighted, na.rm = TRUE), 
            total_population = sum(population, na.rm = TRUE))


# Fig 1: Potential gain in Life Expectancy from permanently reducing PM2.5 ------ 
# from 2022 levels to the WHO PM2.5 guideline.
# separately getting Gilgit Baltistan and Azad Kashmir
azad_kashmir_gilgit_baltistan <- gadm2_aqli_2022 %>%
  filter(country == "Pakistan", name_1 %in% c("Azad Kashmir", "Gilgit Baltistan"))

# plot 1 data
india_fs_fig1_data <- gadm2_aqli_2022 %>%
  filter(country == "India") %>%
  bind_rows(azad_kashmir_gilgit_baltistan) %>%
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# india factsheet figure 1
india_fs_fig1 <- india_fs_fig1_data %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), color = "lightgrey", lwd = 0.05) +
  geom_sf(data = india_state, color = "black", fill = "transparent", lwd = 0.5) +
  ggthemes::theme_map() + 
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  ggthemes::theme_map() +
  labs(fill = "Potential gain in life expectancy (Years) ", title = "") + 
  theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15), 
        # legend.key = element_rect(color = "black"),
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 7), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
        legend.key = element_rect(color = "black"), 
        legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal", 
       plot.background = element_rect(fill = "white", color = "white")) +
  guides(fill = guide_legend(nrow = 1))


# Fig 2: Potential gain in life expectancy in 10 most populous states in India ------
india_fs_fig2_data <- gadm_level_summary(gadm2_aqli_2022, c("country", "name_1"), c(2022),  10) %>%
  filter(country == "India") %>% 
  slice_max(population, n = 10) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022")


india_fs_fig2_data$lyl_bucket <- as.factor(india_fs_fig2_data$lyl_bucket)

india_fs_fig2 <- india_fs_fig2_data %>%
  ggplot() +
  geom_col(mapping = aes(x = forcats::fct_reorder(name_1, llpp_who_2022), y = llpp_who_2022, fill = lyl_bucket), width = 0.5) +
  labs(x = "State", y = "Potential Gain in Life Expectancy (Years)",
       title = "",
       subtitle = "", 
       caption = "", 
       fill = "Potential gain in life expectancy (Years)") +
  scale_y_continuous(breaks = seq(0, 7, 1), limits = c(0, 7)) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  coord_flip() +
  ggthemes::theme_tufte() +
  themes_aqli_base +
  theme(legend.position = "bottom", 
        plot.title = element_text(hjust = 0.5, size = 16), 
        plot.subtitle = element_text(hjust =  0.5, size = 10, face = "italic", margin = margin(b = 0.8, unit = "cm")), 
        plot.caption = element_text(size = 8, hjust = 0, face = "italic"),
        axis.line = element_line(), 
        axis.text = element_text(size = 11), 
        axis.title = element_text(size = 13), 
        axis.title.y = element_text(margin = margin(r = 0.7, unit = "cm")), 
        axis.title.x = element_text(margin = margin(t = 0.6, b = 0.6, unit = "cm")), 
        axis.ticks = element_blank(),
        plot.background = element_rect(fill = "white", color = "white")) 


# Fig 3: GBD ------
# top 5 most deadly diseases
india_fs_fig3_dataset <- gbd_results_master_2022 %>%
  filter(country == "India") %>%
  slice_max(lyl, n = 5)

colnames(india_fs_fig3_dataset)[3] <- c("llpp_who_2022")

india_fs_fig3_dataset <- india_fs_fig3_dataset %>%
add_aqli_color_scale_buckets("lyl", "llpp_who_2022")

# figure 3 caption removed: 
# Source: Global Burden of Disease (https://vizhub.healthdata.org/gbd-results/) 
# causes and risks data and WHO Life Tables (https://apps.who.int/gho/data/node.main.LIFECOUNTRY?lang=en) 
# were used combined with the Life table method to arrive at these results. 
# 'PM2.5 relative to WHO Guideline' bar displays life years lost relative to the 
# WHO guideline as calculated by latest AQLI (2022) data, which will be published 
# in 2024.

india_fs_fig3 <- india_fs_fig3_dataset %>%
  ggplot() + 
  geom_col(mapping = aes(x = forcats::fct_reorder(cause_of_death, llpp_who_2022), 
                         y = llpp_who_2022, 
                         fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), 
           width = 0.4, color = "black") +
  labs(x = "Threats to Life Expectancy", y = "Life Years Lost", fill = "Life years lost", 
       title = expression("")) +
  coord_flip() + 
  ggthemes::theme_tufte() +
  themes_aqli_base +
  theme(legend.position = "bottom",
        axis.text = element_text(size = 14),
        axis.title.y = element_text(size = 16, margin = margin(r = 0.6, unit = "cm")),
        axis.title.x = element_text(size = 16, margin = margin(t = 0.6, b = 0.6, unit = "cm")),
        plot.caption = element_text(hjust = 0, size = 8, margin = margin(t = 0.8, unit = "cm")),
        plot.title = element_text(hjust = 0.5, size = 20, margin = margin(b = 0.8, unit = "cm")),
        plot.subtitle = element_text(hjust = 0.5, size = 10, margin = margin(b = 0.8, unit = "cm")),
        legend.box.background = element_rect(color = "black"),
        axis.line = element_line(), 
        legend.text = element_text(size = 11), 
        legend.title = element_text(size = 14),
        panel.grid.major.y = element_blank(), 
        plot.background = element_rect(fill = "white", color = "white")) +
  scale_y_continuous(breaks = seq(0, 6, 0.5)) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) + 
  guides(fill = guide_legend(nrow = 1)) 


# Figure 4: Average PM2.5 concentration in India from 1998 to 2022 ------

# adding a north India/rest of india region column (specifically Indo gangetic plain)
north_india <- c("West Bengal", "Uttar Pradesh", "Punjab", "Haryana", 
                 "Chandigarh", "Bihar", "NCT of Delhi")

india_fs_fig4_data_part1 <- gadm2_aqli_2022 %>%
  filter(country == "India", !is.na(population)) %>%
  mutate(region = ifelse(name_1 %in% north_india, "Northern Plains of India", "All other regions (excluding Northern Plains of India)"))


# creating India's region wise average PM2.5 data from 1998 to 2022 
india_fs_fig4_data_part1 <- india_fs_fig4_data_part1 %>%
  group_by(region) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2022_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+")))) %>%
  select(years, region, pop_weighted_avg_pm2.5)

# creating a national average PM2.5 trendlines data from 1998 to 2022
india_fs_fig4_data_part2 <- gadm2_aqli_2022 %>%
  filter(country == "India") %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2022_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))), 
         region = "National Average") %>% 
  select(years, region, pop_weighted_avg_pm2.5)

# India factsheet figure 4 dataset
india_fs_fig4_data <- rbind(india_fs_fig4_data_part1, india_fs_fig4_data_part2)

# India factsheet figure 4
# fig4 caption removed: "We define the Indo-Gangetic plain region as containing 
# the following seven states and union territories: Bihar, Chandigarh, NCT of Delhi, 
# Haryana, Punjab, Uttar Pradesh, and West Bengal."

india_fs_fig4_data$region <- factor(india_fs_fig4_data$region, 
                                    levels = c("Northern Plains of India", 
                                               "National Average", 
                                               "All other regions (excluding Northern Plains of India)"))

india_fs_fig4 <- ggplot(india_fs_fig4_data) +
  geom_line(mapping = aes(x = years, y = pop_weighted_avg_pm2.5, 
                          color = interaction(region), 
                          linetype = interaction(region)), lwd = 1.3) +
  geom_hline(mapping = aes(yintercept = 5), lwd = 0.8, linetype = "dotted", color = "lightgrey") +
  scale_y_continuous(breaks = seq(0, 100, 10), limits = c(0, 100)) +
  scale_x_continuous(breaks = c(seq(1998, 2019, 3), 2022)) +
  scale_color_manual(values = c("Northern Plains of India" = "#1a1638", 
                                "National Average" =  "#3c456f", 
                                "All other regions (excluding Northern Plains of India)" = "#4e5e8b"), 
                     name = "legend") +
  scale_linetype_manual(values = c("Northern Plains of India" = "dashed", 
                                   "National Average" = "solid", 
                                   "All other regions (excluding Northern Plains of India)" = "dotted"), 
                        name = "legend")  +
  ggthemes::theme_tufte() +
  labs(x = "Year", 
       y = expression("Annual Average   " ~ PM[2.5] ~ " Concentration (in µg/m³)"), 
       title = "") +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 11),
        legend.title = element_blank(),
        axis.title.y = element_text(size = 13, margin = margin(r = 0.6, unit = "cm")), 
        axis.title.x = element_text(size = 13, margin = margin(t = 0.6, b = 0.6, unit = "cm")), 
        axis.line = element_line(), 
        legend.box.background = element_rect(color = "black"),
        plot.title = element_text(hjust = 0.5, size = 16, margin = margin(b = 0.7, unit = "cm")), 
        plot.subtitle = element_text(hjust = 0.5, size = 8, face = "italic"), 
        plot.caption = element_text(size = 7, margin = margin(t = 0.8, unit = "cm"), hjust = 0, face = "italic"),
        axis.text = element_text(size = 12), 
        plot.background = element_rect(color = "white"), 
        axis.ticks = element_blank(), 
        legend.key.width = unit(2, "cm")) +
     geom_text(x = 2003.5, y = 7.6, label = expression("WHO" ~ PM[2.5] ~ "Guideline (last updated: 2022): 5 µg/m³"), size = 4.5) 


# appendix table ------
india_fs_appendix_table <- gadm_level_summary(gadm2_aqli_2022, c("country", "name_1"), c(2022), 10) %>%
  filter(country == "India") %>%
  mutate(population_lakhs = round(population/100000, 1)) %>%
  select(name_1, population_lakhs, pm2022, llpp_who_2022, llpp_nat_2022) %>%
  rename("State/UT" = name_1, 
         "Population (Lakhs)" = population_lakhs, 
         "Annual Average 2022 PM2.5 Concentration (µg/m³)" = pm2022, 
         "Life Expectancy Gains from reducing PM2.5 from 2022 concentration to WHO PM2.5 guideline of 5 µg/m³" = llpp_who_2022, 
         "Life Expectancy Gains from reducing PM2.5 from 2022 concentration to National PM2.5 guideline of 40 µg/m³" = llpp_nat_2022)
```

## Bangladesh Factsheet
```{r}

# stats check/update
# by what multiple does particulate pollution exceed the WHO guideline in each of Bangladesh's districts
gadm2_aqli_2022 %>%
  filter(country == "Bangladesh") %>%
  mutate(mult_of_who = pm2022/5, 
         mult_of_nat = pm2022/15) %>%
  select(name_1, name_2, mult_of_who, mult_of_nat) %>% 
  slice_min(mult_of_who, n = 5) %>%
  View()


gadm2_aqli_2022 %>%
  filter(country == "Bangladesh") %>%
  slice_max(population, n = 5)

gadm2_aqli_2022 %>%
  gadm_level_summary(c("country"), c(2022), 10) %>%
  filter(country == "Bangladesh")

# Fig 1: Potential gain in Life Expectancy from permanently reducing PM2.5 from ------
# 2022 levels to the WHO PM2.5 guideline.

# bangladesh figure1 dataset
bangladesh_fs_fig1_data <- gadm2_aqli_2022 %>%
  filter(country == "Bangladesh") %>%
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# bangladesh figure 1
bangladesh_fs_fig1 <- bangladesh_fs_fig1_data %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), color = "lightgrey", lwd = 0.05) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 == "Bangladesh"), color = "black", fill = "transparent", lwd = 0.15) +
  ggthemes::theme_map() + 
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  ggthemes::theme_map() +
  labs(fill = "Potential gain in life expectancy (Years)  ", title = "") + 
  theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15), 
        # legend.key = element_rect(color = "black"),
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 7), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
        legend.key = element_rect(color = "black"), 
        legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal", 
       plot.background = element_rect(fill = "white", color = "white")) +
  guides(fill = guide_legend(nrow = 1))


# Fig 2: Potential Gain in Life Expectancy from Reducing PM2.5 ------
# from 2022 to the WHO Guideline in 10 most populous regions of Bangladesh 

# bangladesh figure 2 data
bangladesh_fs_fig2_dataset <- gadm2_aqli_2022 %>%
  filter(country == "Bangladesh") %>%
  add_aqli_color_scale_buckets(scale_type = "lyl", col_name = "llpp_who_2022") %>%
  slice_max(population, n = 10)

# bangladesh figure 2
bangladesh_fs_fig2 <- bangladesh_fs_fig2_dataset %>%
  aqli_bar(scale_type = "lyl", x_var = "name_2", y_var = "llpp_who_2022", title = "", subtitle = "", x_label = "District", y_label = "Potential Gain in Life Expectancy (Years)", legend_title = "Potential gain in life expectancy (Years)", caption = "") +
  theme(legend.position = "bottom", 
        plot.title = element_text(hjust = 0.5, size = 16), 
        plot.subtitle = element_text(hjust =  0.5, size = 10, face = "italic", margin = margin(b = 0.8, unit = "cm")), 
        plot.caption = element_text(size = 8, hjust = 0, face = "italic"),
        axis.line = element_line(), 
        axis.text = element_text(size = 11), 
        axis.title = element_text(size = 13), 
        axis.title.y = element_text(margin = margin(r = 0.7, unit = "cm")), 
        axis.title.x = element_text(margin = margin(t = 0.6, b = 0.6, unit = "cm")), 
        axis.ticks = element_blank(),
        plot.background = element_rect(fill = "white", color = "white"))


# Fig 3: GBD ------

# top 10 most deadly diseases
bangladesh_fs_fig3_dataset <- gbd_results_master_2022 %>%
  filter(country == "Bangladesh") %>%
  slice_max(lyl, n = 10)

colnames(bangladesh_fs_fig3_dataset)[3] <- c("llpp_who_2022")

# bangladesh figure 3 data
bangladesh_fs_fig3_dataset <- bangladesh_fs_fig3_dataset %>%
   add_aqli_color_scale_buckets("lyl", "llpp_who_2022")

# bangladesh figure 3

#' figure 3 caption removed: Source: Global Burden of Disease 
#' (https://vizhub.healthdata.org/gbd-results/) causes and risks data and WHO 
#' Life Tables (https://apps.who.int/gho/data/node.main.LIFECOUNTRY?lang=en) 
#' were used combined with the Life table method to arrive at these results. 
#' 'PM2.5 relative to WHO Guideline' bar displays life years lost relative to 
#' the WHO guideline as calculated by latest AQLI (2022) data, which will be 
#' published in September 2024.

bangladesh_fs_fig3 <- bangladesh_fs_fig3_dataset %>%
  ggplot() + 
  geom_col(mapping = aes(x = forcats::fct_reorder(cause_of_death, llpp_who_2022), 
                         y = llpp_who_2022, 
                         fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), 
           width = 0.4, color = "black") +
  labs(x = "Threats to Life Expectancy", y = "Life Years Lost", fill = "Life years lost", 
       title = "") +
  coord_flip() + 
  ggthemes::theme_tufte() +
  themes_aqli_base +
  theme(legend.position = "bottom",
        axis.text = element_text(size = 14),
        axis.title.y = element_text(size = 16, margin = margin(r = 0.6, unit = "cm")),
        axis.title.x = element_text(size = 16, margin = margin(t = 0.6, b = 0.6, unit = "cm")),
        plot.caption = element_text(hjust = 0, size = 8, margin = margin(t = 0.8, unit = "cm")),
        plot.title = element_text(hjust = 0.5, size = 20, margin = margin(b = 0.8, unit = "cm")),
        plot.subtitle = element_text(hjust = 0.5, size = 10, margin = margin(b = 0.8, unit = "cm")),
        legend.box.background = element_rect(color = "black"),
        axis.line = element_line(), 
        legend.text = element_text(size = 11), 
        legend.title = element_text(size = 14),
        panel.grid.major.y = element_blank(), 
        plot.background = element_rect(fill = "white", color = "white")) +
  scale_y_continuous(breaks = seq(0, 7, 1)) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) + 
  guides(fill = guide_legend(nrow = 1)) 


# Fig 4: Average PM2.5 concentration in Bangladesh from 1998 to 2022 ------

# bangladesh figure 4 data
bangladesh_fs_fig4_dataset <- gadm2_aqli_2022 %>%
  filter(country == "Bangladesh", !is.na(population)) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2022_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))), 
         region = "National Average") %>% 
  select(years, region, pop_weighted_avg_pm2.5)

# bangladesh figure 4
bangladesh_fs_fig4 <- bangladesh_fs_fig4_dataset %>%  
  ggplot() +
  geom_line(mapping = ggplot2::aes(x = years, y = pop_weighted_avg_pm2.5), lwd = 1.1,   
            color = "#1a1638") +
  geom_hline(mapping = aes(yintercept = 5), lwd = 0.8, linetype = "dashed") +
  geom_hline(mapping = aes(yintercept = 15), lwd = 0.8, linetype = "dashed") + 
  scale_y_continuous(breaks = seq(0, 80, 10), limits = c(0, 80)) +
  scale_x_continuous(breaks = c(seq(1998, 2019, 3), 2022)) +
  scale_color_manual(values = c("National Average" = "#1a1638")) +
  ggthemes::theme_clean() +
  themes_aqli_base +
  labs(x = "Year", 
       y = expression("Annual Average  " ~ PM[2.5] ~ " Concentration (in µg/m³)"), 
       title = "") +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 11),
        legend.title = element_blank(),
        axis.title.y = element_text(size = 13, margin = margin(r = 0.6, unit = "cm")), 
        axis.title.x = element_text(size = 13, margin = margin(t = 0.6, b = 0.6, unit = "cm")), 
        axis.line = element_line(), 
        legend.box.background = element_rect(color = "black"),
        plot.title = element_text(hjust = 0.5, size = 16, margin = margin(b = 0.7, unit = "cm")), 
        plot.subtitle = element_text(hjust = 0.5, size = 8, face = "italic"), 
        plot.caption = element_text(size = 7, margin = margin(t = 0.8, unit = "cm"), hjust = 0, face = "italic"),
        axis.text = element_text(size = 12), 
        plot.background = element_rect(color = "white"), 
        axis.ticks = element_blank(), 
        legend.key.width = unit(2, "cm")) +
  geom_text(x = 2003.8, y = 6.7, label =  expression("WHO " ~ PM[2.5] ~ " Guideline (last updated in 2022): 5 µg/m³"), size = 5) +
  geom_text(x = 2002.9, y = 16.7, label = expression("Bangladesh National" ~ PM[2.5] ~ "Standard: 15 µg/m³"), size = 5) 


# appendix table ------
bangladesh_fs_appendix_table <- gadm2_aqli_2022 %>%
    filter(country == "Bangladesh") %>%
    select(name_1, name_2, population, pm2022, llpp_who_2022, llpp_nat_2022) %>%
    mutate(pop_millions = round(population/1000000, 1), 
           pm2022 = round(pm2022, 1), 
           llpp_who_2022 = round(llpp_who_2022, 1), 
           llpp_nat_2022 = round(llpp_nat_2022, 1)) %>%
  mutate(lyg_red_pm2.5_30perc_2022 = round((pm2022*0.3)*0.098, 1)) %>%
    slice_max(population, n = 25) %>% 
    select(name_1, name_2, pop_millions, pm2022, llpp_who_2022, llpp_nat_2022, lyg_red_pm2.5_30perc_2022) %>%
    rename(`Population (Millions)` = pop_millions, 
           "Division" = name_1, 
           "District" = name_2, 
           "PM2.5 concentration 2022 (in µg/m³)" = pm2022, 
           "Life Expectancy Gains from reducing PM2.5 from 2022 Concentrations to the National Guideline of 15 µg/m³" = llpp_nat_2022, 
           "Life Expectancy Gains from reducing PM2.5 from 2022 Concentrations to the WHO Guideline of 5 µg/m³" = llpp_who_2022, 
           "Life Expectancy Gains from reducing PM2.5 from 2022 Concentrations by 30 percent" = lyg_red_pm2.5_30perc_2022)

```

## Pakistan factsheet
```{r}

# read and filter AQLI data
pak_aqli_2022 <- gadm2_aqli_2022 %>%
  filter(country == "Pakistan") %>%
  mutate(region = case_when(
    name_1 == "Islamabad" ~ "Islamabad",
    name_1 == "Punjab" ~ "Punjab",
    name_1 != "Islamabad"| name_1 != "Punjab" ~ "All other regions (excluding Islamabad and Punjab)"))

# Fig 1: Potential gain in life expectancy from permanently reducing PM2.5 ------
# in 2022 to WHO guideline

# pakistan fs fig 1 data
pak_fs_fig1_dataset <- pak_aqli_2022 %>%
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  select('country', 'name_1', 'name_2', 'population', 'pm2022', 'llpp_who_2022', 'geometry') %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# pakistan fs figure 1
pak_fs_fig1 <- pak_fs_fig1_dataset %>%
  ggplot() +
  geom_sf(mapping = aes(fill = reorder(lyl_bucket, order_lyl_bucket)), color = "aliceblue", lwd = 0.05) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 == "Pakistan"), color = "azure4", fill = "transparent", lwd = 0.15) +
  geom_sf(data = gadm0_aqli_2022_shp %>% filter(name0 == "Pakistan"), color = "cornsilk4", fill = "transparent", lwd = 0.5) +
  ggthemes::theme_map() + 
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  ggthemes::theme_map() +
  labs(fill = "Potential gain in life expectancy (Years)") + 
  theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15), 
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 7), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
        legend.key = element_rect(color = "black"), 
        legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal") +
  guides(fill = guide_legend(nrow = 1))


# Fig 2: Potential gain in life expectancy in states in Pakistan ------

# pakistan fs fig 2 data
pak_fs_fig2_dataset <- pak_aqli_2022 %>%
  select('country', 'name_1', 'name_2', 'population', 'pm2022', 'llpp_who_2022', 'llpp_nat_2022') %>%
  group_by(name_1) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         pm2022_pop_weighted = pop_weights*pm2022,
         llpp_who_2022_pop_weighted = pop_weights*llpp_who_2022,
         llpp_nat_2022_pop_weighted = pop_weights*llpp_nat_2022) %>%
  summarise(tot_pop = sum(population, na.rm = TRUE), 
            avg_pm2.5_2022 = sum(pm2022_pop_weighted, na.rm = TRUE),
            le_gain = (avg_pm2.5_2022 - who_guideline)*le_constant,
            llpp_who_2022 = sum(llpp_who_2022_pop_weighted, na.rm = TRUE),
            llpp_nat_2022 = sum(llpp_nat_2022_pop_weighted, na.rm = TRUE),
            le_gain = ifelse(le_gain < 0 , 0, le_gain)) %>%
  slice_max(tot_pop, n = 10) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022")

# pakistan fs figure 2
pak_fs_fig2 <- pak_fs_fig2_dataset %>%
  ggplot() +
  geom_col(mapping = aes(x = reorder(name_1, llpp_who_2022), y = llpp_who_2022, fill = lyl_bucket), width = 0.5) +
  labs(x = "Province", y = "Potential Gain in Life Expectancy  (Years)", fill = "Potential gain in life expectancy (Years)") +
  scale_y_continuous(breaks = seq(0, 5, 1), limits = c(0, 5)) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  coord_flip() + 
  ggthemes::theme_tufte() +
  theme(legend.position = "bottom", 
        plot.title = element_text(hjust = 0.5, size = 16), 
        plot.subtitle = element_text(hjust =  0.5, size = 10, face = "italic", margin = margin(b = 0.8, unit = "cm")), 
        plot.caption = element_text(size = 8, hjust = 0, face = "italic"),
        legend.box.background = element_rect(color = "black"),
        plot.background = element_rect(color = "white"),
        axis.line = element_line(), 
        axis.text = element_text(size = 11), 
        axis.title = element_text(size = 13), 
        axis.title.y = element_text(margin = margin(r = 0.7, unit = "cm")), 
        axis.title.x = element_text(margin = margin(t = 0.6, b = 0.6, unit = "cm")), 
        axis.ticks = element_blank()) 


# Fig 3: GBD ------
# pakistan fs fig 3 data
pak_fs_fig3_dataset <- gbd_results_master_2022 %>%
  filter(country == "Pakistan")

# filtering out those causes of death that are sort of* covered under PM2.5 in some broad way
colnames(pak_fs_fig3_dataset)[3] <- c("llpp_who_2022")

pak_fs_fig3_dataset <- pak_fs_fig3_dataset %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  slice_max(llpp_who_2022, n = 5)

# pakistan factsheet figure 3
pak_fs_fig3 <- pak_fs_fig3_dataset %>%
  ggplot() + 
  geom_col(mapping = aes(x = reorder(cause_of_death, llpp_who_2022), y = llpp_who_2022, fill = reorder(lyl_bucket, order_lyl_bucket)), width = 0.5, color = "black") +
  labs(x = "Threats to life expectancy", y = "Life Years Lost", fill = "Life years lost") +
  coord_flip() + 
  ggthemes::theme_tufte() +
  theme(legend.position = "bottom",
        axis.text = element_text(size = 14),
        axis.title.y = element_text(size = 16, margin = margin(r = 0.6, unit = "cm")),
        axis.title.x = element_text(size = 16, margin = margin(t = 0.6, b = 0.6, unit = "cm")),
        plot.caption = element_text(hjust = 0, size = 8, margin = margin(t = 0.8, unit = "cm"), face = "italic"),
        plot.title = element_text(hjust = 0.5, size = 20, margin = margin(b = 0.8, unit = "cm")),
        plot.subtitle = element_text(hjust = 0.5, size = 10, margin = margin(b = 0.8, unit = "cm"), face = "italic"),
        legend.box.background = element_rect(color = "black"),
        plot.background = element_rect(color = "white"),
        axis.line = element_line(), 
        legend.text = element_text(size = 11), 
        legend.title = element_text(size = 14),
        panel.grid.major.y = element_blank()) +
  scale_y_continuous(breaks = seq(0, 6, 0.5)) +
  # scale_x_discrete(limits = cause_of_death_ordered[seq(1, length(cause_of_death_ordered), by = 2)]) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  guides(fill = guide_legend(nrow = 1))


# Fig 4: Average PM2.5 concentration in Pakistan from 1998 to 2022 ------

# pakistan factsheet figure 4 dataset
pak_region_avg_ts <- pak_aqli_2022 %>%
  group_by(region) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2022_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+")))) %>%
  select(years, region, pop_weighted_avg_pm2.5)

pak_nat_avg_ts <- pak_aqli_2022 %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2022_weighted, names_to = "years",
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))),
         region = "National Average") %>%
  select(years, region, pop_weighted_avg_pm2.5)

pak_fs_fig4_dataset <- rbind(pak_region_avg_ts, pak_nat_avg_ts)

pak_fs_fig4_dataset$region = factor(pak_fs_fig4_dataset$region, levels = c('Islamabad', 'Punjab', 'National Average', 'All other regions (excluding Islamabad and Punjab)'))

# pakistan factsheet figure 4
pak_fs_fig4 <- pak_fs_fig4_dataset %>%
  ggplot() +
  geom_line(mapping = aes(x = as.integer(years), 
                          y = as.double(pop_weighted_avg_pm2.5),
                          colour = region, linetype = region), 
            lwd = 1.1) +
  geom_hline(mapping = aes(yintercept = 5), lwd = 0.8, linetype = "dotted") +
  scale_y_continuous(breaks = seq(0, 100, 5), limits = c(0, 60)) +
  scale_x_continuous(breaks = c(seq(1998, 2019, 3), 2022))  +
  scale_color_manual(values = c("Islamabad" = "#3c456f", "Punjab" = "#3c456f", "National Average" = "#4e5e8b", "All other regions (excluding Islamabad and Punjab)" = "#5f7aa5")) +
  scale_linetype_manual(values = c("Islamabad" = "dashed", "Punjab" = "dashed", "National Average" = "solid", "All other regions (excluding Islamabad and Punjab)" = "dotted")) +
  ggthemes::theme_tufte() +
  labs(x = "Year", 
       y = expression("Annual Average" ~ PM[2.5] ~ "Concentration (in µg/m³)")) +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 11),
        legend.title = element_blank(),
        axis.title.y = element_text(size = 13, margin = margin(r = 0.6, unit = "cm")), 
        axis.title.x = element_text(size = 13, margin = margin(t = 0.6, b = 0.6, unit = "cm")), 
        axis.line = element_line(), 
        legend.box.background = element_rect(color = "black"),
        plot.title = element_text(hjust = 0.5, size = 16, margin = margin(b = 0.7, unit = "cm")), 
        plot.subtitle = element_text(hjust = 0.5, size = 8, face = "italic"), 
        plot.caption = element_text(size = 7, margin = margin(t = 0.8, unit = "cm"), hjust = 0, face = "italic"),
        axis.text = element_text(size = 12), 
        plot.background = element_rect(color = "white"), 
        axis.ticks = element_blank()) +
  geom_text(x = 2002.8, y = 6.8, label = expression("WHO" ~ PM[2.5] ~ "Guideline (last updated: 2022): 5 µg/m³"), size = 4.5)


# appendix table ------
pak_fs_appendix_table <- pak_aqli_2022 %>%
  mutate(pm2022 = round(pm2022, 1),
         le_gain_red_to_who = round((pm2022 - who_guideline)*le_constant, 1),
         le_gain_red_to_who = ifelse(le_gain_red_to_who < 0, 0, le_gain_red_to_who),
         le_gain_red_to_nat = round((pm2022 - natstandard)*le_constant, 1),
         le_gain_red_to_nat = ifelse(le_gain_red_to_nat < 0, 0, le_gain_red_to_nat),
         le_gain_red_by_30_percent = round((pm2022*0.3)*le_constant, 1), 
         pop_millions = round(population/1000000, 3)) %>%
  select(name_2, pop_millions, pm2022, le_gain_red_to_who, le_gain_red_to_nat,
         le_gain_red_by_30_percent) %>%
  ungroup() %>%
  slice_max(pop_millions, n = 25) %>%
  mutate(pop_millions = round(pop_millions, 1)) %>%
  rename(`Region` = name_2, 
         `Population (Millions)` = pop_millions, 
         `Annual Average 2022 PM2.5 Concentration (µg/m³)` = pm2022,
         `Life Expectancy Gains from reducing PM2.5 from 2022 concentration to WHO PM2.5 guideline of 5 µg/m` = le_gain_red_to_who, 
         `Life Expectancy Gains from reducing PM2.5 from 2022 concentration to National PM2.5 guideline of 15 µg/m³` = le_gain_red_to_nat,
         `Life Expectancy Gains from reducing PM2.5 from 2022 concentration by 30 percent` = le_gain_red_by_30_percent)
```

## Nepal Factsheet
```{r}

# Fig 1:  Potential gain in Life Expectancy from permanently reducing PM2.5 ------ 
# from 2022 levels to the WHO PM2.5 guideline.
# nepal fs fig 1 data
nepal_fs_fig1_dataset <- gadm2_aqli_2022 %>%
  filter(country == "Nepal") %>%
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  select('country', 'name_1', 'name_2', 'population', 'pm2022', 'llpp_who_2022', 'geometry') %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# nepal fs figure 1
nepal_fs_fig1 <- nepal_fs_fig1_dataset %>%
  ggplot() +
  geom_sf(mapping = aes(fill = reorder(lyl_bucket, order_lyl_bucket)), color = "aliceblue", lwd = 0.05) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 == "Nepal"), color = "azure4", fill = "transparent", lwd = 0.15) +
  geom_sf(data = gadm0_aqli_2022_shp %>% filter(name0 == "Nepal"), color = "cornsilk4", fill = "transparent", lwd = 0.5) +
  ggthemes::theme_map() + 
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  ggthemes::theme_map() +
  labs(fill = "Potential gain in life expectancy (Years)") + 
  theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15), 
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 7), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
        legend.key = element_rect(color = "black"), 
        legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal") +
  guides(fill = guide_legend(nrow = 1))


# Fig 2: Potential gain in life expectancy in states in Nepal ------

# nepal fs fig 2 data
nepal_fs_fig2_dataset <- gadm2_aqli_2022 %>%
  filter(country == "Nepal") %>%
  select('country', 'name_1', 'name_2', 'population', 'pm2022', 'llpp_who_2022') %>%
  group_by(name_1) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         pm2022_pop_weighted = pop_weights*pm2022,
         llpp_who_2022_pop_weighted = pop_weights*llpp_who_2022) %>%
  summarise(tot_pop = sum(population, na.rm = TRUE), 
            avg_pm2.5_2022 = sum(pm2022_pop_weighted, na.rm = TRUE),
            le_gain = (avg_pm2.5_2022 - who_guideline)*le_constant,
            llpp_who_2022 = sum(llpp_who_2022_pop_weighted, na.rm = TRUE),
            le_gain = ifelse(le_gain < 0 , 0, le_gain)) %>%
  slice_max(tot_pop, n = 10) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022")

# nepal fs figure 2
nepal_fs_fig2 <- nepal_fs_fig2_dataset %>%
  ggplot() +
  geom_col(mapping = aes(x = reorder(name_1, llpp_who_2022), y = llpp_who_2022, fill = lyl_bucket), width = 0.5) +
  labs(x = "Province", y = "Potential Gain in Life Expectancy (Years)", fill = "Potential gain in life expectancy (Years)") +
  scale_y_continuous(breaks = seq(0, 8, 1), limits = c(0, 8)) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  coord_flip() + 
  ggthemes::theme_tufte() +
  theme(legend.position = "bottom", 
        plot.title = element_text(hjust = 0.5, size = 16), 
        plot.subtitle = element_text(hjust =  0.5, size = 10, face = "italic", margin = margin(b = 0.8, unit = "cm")), 
        plot.caption = element_text(size = 8, hjust = 0, face = "italic"),
        legend.box.background = element_rect(color = "black"),
        plot.background = element_rect(color = "white"),
        axis.line = element_line(), 
        axis.text = element_text(size = 11), 
        axis.title = element_text(size = 13), 
        axis.title.y = element_text(margin = margin(r = 0.7, unit = "cm")), 
        axis.title.x = element_text(margin = margin(t = 0.6, b = 0.6, unit = "cm")), 
        axis.ticks = element_blank()) 


# Fig 3: GBD ------

# read and filter gbd results for nepal
nepal_fs_fig3_dataset <-  gbd_results_master_2022  %>%
  filter(country == "Nepal")

# filtering out those causes of death that are sort of* covered under PM2.5 in some broad way
colnames(nepal_fs_fig3_dataset)[3] <- c("llpp_who_2022")

# nepal fs fig 3 data
nepal_fs_fig3_dataset <- nepal_fs_fig3_dataset %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  slice_max(llpp_who_2022, n = 5)

# nepal factsheet figure 3
nepal_fs_fig3 <- nepal_fs_fig3_dataset %>%
  ggplot() + 
  geom_col(mapping = aes(x = reorder(cause_of_death, llpp_who_2022), y = llpp_who_2022, fill = reorder(lyl_bucket, order_lyl_bucket)), width = 0.5, color = "black") +
  labs(x = "Threats to life expectancy", y = "Life Years Lost", fill = "Life years lost") +
  coord_flip() + 
  ggthemes::theme_tufte() +
  theme(legend.position = "bottom",
        axis.text = element_text(size = 14),
        axis.title.y = element_text(size = 16, margin = margin(r = 0.6, unit = "cm")),
        axis.title.x = element_text(size = 16, margin = margin(t = 0.6, b = 0.6, unit = "cm")),
        plot.caption = element_text(hjust = 0, size = 8, margin = margin(t = 0.8, unit = "cm"), face = "italic"),
        plot.title = element_text(hjust = 0.5, size = 20, margin = margin(b = 0.8, unit = "cm")),
        plot.subtitle = element_text(hjust = 0.5, size = 10, margin = margin(b = 0.8, unit = "cm"), face = "italic"),
        legend.box.background = element_rect(color = "black"),
        plot.background = element_rect(color = "white"),
        axis.line = element_line(), 
        legend.text = element_text(size = 11), 
        legend.title = element_text(size = 14),
        panel.grid.major.y = element_blank()) +
  scale_y_continuous(breaks = seq(0, 6, 0.5)) +
  # scale_x_discrete(limits = cause_of_death_ordered[seq(1, length(cause_of_death_ordered), by = 2)]) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  guides(fill = guide_legend(nrow = 1))


# Fig 4: Average PM2.5 concentration in Nepal from 1998 to 2022 ------

# nepal factsheet figure 4 dataset
nepal_fs_fig4_dataset <- gadm2_aqli_2022 %>%
  filter(country == "Nepal") %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2022_weighted, names_to = "years",
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))),
         region = "National Average") %>%
  select(years, region, pop_weighted_avg_pm2.5)

# nepal factsheet figure 4
nepal_fs_fig4 <- nepal_fs_fig4_dataset %>%
  ggplot() +
  geom_line(mapping = aes(x = as.integer(years), 
                          y = as.double(pop_weighted_avg_pm2.5)), 
            lwd = 1.1, color = "#3c456f") +
  geom_hline(mapping = aes(yintercept = 5), lwd = 0.8, linetype = "dotted") +
  scale_y_continuous(breaks = seq(0, 100, 5), limits = c(0, 60)) +
  scale_x_continuous(breaks = c(seq(1998, 2019, 3), 2022))  +
  ggthemes::theme_tufte() +
  labs(x = "Year", 
       y = expression("Annual Average" ~ PM[2.5] ~ "Concentration (in µg/m³)")) +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 11),
        legend.title = element_blank(),
        axis.title.y = element_text(size = 13, margin = margin(r = 0.6, unit = "cm")), 
        axis.title.x = element_text(size = 13, margin = margin(t = 0.6, b = 0.6, unit = "cm")), 
        axis.line = element_line(), 
        legend.box.background = element_rect(color = "black"),
        plot.title = element_text(hjust = 0.5, size = 16, margin = margin(b = 0.7, unit = "cm")), 
        plot.subtitle = element_text(hjust = 0.5, size = 8, face = "italic"), 
        plot.caption = element_text(size = 7, margin = margin(t = 0.8, unit = "cm"), hjust = 0, face = "italic"),
        axis.text = element_text(size = 12), 
        plot.background = element_rect(color = "white"), 
        axis.ticks = element_blank()) +
  geom_text(x = 2000.6, y = 6.8, label = expression("WHO" ~ PM[2.5] ~ "Guideline (last updated: 2022): 5 µg/m³"), size = 4.5)


# appendix table ------

# nepal factsheet appendix table 
nepal_fs_appendix_table <- gadm2_aqli_2022 %>%
  mutate(pm2022 = round(pm2022, 1),
         le_gain_red_to_who = round((pm2022 - who_guideline)*le_constant, 1),
         le_gain_red_to_who = ifelse(le_gain_red_to_who < 0, 0, le_gain_red_to_who),
         le_gain_red_by_30_percent = round((pm2022*0.3)*le_constant, 1), 
         pop_millions = round(population/1000000, 3)) %>%
  select(name_2, pop_millions, pm2022, le_gain_red_to_who, 
         le_gain_red_by_30_percent) %>%
  ungroup() %>%
  slice_max(pop_millions, n = 25) %>%
  mutate(pop_millions = round(pop_millions, 1)) %>%
  rename(`District Coordination Committee` = name_2, 
         `Population (Millions)` = pop_millions, 
         `Annual Average 2022 PM2.5 Concentration (µg/m³)` = pm2022,
         `Life Expectancy Gains from reducing PM2.5 from 2022 concentration to WHO PM2.5 guideline of 5 µg/m` = le_gain_red_to_who, 
         `Life Expectancy Gains from reducing PM2.5 from 2022 concentration by 30 percent` = le_gain_red_by_30_percent) 

```
## Indonesia factsheet
```{r}
# figure 1 ---------

# indonesia fs fig 1 data
indonesia_fs_fig1_dataset <- gadm2_aqli_2022 %>%
  filter(country == "Indonesia") %>% 
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  select('country', 'name_1', 'name_2', 'population', 'pm2022', 'llpp_who_2022', 'geometry') %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# indonesia fs figure 1
indonesia_fs_fig1 <- indonesia_fs_fig1_dataset %>%
  ggplot() +
  geom_sf(mapping = aes(fill = reorder(lyl_bucket, order_lyl_bucket)), color = "aliceblue", lwd = 0.05) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 == "Indonesia"), color = "azure4", fill = "transparent", lwd = 0.15) +
  geom_sf(data = gadm0_aqli_2022_shp %>% filter(name0 == "Indonesia"), color = "cornsilk4", fill = "transparent", lwd = 0.5) +
  ggthemes::theme_map() + 
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  ggthemes::theme_map() +
  labs(fill = "Potential gain in life expectancy (Years)") + 
  theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15), 
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 7), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
        legend.key = element_rect(color = "black"), 
        legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal") +
  guides(fill = guide_legend(nrow = 1))

# figure 2 ---------

# indonesia fs fig 2 data
indonesia_fs_fig2_dataset <- gadm2_aqli_2022 %>%
  filter(country == "Indonesia") %>%
  select('country', 'name_1', 'name_2', 'population', 'pm2022', 'llpp_who_2022') %>%
  group_by(name_1) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         pm2022_pop_weighted = pop_weights*pm2022,
         llpp_who_2022_pop_weighted = pop_weights*llpp_who_2022) %>%
  summarise(tot_pop = sum(population, na.rm = TRUE), 
            avg_pm2.5_2022 = sum(pm2022_pop_weighted, na.rm = TRUE),
            le_gain = (avg_pm2.5_2022 - who_guideline)*le_constant,
            llpp_who_2022 = sum(llpp_who_2022_pop_weighted, na.rm = TRUE),
            le_gain = ifelse(le_gain < 0 , 0, le_gain)) %>%
  slice_max(tot_pop, n = 10) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022")

# indonesia fs figure 2
indonesia_fs_fig2 <- indonesia_fs_fig2_dataset %>%
  ggplot() +
  geom_col(mapping = aes(x = reorder(name_1, llpp_who_2022), y = llpp_who_2022, fill = lyl_bucket), width = 0.5) +
  labs(x = "Province", y = "Potential Gain in Life Expectancy (Years)", fill = "Potential gain in life expectancy (Years)") +
  scale_y_continuous(breaks = seq(0, 3, 1), limits = c(0, 3)) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  coord_flip() + 
  ggthemes::theme_tufte() +
  theme(legend.position = "bottom", 
        plot.title = element_text(hjust = 0.5, size = 16), 
        plot.subtitle = element_text(hjust =  0.5, size = 10, face = "italic", margin = margin(b = 0.8, unit = "cm")), 
        plot.caption = element_text(size = 8, hjust = 0, face = "italic"),
        legend.box.background = element_rect(color = "black"),
        plot.background = element_rect(color = "white"),
        axis.line = element_line(), 
        axis.text = element_text(size = 11), 
        axis.title = element_text(size = 13), 
        axis.title.y = element_text(margin = margin(r = 0.7, unit = "cm")), 
        axis.title.x = element_text(margin = margin(t = 0.6, b = 0.6, unit = "cm")), 
        axis.ticks = element_blank()) 

# figure 3 -----------

# read and filter gbd results for indonesia
gbd_results_indonesia <- gbd_results_master_2022 %>%
  filter(country == "Indonesia") 

# filtering out those causes of death that are sort of* covered under PM2.5 in some broad way
colnames(gbd_results_indonesia)[3] <- c("llpp_who_2022")

# indonesia fs fig 3 data
indonesia_fs_fig3_dataset <- gbd_results_indonesia %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  slice_max(llpp_who_2022, n = 10)

# indonesia factsheet figure 3
indonesia_fs_fig3 <- indonesia_fs_fig3_dataset %>%
  ggplot() + 
  geom_col(mapping = aes(x = reorder(cause_of_death, llpp_who_2022), y = llpp_who_2022, fill = reorder(lyl_bucket, order_lyl_bucket)), width = 0.5, color = "black") +
  labs(x = "Threats to life expectancy", y = "Life Years Lost", fill = "Life years lost") +
  coord_flip() + 
  ggthemes::theme_tufte() +
  theme(legend.position = "bottom",
        axis.text = element_text(size = 14),
        axis.title.y = element_text(size = 16, margin = margin(r = 0.6, unit = "cm")),
        axis.title.x = element_text(size = 16, margin = margin(t = 0.6, b = 0.6, unit = "cm")),
        plot.caption = element_text(hjust = 0, size = 8, margin = margin(t = 0.8, unit = "cm"), face = "italic"),
        plot.title = element_text(hjust = 0.5, size = 20, margin = margin(b = 0.8, unit = "cm")),
        plot.subtitle = element_text(hjust = 0.5, size = 10, margin = margin(b = 0.8, unit = "cm"), face = "italic"),
        legend.box.background = element_rect(color = "black"),
        plot.background = element_rect(color = "white"),
        axis.line = element_line(), 
        legend.text = element_text(size = 11), 
        legend.title = element_text(size = 14),
        panel.grid.major.y = element_blank()) +
  scale_y_continuous(breaks = seq(0, 7, 0.5)) +
  # scale_x_discrete(limits = cause_of_death_ordered[seq(1, length(cause_of_death_ordered), by = 2)]) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  guides(fill = guide_legend(nrow = 1))

# figure 4 ---------

# indonesia factsheet figure 4 dataset
indonesia_fs_fig4_dataset <- gadm2_aqli_2022 %>%
  filter(country == "Indonesia") %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2022_weighted, names_to = "years",
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))),
         region = "National Average") %>%
  select(years, region, pop_weighted_avg_pm2.5)

# indonesia factsheet figure 4
indonesia_fs_fig4 <- indonesia_fs_fig4_dataset %>%
  ggplot() +
  geom_line(mapping = aes(x = as.integer(years), 
                          y = as.double(pop_weighted_avg_pm2.5)), 
            lwd = 1.1, color = "#82b5d5") +
  geom_hline(mapping = aes(yintercept = 5), lwd = 0.8, linetype = "dotted") +
  geom_hline(mapping = aes(yintercept = 15), lwd = 0.8, linetype = "dotted") + 
  scale_y_continuous(breaks = seq(0, 100, 5), limits = c(0, 30)) +
  scale_x_continuous(breaks = c(seq(1998, 2019, 3), 2022))  +
  ggthemes::theme_tufte() +
  labs(x = "Year", 
       y = expression("Annual Average" ~ PM[2.5] ~ "Concentration (in µg/m³)")) +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 11),
        legend.title = element_blank(),
        axis.title.y = element_text(size = 13, margin = margin(r = 0.6, unit = "cm")), 
        axis.title.x = element_text(size = 13, margin = margin(t = 0.6, b = 0.6, unit = "cm")), 
        axis.line = element_line(), 
        legend.box.background = element_rect(color = "black"),
        plot.title = element_text(hjust = 0.5, size = 16, margin = margin(b = 0.7, unit = "cm")), 
        plot.subtitle = element_text(hjust = 0.5, size = 8, face = "italic"), 
        plot.caption = element_text(size = 7, margin = margin(t = 0.8, unit = "cm"), hjust = 0, face = "italic"),
        axis.text = element_text(size = 12), 
        plot.background = element_rect(color = "white"), 
        axis.ticks = element_blank()) +
  geom_text(x = 2001, y = 5.6, label = expression("WHO" ~ PM[2.5] ~ "Guideline (last updated: 2022): 5 µg/m³"), size = 5) +
  geom_text(x = 2006.6, y = 15.6, label = expression("Indonesia National" ~ PM[2.5] ~ "Standard: 15 µg/m³"), size = 5)

# appendix table ---------

# indonesia factsheet appendix table 
indonesia_fs_appendix_table <- gadm2_aqli_2022 %>%
  filter(country == "Indonesia") %>%
  mutate(pm2022 = round(pm2022, 1),
         le_gain_red_to_who = round((pm2022 - who_guideline)*le_constant, 1),
         le_gain_red_to_who = ifelse(le_gain_red_to_who < 0, 0, le_gain_red_to_who),
         le_gain_red_to_nat = round((pm2022 - natstandard)*le_constant, 1),
         le_gain_red_to_nat = ifelse(le_gain_red_to_nat < 0, 0, le_gain_red_to_nat),
         le_gain_red_by_30_percent = round((pm2022*0.3)*le_constant, 1), 
         pop_millions = round(population/1000000, 3)) %>%
  select(name_2, pop_millions, pm2022, le_gain_red_to_who, le_gain_red_to_nat,
         le_gain_red_by_30_percent) %>%
  ungroup() %>%
  slice_max(pop_millions, n = 25) %>%
  mutate(pop_millions = round(pop_millions, 1)) %>%
  rename(`Regency/City` = name_2, 
         `Population (millions)` = pop_millions, 
         `Annual Average 2022 PM2.5 Concentration (µg/m³)` = pm2022,
         `Life Expectancy Gains from reducing PM2.5 from 2022 concentration to WHO PM2.5 guideline of 5 µg/m` = le_gain_red_to_who, 
         `Life Expectancy Gains from reducing PM2.5 from 2022 concentration to National PM2.5 guideline of 15 µg/m³` = le_gain_red_to_nat,
         `Life Expectancy Gains from reducing PM2.5 from 2022 concentration by 30 percent` = le_gain_red_by_30_percent) %>%

```
##Thailand factsheet
```{r}
# read and filter AQLI data
ne_thai <- c("Amnat Charoen", "Bueng Kan", "Buri Ram", "Chaiyaphum", "Kalasin", "Khon Kaen", "Loei", 
             "Maha Sarakham", "Mukdahan", "Nakhon Phanom", "Nakhon Ratchasima", "Nong Bua Lam Phu", 
             "Nong Khai", "Roi Et", "Sakon Nakhon", "Si Sa Ket", "Surin", "Ubon Ratchathani", 
             "Udon Thani", "Yasothon")

n_thai <- c ("Chiang Mai", "Chiang Rai", "Lampang", "Lamphun", "Mae Hong Son", "Nan", "Phayao", "Phrae", 
             "Uttaradit", "Tak", "Kamphaeng Phet", "Phetchabun", "Phichit", "Phitsanulok", "Sukhothai",
             "Nakhon Sawan", "Uthai Thani")

c_thai <- c("Ang Thong", "Bangkok Metropolis", "Chai Nat", "Lop Buri", "Nakhon Pathom", "Nonthaburi", "Pathum Thani", 
            "Phra Nakhon Si Ayutthaya", "Samut Prakan", "Samut Sakhon", "Samut Songkhram", "Saraburi", 
            "Sing Buri", "Suphan Buri", "Nakhon Nayok", "Chachoengsao", "Chanthaburi", "Chon Buri", 
            "Prachin Buri", "Rayong", "Sa Kaeo", "Trat", "Kanchanaburi", "Ratchaburi", "Phetchaburi", "Prachuap Khiri Khan")

s_thai <- c("Chumphon", "Nakhon Si Thammarat", "Narathiwat", "Pattani", "Phatthalung", "Songkhla", "Surat Thani", 
            "Yala", "Krabi", "Phangnga", "Phuket", "Ranong", "Satun", "Trang")
  
thai_aqli_2022 <- gadm2_aqli_2022 %>%
  filter(country == "Thailand") %>%
  mutate(region = case_when(
    name_1 %in% ne_thai ~ "Northeastern",
    name_1 %in% n_thai ~ "Northern",
    name_1 %in% c_thai ~ "Central",
    name_1 %in% s_thai ~ "Southern"))

# figure 1 ---------

# thailand fs fig 1 data
thailand_fs_fig1_dataset <- thai_aqli_2022 %>%
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  select('country', 'name_1', 'name_2', 'population', 'pm2022', 'llpp_who_2022', 'geometry') %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# thailand fs figure 1
thailand_fs_fig1 <- thailand_fs_fig1_dataset %>%
  ggplot() +
  geom_sf(mapping = aes(fill = reorder(lyl_bucket, order_lyl_bucket)), color = "aliceblue", lwd = 0.05) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 == "Thailand"), color = "azure4", fill = "transparent", lwd = 0.15) +
  geom_sf(data = gadm0_aqli_2022_shp %>% filter(name0 == "Thailand"), color = "cornsilk4", fill = "transparent", lwd = 0.5) +
  ggthemes::theme_map() + 
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  ggthemes::theme_map() +
  labs(fill = "Potential gain in life expectancy (Years)") + 
  theme(legend.position = "bottom", 
        legend.justification = c(0.5, 3), 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15), 
        plot.title = element_text(hjust = 0.5, size = 15), 
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 7), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"), 
        legend.key = element_rect(color = "black"), 
        legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal") +
  guides(fill = guide_legend(nrow = 1))

# figure 2 ---------

# thailand fs fig 2 data
thailand_fs_fig2_dataset <- thai_aqli_2022 %>%
  select('country', 'name_1', 'name_2', 'population', 'pm2022', 'llpp_who_2022') %>%
  group_by(name_1) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         pm2022_pop_weighted = pop_weights*pm2022,
         llpp_who_2022_pop_weighted = pop_weights*llpp_who_2022) %>%
  summarise(tot_pop = sum(population, na.rm = TRUE), 
            avg_pm2.5_2022 = sum(pm2022_pop_weighted, na.rm = TRUE),
            le_gain = (avg_pm2.5_2022 - who_guideline)*le_constant,
            llpp_who_2022 = sum(llpp_who_2022_pop_weighted, na.rm = TRUE),
            le_gain = ifelse(le_gain < 0 , 0, le_gain)) %>%
  slice_max(tot_pop, n = 10) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022")

# thailand fs figure 2
thailand_fs_fig2 <- thailand_fs_fig2_dataset %>%
  ggplot() +
  geom_col(mapping = aes(x = reorder(name_1, llpp_who_2022), y = llpp_who_2022, fill = lyl_bucket), width = 0.5) +
  labs(x = "Province", y = "Potential Gain in Life Expectancy (Years)", fill = "Potential gain in life expectancy (Years)") +
  scale_y_continuous(breaks = seq(0, 3, 1), limits = c(0, 3)) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  coord_flip() + 
  ggthemes::theme_tufte() +
  theme(legend.position = "bottom", 
        plot.title = element_text(hjust = 0.5, size = 16), 
        plot.subtitle = element_text(hjust =  0.5, size = 10, face = "italic", margin = margin(b = 0.8, unit = "cm")), 
        plot.caption = element_text(size = 8, hjust = 0, face = "italic"),
        legend.box.background = element_rect(color = "black"),
        plot.background = element_rect(color = "white"),
        axis.line = element_line(), 
        axis.text = element_text(size = 11), 
        axis.title = element_text(size = 13), 
        axis.title.y = element_text(margin = margin(r = 0.7, unit = "cm")), 
        axis.title.x = element_text(margin = margin(t = 0.6, b = 0.6, unit = "cm")), 
        axis.ticks = element_blank()) 

# figure 3 --------

# read and filter gbd results for thailand
gbd_results_thailand <- gbd_results_master_2022 %>%
  filter(country == "Thailand")

# filtering out those causes of death that are sort of* covered under PM2.5 in some broad way
colnames(gbd_results_thailand)[3] <- c("llpp_who_2022")

# thailand fs fig 3 data
thailand_fs_fig3_dataset <- gbd_results_thailand %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  slice_max(llpp_who_2022, n = 10)

# thailand factsheet figure 3
thailand_fs_fig3 <- thailand_fs_fig3_dataset %>%
  ggplot() + 
  geom_col(mapping = aes(x = reorder(cause_of_death, llpp_who_2022), y = llpp_who_2022, fill = reorder(lyl_bucket, order_lyl_bucket)), width = 0.5, color = "black") +
  labs(x = "Threats to life expectancy", y = "Life Years Lost", fill = "Life years lost") +
  coord_flip() + 
  ggthemes::theme_tufte() +
  theme(legend.position = "bottom",
        axis.text = element_text(size = 14),
        axis.title.y = element_text(size = 16, margin = margin(r = 0.6, unit = "cm")),
        axis.title.x = element_text(size = 16, margin = margin(t = 0.6, b = 0.6, unit = "cm")),
        plot.caption = element_text(hjust = 0, size = 8, margin = margin(t = 0.8, unit = "cm"), face = "italic"),
        plot.title = element_text(hjust = 0.5, size = 20, margin = margin(b = 0.8, unit = "cm")),
        plot.subtitle = element_text(hjust = 0.5, size = 10, margin = margin(b = 0.8, unit = "cm"), face = "italic"),
        legend.box.background = element_rect(color = "black"),
        plot.background = element_rect(color = "white"),
        axis.line = element_line(), 
        legend.text = element_text(size = 11), 
        legend.title = element_text(size = 14),
        panel.grid.major.y = element_blank()) +
  scale_y_continuous(breaks = seq(0, 6, 0.5)) +
  # scale_x_discrete(limits = cause_of_death_ordered[seq(1, length(cause_of_death_ordered), by = 2)]) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  guides(fill = guide_legend(nrow = 1))

# figure 4 ---------

# thailand factsheet figure 4 dataset
thailand_fs_fig4_regions <- thai_aqli_2022 %>%
  group_by(region) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2022_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+")))) %>%
  select(years, region, pop_weighted_avg_pm2.5)

thailand_fs_fig4_nat <- thai_aqli_2022 %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2022_weighted, names_to = "years",
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))),
         region = "National Average") %>%
  select(years, region, pop_weighted_avg_pm2.5)

thailand_fs_fig4_dataset <- rbind(thailand_fs_fig4_regions, thailand_fs_fig4_nat)

thailand_fs_fig4_dataset$region = factor(thailand_fs_fig4_dataset$region, levels = c('National Average', 'Central', 'Northeastern', 'Northern', 'Southern'))

# thailand factsheet figure 4
thailand_fs_fig4 <- thailand_fs_fig4_dataset %>%
  ggplot() +
  geom_line(mapping = aes(x = as.integer(years), 
                          y = as.double(pop_weighted_avg_pm2.5),
                          colour = region, linetype = region), lwd = 1.1) +
  geom_hline(mapping = aes(yintercept = 5), lwd = 0.8, linetype = "dotted") +
  scale_y_continuous(breaks = seq(0, 100, 5), limits = c(0, 35)) +
  scale_x_continuous(breaks = c(seq(1998, 2019, 3), 2022))  +
  scale_color_manual(values = c("National Average" = "#7197be", "Northeastern" = "#7197be", "Northern" = "#5f7aa5", "Central" = "#7197be", "Southern" = "#CBE8F3")) +
  scale_linetype_manual(values = c("National Average" = "solid", "Northeastern" = "dashed", "Northern" = "dashed", "Central" = "dashed", "Southern" = "dashed")) +
  ggthemes::theme_tufte() +
  labs(x = "Year", 
       y = expression("Annual Average" ~ PM[2.5] ~ "Concentration (in µg/m³)")) +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 11),
        legend.title = element_blank(),
        axis.title.y = element_text(size = 13, margin = margin(r = 0.6, unit = "cm")), 
        axis.title.x = element_text(size = 13, margin = margin(t = 0.6, b = 0.6, unit = "cm")), 
        axis.line = element_line(), 
        legend.box.background = element_rect(color = "black"),
        plot.title = element_text(hjust = 0.5, size = 16, margin = margin(b = 0.7, unit = "cm")), 
        plot.subtitle = element_text(hjust = 0.5, size = 8, face = "italic"), 
        plot.caption = element_text(size = 7, margin = margin(t = 0.8, unit = "cm"), hjust = 0, face = "italic"),
        axis.text = element_text(size = 12), 
        plot.background = element_rect(color = "white"), 
        axis.ticks = element_blank()) +
  geom_text(x = 2001.15, y = 5.8, label = expression("WHO" ~ PM[2.5] ~ "Guideline (last updated: 2022): 5 µg/m³"), size = 5)
  
# appendix table

# thailand factsheet appendix table 
thailand_fs_appendix_table <- thai_aqli_2022 %>%
  mutate(pm2022 = round(pm2022, 1),
         le_gain_red_to_who = round((pm2022 - who_guideline)*le_constant, 1),
         le_gain_red_to_who = ifelse(le_gain_red_to_who < 0, 0, le_gain_red_to_who),
         le_gain_red_to_nat = round((pm2022 - natstandard)*le_constant, 1),
         le_gain_red_to_nat = ifelse(le_gain_red_to_nat < 0, 0, le_gain_red_to_nat),
         le_gain_red_by_30_percent = round((pm2022*0.3)*le_constant, 1), 
         pop_millions = round(population/100000, 3)) %>%
  select(name_2, pop_millions, pm2022, le_gain_red_to_who, le_gain_red_to_nat,
         le_gain_red_by_30_percent) %>%
  ungroup() %>%
  slice_max(pop_millions, n = 25) %>%
  mutate(pop_millions = round(pop_millions, 1)) %>%
  rename(`District` = name_2, 
         `Population (Hundred thousands)` = pop_millions, 
         `Annual Average 2022 PM2.5 Concentration (µg/m³)` = pm2022,
         `Life Expectancy Gains from reducing PM2.5 from 2022 concentration to WHO PM2.5 guideline of 5 µg/m³` = le_gain_red_to_who, 
         `Life Expectancy Gains from reducing PM2.5 from 2022 concentration to National PM2.5 standard of 15 µg/m³` = le_gain_red_to_nat,
         `Life Expectancy Gains from reducing PM2.5 from 2022 concentration by 30 percent` = le_gain_red_by_30_percent)%>%


```
## Colombia
```{r}

# Fig 1:  Potential gain in Life Expectancy from permanently reducing PM2.5 ------ 
# from 2022 levels to the WHO PM2.5 guideline.
# colombia fs fig 1 data
colombia_fs_fig1_dataset <- gadm2_aqli_2022 %>%
  mutate(llpp_who_2022 = if_else(pm2022 <= whostandard, 0, llpp_who_2022)) %>%
  filter(country == "Colombia", !is.na(llpp_who_2022)) %>%
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  select('country', 'name_1', 'name_2', 'population', 'pm2022', 'llpp_who_2022', 'geometry') %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# colombia fs figure 1
colombia_fs_fig1 <- colombia_fs_fig1_dataset %>%
  ggplot() +
  geom_sf(mapping = aes(fill = reorder(lyl_bucket, order_lyl_bucket)), color = "aliceblue", lwd = 0.05) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 == "Colombia"), color = "azure4", fill = "transparent", lwd = 0.15) +
  geom_sf(data = gadm0_aqli_2022_shp %>% filter(name0 == "Colombia"), color = "cornsilk4", fill = "transparent", lwd = 0.5) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 == "Colombia", name1 %in% c("Amazonas", "Guaviare", "Vaupés")), 
          color = "black", fill = "transparent", lwd = 0.5) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  ggthemes::theme_map() +
  labs(fill = "Potential gain in life expectancy (Years)") + 
  theme(legend.position = "bottom", 
        legend.justification = "center", 
        legend.background = element_rect(color = "black"), 
        legend.text = element_text(size = 20, colour = "#222222"),
        legend.title = element_text(size = 20, colour = "#222222"),
        legend.box.margin = margin(b = 1, unit = "cm"), 
        legend.key = element_rect(color = "black"), 
        legend.box.spacing = unit(0, "cm"), 
        legend.direction = "horizontal",
        plot.title = element_text(hjust = 0.5, size = 15), 
        plot.subtitle = element_text(hjust = 0.5, size = 7), 
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic")) +
  guides(fill = guide_legend(nrow = 1))


# Fig 2: Potential gain in life expectancy in states in colombia ------

# colombia fs fig 2 data
colombia_fs_fig2_dataset <- gadm2_aqli_2022 %>%
  filter(country == "Colombia") %>%
  select('country', 'name_1', 'name_2', 'population', 'pm2022', 'llpp_who_2022') %>%
  group_by(name_1) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         pm2022_pop_weighted = pop_weights*pm2022,
         llpp_who_2022_pop_weighted = pop_weights*llpp_who_2022) %>%
  summarise(tot_pop = sum(population, na.rm = TRUE), 
            avg_pm2.5_2022 = sum(pm2022_pop_weighted, na.rm = TRUE),
            le_gain = (avg_pm2.5_2022 - who_guideline)*le_constant,
            llpp_who_2022 = sum(llpp_who_2022_pop_weighted, na.rm = TRUE),
            le_gain = ifelse(le_gain < 0 , 0, le_gain)) %>%
  slice_max(tot_pop, n = 10) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022")

# colombia fs figure 2
colombia_fs_fig2 <- colombia_fs_fig2_dataset %>%
  ggplot() +
  geom_col(mapping = aes(x = reorder(name_1, llpp_who_2022), y = llpp_who_2022, fill = lyl_bucket), width = 0.5) +
  labs(x = "Municipality", y = "Potential Gain in Life Expectancy (Years)", fill = "Potential gain in life expectancy (Years)") +
  scale_y_continuous(breaks = seq(0, 6, 1), limits = c(0, 2)) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  coord_flip() + 
  ggthemes::theme_tufte() +
  theme(legend.position = "bottom", 
        legend.text = element_text(size = 20, colour = "#222222"),
        legend.title = element_text(size = 20, colour = "#222222"),
        legend.box.background = element_rect(color = "black"),
        # plot.title = element_text(hjust = 0.5, size = 16), 
        # plot.subtitle = element_text(hjust =  0.5, size = 10, face = "italic", margin = margin(b = 0.8, unit = "cm")), 
        # plot.caption = element_text(size = 8, hjust = 0, face = "italic"),
        plot.background = element_rect(color = "white"),
        axis.line = element_line(), 
        axis.text = element_text(size = 20, colour = "#222222"), 
        axis.title.y = element_text(size = 24, colour = "#222222", margin = margin(r = 0.7, unit = "cm")), 
        axis.title.x = element_text(size = 24, colour = "#222222", margin = margin(t = 0.6, b = 0.6, unit = "cm")), 
        axis.ticks = element_blank()) 


# Fig 3: GBD ------
# read and filter gbd results for colombia
diseases_list <- c("Tobacco",
                   "Child and maternal malnutrition",
                   "Self-harm and interpersonal violence",
                   "PM2.5 relative to WHO guideline")

colombia_fs_fig3_dataset <- gbd_results_master_2022  %>%
  filter(country == "Colombia", cause_of_death %in% diseases_list)

# filtering out those causes of death that are sort of* covered under PM2.5 in some broad way
colnames(colombia_fs_fig3_dataset)[3] <- c("llpp_who_2022")

colombia_fs_fig3_dataset <- colombia_fs_fig3_dataset %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022")

# colombia_fs_fig3_dataset <- colombia_fs_fig3_dataset %>%
#   add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
#   slice_max(llpp_who_2022, n = 5)

# colombia factsheet figure 3
colombia_fs_fig3 <- colombia_fs_fig3_dataset %>%
  ggplot() + 
  geom_col(mapping = aes(x = reorder(cause_of_death, llpp_who_2022), y = llpp_who_2022, fill = reorder(lyl_bucket, order_lyl_bucket)), width = 0.5, color = "black") +
  labs(x = "Threats to life expectancy", y = "Life Years Lost", fill = "Life years lost") +
  coord_flip() + 
  ggthemes::theme_tufte() +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 20, colour = "#222222"),
        legend.title = element_text(size = 20, colour = "#222222"),
        legend.box.background = element_rect(color = "black"),
        axis.text = element_text(size = 20, colour = "#222222"), 
        axis.title.y = element_text(size = 24, colour = "#222222", margin = margin(r = 0.6, unit = "cm")),
        axis.title.x = element_text(size = 24, colour = "#222222", margin = margin(t = 0.6, b = 0.6, unit = "cm")),
        axis.line = element_line(), 
        plot.caption = element_text(hjust = 0, size = 8, margin = margin(t = 0.8, unit = "cm"), face = "italic"),
        plot.title = element_text(hjust = 0.5, size = 20, margin = margin(b = 0.8, unit = "cm")),
        plot.subtitle = element_text(hjust = 0.5, size = 10, margin = margin(b = 0.8, unit = "cm"), face = "italic"),
        plot.background = element_rect(color = "white"),
        panel.grid.major.y = element_blank()) +
  scale_y_continuous(breaks = seq(0, 6, 0.5)) +
  # scale_x_discrete(limits = cause_of_death_ordered[seq(1, length(cause_of_death_ordered), by = 2)]) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
  guides(fill = guide_legend(nrow = 1)) 


# Fig 4: Average PM2.5 concentration in colombia from 1998 to 2022 ------
# colombia factsheet figure 4 dataset
colombia_fs_fig4_dataset <- gadm2_aqli_2022 %>%
  mutate(llpp_who_2022 = if_else(pm2022 <= whostandard, 0, llpp_who_2022)) %>%
  filter(country == "Colombia", !is.na(llpp_who_2022)) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2022_weighted, names_to = "years",
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))),
         region = "National Average") %>%
  select(years, region, pop_weighted_avg_pm2.5)

# colombia factsheet figure 4
colombia_fs_fig4 <- colombia_fs_fig4_dataset %>%
  ggplot() +
  geom_line(mapping = aes(x = as.integer(years), 
                          y = as.double(pop_weighted_avg_pm2.5)), 
            lwd = 1.1, color = "#3c456f") +
  # geom_smooth(aes(x = as.integer(years), y = as.double(pop_weighted_avg_pm2.5)),
  #             lwd = 0.5, linetype = "dashed", se = FALSE) +
  geom_hline(mapping = aes(yintercept = 5), lwd = 0.8, linetype = "dotted") +
  geom_hline(mapping = aes(yintercept = 20), lwd = 0.8, linetype = "dotted") +
  scale_y_continuous(breaks = seq(0, 100, 5), limits = c(0, 60)) +
  scale_x_continuous(breaks = c(seq(1998, 2019, 3), 2022))  +
  ggthemes::theme_tufte() +
  labs(x = "Year", 
       y = expression("Annual Average" ~ PM[2.5] ~ "Concentration (in µg/m³)")) +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 20, colour = "#222222"),
        legend.title = element_text(size = 20, colour = "#222222"),
        legend.box.background = element_rect(color = "black"),
        axis.text = element_text(size = 20, colour = "#222222"), 
        axis.title.y = element_text(size = 24, colour = "#222222", margin = margin(r = 0.6, unit = "cm")), 
        axis.title.x = element_text(size = 24, colour = "#222222", margin = margin(t = 0.6, b = 0.6, unit = "cm")), 
        axis.line = element_line(), 
        axis.ticks = element_blank(), 
        plot.title = element_text(hjust = 0.5, size = 16, margin = margin(b = 0.7, unit = "cm")), 
        plot.subtitle = element_text(hjust = 0.5, size = 8, face = "italic"), 
        plot.caption = element_text(size = 7, margin = margin(t = 0.8, unit = "cm"), hjust = 0, face = "italic"),
        plot.background = element_rect(color = "white")) +
  geom_text(x = 2003.8, y = 6.8, label = expression("WHO" ~ PM[2.5] ~ "Guideline (last updated: 2021): 5 µg/m³"), size = 7) +
  geom_text(x = 2001.8, y = 21.6, label = expression("National" ~ PM[2.5] ~ "Standard: 20 µg/m³"), size = 7)


# appendix table ----------

# colombia factsheet appendix table 
colombia_fs_appendix_table <- gadm2_aqli_2022 %>%
  filter(country == "Colombia") %>%
  mutate(pm2022 = round(pm2022, 1),
         le_gain_red_to_who = round((pm2022 - whostandard)*le_constant, 1),
         le_gain_red_to_who = ifelse(le_gain_red_to_who < 0, 0, le_gain_red_to_who),
         le_gain_red_to_natstd = round((pm2022 - natstandard)*le_constant, 1), 
         le_gain_red_to_natstd = ifelse(le_gain_red_to_natstd < 0, 0, le_gain_red_to_natstd),
         le_gain_red_by_30_percent = round((pm2022*0.3)*le_constant, 1), 
         pop_millions = round(population/1000000, 3)) %>%
  select(name_2, pop_millions, pm2022, le_gain_red_to_who, 
         le_gain_red_to_natstd, le_gain_red_by_30_percent) %>%
  ungroup() %>%
  slice_max(pop_millions, n = 25) %>%
  # mutate(pop_millions = round(pop_millions, 1)) %>%
  rename(`Municipality` = name_2, 
         `Population (Millions)` = pop_millions, 
         `Annual Average 2022 PM2.5 Concentration (µg/m³)` = pm2022,
         `Life Expectancy Gains from reducing PM2.5 from 2022 concentration to WHO PM2.5 guideline of 5 µg/m³` = le_gain_red_to_who, 
         `Life Expectancy Gains from reducing PM2.5 from 2022 concentration to National PM2.5 standard of 20 µg/m³` = le_gain_red_to_natstd,
         `Life Expectancy Gains from reducing PM2.5 from 2022 concentration by 30 percent` = le_gain_red_by_30_percent) 

```

##USA
```{r USA_fs_2024}

#Figure 1: Change in life expectancy due to change in PM2.5 concentration in 235 counties in the United States between 1970 and 2022.
#Only three counties (in orange) are losing life years due to particulate pollution increasing in 2022 compared to 1970

# percent reduction in pollution since 1970
caa_pct_reduction <- 0.67

#> use as is or source from our folder (or use gadm1_aqli_2022 shape file for the US)
# US state level shapefile
us_states_shp <- gadm1_aqli_2022_shp %>%
  filter(!(name1 %in% c("Alaska", "Hawaii")))


# this is the county level shape file. (Filter this for USA)
county_shp <- gadm2_aqli_2022_shp %>%
  filter(name0 == "United States")


# use county pm25 for aqli csv file
county_data <- read_csv("~/Desktop/county_pm25_foraqli_stats.csv")

# country level files
country <- read_csv("~/Desktop/CleanAirAct/aqli_gadm0_2022.csv")


# Change in life expectancy map (change geo_name to name_2) and remove any counties that belong to Hawaii or Alaska
county_shp <- inner_join(county_shp, county_data, by = c("obidgadm2"="objectid_gadm2")) %>%
	filter(!(name2 %in% c("Anchorage", "Honolulu")))



# us figure 1
us_1970_2022_map_data <- county_shp %>%
  mutate(lifeyears_saved_reverse = round((pm2022 - pm1970)*0.098, 2)) %>%
  add_aqli_color_scale_buckets("lyldiff", "lifeyears_saved_reverse") %>%
  select(-geometry, geometry)

us_fs_fig1 <- us_1970_2022_map_data %>%
  st_as_sf() %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyldiff_bucket, order_lyldiff_bucket)), color = "aliceblue", lwd = 0.05) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 == "United States", name1 %notin% c("Alaska", "Hawaii")), color = "azure4", fill = "transparent", lwd = 0.5) +
  ggthemes::theme_map() +
  scale_fill_manual(values = c("< -2" = "#4575b4",
                               "-2 to (< -0.5)" = "#74add1",
                               "-0.5 to (< -0.1)" = "#abd9e9",
                               "-0.1 to (< 0)" = "#e0f3f8",
                               "0 to (< 0.1)" = "#fee090",
                               "0.1 to (< 0.5)" = "#fdae61",
                               "0.5 to (< 2)" = "#f46d43",
                               ">= 2" = "#d73027")) +
  ggthemes::theme_map() +
  labs(fill = "Change in life expectancy between 1970 and 2022 (Years; blue values indicate improvement)", title = "") +
  theme(legend.position = "bottom",
        legend.justification = c(0.5, 3),
        legend.background = element_rect(color = "black"),
        legend.text = element_text(size = 15, color="#222222"),
        legend.title = element_text(size = 15, color="#222222"),
        plot.title = element_text(hjust = 0.5, size = 15),
        # legend.key = element_rect(color = "black"),
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 7),
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"),
        legend.key = element_rect(color = "black"),
        legend.box.spacing = unit(2, "cm"),
        legend.direction = "horizontal",
        plot.background = element_rect(fill = "white", color = "white")) +
  guides(fill = guide_legend(nrow = 1))


#Figure 2: Potential gain in life expectancy from permanently reducing PM2.5 from 2022 concentration to the WHO guideline ----------------------------------

# US figure2 dataset
us_fs_fig2_data <- gadm2_aqli_2022 %>%
  filter(country == "United States", name_1 %notin% c("Alaska", "Hawaii")) %>%
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  select(-geometry, geometry) %>%
  st_as_sf()



# US figure 2
us_fs_fig2 <- us_fs_fig2_data %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), color = "aliceblue", lwd = 0.05) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 == "United States", name1 %notin% c("Alaska", "Hawaii")), color = "azure4", fill = "transparent", lwd = 0.5) +
  ggthemes::theme_map() +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff",
                               "0.1 to < 0.5" = "#ffeda0",
                               "0.5 to < 1" = "#fed976",
                               "1 to < 2" = "#feb24c",
                               "2 to < 3" = "#fd8d3c",
                               "3 to < 4" = "#fc4e2a",
                               "4 to < 5" = "#e31a1c",
                               "5 to < 6" = "#bd0026",
                               ">= 6" = "#800026")) +
  ggthemes::theme_map() +
  labs(fill = "Potetial gain in life expectancy (Years)  ", title = "") +
  theme(legend.position = "bottom",
        legend.justification = c(0.5, 3),
        legend.background = element_rect(color = "black"),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15),
        plot.title = element_text(hjust = 0.5, size = 15),
        # legend.key = element_rect(color = "black"),
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 7),
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"),
        legend.key = element_rect(color = "black"),
        legend.box.spacing = unit(0, "cm"),
        legend.direction = "horizontal",
        plot.background = element_rect(fill = "white", color = "white")) +
  guides(fill = guide_legend(nrow = 1))

#Figure 3:  Change in life expectancy due to change in PM2.5 concentration in some of the most populous US states between 1970 and 2022-----------------

# calculate the x most populous states
x_most_populous_us_states <- gadm2_aqli_2022 %>%
  filter(country == "United States") %>%
  gadm_level_summary(c("country", "name_1"), c(2022), 10) %>%
  slice_max(population, n = 11) %>%
  select(name_1) %>%
  unlist() %>%
  as.vector()

# calculate pollution in the above states for the year 2022
us_fs_fig3_dataset_part1 <- gadm2_aqli_2022 %>%
  filter(country == "United States") %>%
  gadm_level_summary(c("country", "name_1"), c(2022), 10) %>%
  filter(name_1 %in% x_most_populous_us_states) %>%
  select(country, name_1, pm2022)

# calculate pollution in the above states for the year 1970
us_fs_fig3_dataset_part2 <- us_1970_calc_results_cleaned %>%
  #gadm_level_summary(c("country", "name_1"), c(1970), 10) %>%
  filter(name_1 %in% x_most_populous_us_states) %>%
  select(country, name_1, pm1970)

# final data set for figure 3
us_fs_fig3_final_data <- us_fs_fig3_dataset_part1 %>%
  left_join(us_fs_fig3_dataset_part2, by = c("country", "name_1")) %>%
  mutate(lyg_1970_2022= round((pm1970 - pm2022)*0.098, 2))
# %>%
#   add_aqli_color_scale_buckets(scale_type = "lyg_1970_2022")
mean_lyg <- us_fs_fig3_final_data %>%
  group_by(name_1) %>%
  summarize(mean_lyg = mean(lyg_1970_2022, na.rm = TRUE))

mean_lyg <- mean_lyg %>%
  mutate(lyg_category = cut(mean_lyg, breaks = c(0, 2, Inf),
                            labels = c("0.5 to (< 2)", ">= 2"), right = FALSE))
# figure 3
us_fs_fig3 <- mean_lyg %>%
  filter(name_1 != "Georgia") %>%
  ggplot() +
  geom_col(mapping = aes(x = forcats::fct_reorder(!!as.symbol("name_1"), !!as.symbol("mean_lyg")), y = !!as.symbol("mean_lyg"), fill=lyg_category)) +
  labs(x = "State", y = "Life years gained", title = "", subtitle = "", caption = "", fill = "Life years gained") +
  themes_aqli_base +
  scale_fill_manual(values = c("0.5 to (< 2)" = "#74add1",
                               ">= 2" = "#4575b4")) +
  coord_flip() +
  theme(legend.position = "bottom",
        axis.text = element_text(size = 20, color="#222222"),
        axis.title.y = element_text(size = 24, margin = margin(r = 0.6, unit = "cm"), color="#222222"),
        axis.title.x = element_text(size = 24, margin = margin(t = 0.6, b = 0.6, unit = "cm"), color="#222222"),
        plot.caption = element_text(hjust = 0, size = 8, margin = margin(t = 0.8, unit = "cm")),
        plot.title = element_text(hjust = 0.5, size = 20, margin = margin(b = 0.8, unit = "cm")),
        plot.subtitle = element_text(hjust = 0.5, size = 10, margin = margin(b = 0.8, unit = "cm")),
        legend.box.background = element_rect(color = "black"),
        axis.line = element_line(),
        legend.text = element_text(size = 20, color="#222222"),
        legend.title = element_text(size = 20, color="#222222"),
        panel.grid.major.y = element_blank(),
        plot.background = element_rect(fill = "white", color = "white"),axis.ticks.y = element_blank()) +
  scale_y_continuous(breaks = seq(0, 3, 0.5)) +
  guides(fill = guide_legend(nrow = 1))





```


##Qatar
```{r Qatar_fs_2024}

#Figure 1: Potential gain in life expectancy from permanently reducing PM2.5 from 2022 concentration to the WHO guideline

# Qatar fs fig 1 data
Qatar_fs_fig1_dataset <- gadm2_aqli_2022 %>%
  filter(country == "Qatar") %>%
  left_join(gadm2_aqli_2022_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  select('country', 'name_1', 'name_2', 'population', 'pm2022', 'llpp_who_2022', 'geometry') %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  select(-geometry, geometry) %>%
  st_as_sf()

# Qatar fs figure 1
Qatar_fs_fig1 <- Qatar_fs_fig1_dataset %>%
  ggplot() +
  geom_sf(mapping = aes(fill = reorder(lyl_bucket, order_lyl_bucket)), color = "aliceblue", lwd = 0.05) +
  geom_sf(data = gadm1_aqli_2022_shp %>% filter(name0 == "Qatar"), color = "azure4", fill = "transparent", lwd = 0.15) +
  geom_sf(data = gadm0_aqli_2022_shp %>% filter(name0 == "Qatar"), color = "cornsilk4", fill = "transparent", lwd = 0.5) +
  ggthemes::theme_map() +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff",
                               "0.1 to < 0.5" = "#ffeda0",
                               "0.5 to < 1" = "#fed976",
                               "1 to < 2" = "#feb24c",
                               "2 to < 3" = "#fd8d3c",
                               "3 to < 4" = "#fc4e2a",
                               "4 to < 5" = "#e31a1c",
                               "5 to < 6" = "#bd0026",
                               ">= 6" = "#800026")) +
  ggthemes::theme_map() +
  labs(fill = "Potential gain in life expectancy (Years)") +
  theme(legend.position = "bottom",
        legend.justification = c(0.5, 3),
        legend.background = element_rect(color = "black"),
        legend.text = element_text(size = 24, color="#222222"),
        legend.title = element_text(size = 24, color="#222222"),
        plot.title = element_text(hjust = 0.5, size = 15),
        legend.box.margin = margin(b = 1, unit = "cm"),
        plot.subtitle = element_text(hjust = 0.5, size = 7),
        plot.caption = element_text(hjust = 0.7, size = 9, face = "italic"),
        legend.key = element_rect(color = "black"),
        legend.box.spacing = unit(2, "cm"),
        legend.direction = "horizontal",
        plot.background = element_rect(fill = "white", color = "white")) +
  guides(fill = guide_legend(nrow = 1))

#Figure 2:Top 10 threats to life expectancy in Qatar

# filtering out those causes of death that are sort of* covered under PM2.5 in some broad way
gbd_results_Qatar <- gbd_results_master_2022 %>%
  filter(cause_of_death!= "Cardiovascular diseases")%>%
  filter(cause_of_death!= "Respiratory infections and tuberculosis")%>%
  filter(cause_of_death!= "Chronic respiratory diseases")%>%
  filter(cause_of_death!= "Non-optimal temperature")%>%
  filter(country == "Qatar")

colnames(gbd_results_Qatar)[3] <- c("llpp_who_2022")

Qatar_fs_fig2_dataset <- gbd_results_Qatar %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022") %>%
  slice_max(llpp_who_2022, n = 10)

# Qatar factsheet figure 2
Qatar_fs_fig2 <- Qatar_fs_fig2_dataset %>%
  ggplot() +
  geom_col(mapping = aes(x = reorder(cause_of_death, llpp_who_2022), y = llpp_who_2022, fill = reorder(lyl_bucket, order_lyl_bucket)), width = 0.5, color = "black") +
  labs(x = "Threats to life expectancy", y = "Life Years Lost", fill = "Life years lost") +
  coord_flip() +
  ggthemes::theme_tufte() +
  theme(legend.position = "bottom",
        axis.text = element_text(size = 20, color="#222222"),
        axis.title.y = element_text(size = 24, margin = margin(r = 0.6, unit = "cm"), color="#222222"),
        axis.title.x = element_text(size = 24, margin = margin(t = 0.6, b = 0.6, unit = "cm"), color="#222222"),
        plot.caption = element_text(hjust = 0, size = 8, margin = margin(t = 0.8, unit = "cm"), face = "italic"),
        plot.title = element_text(hjust = 0.5, size = 20, margin = margin(b = 0.8, unit = "cm")),
        plot.subtitle = element_text(hjust = 0.5, size = 10, margin = margin(b = 0.8, unit = "cm"), face = "italic"),
        legend.box.background = element_rect(color = "black"),
        plot.background = element_rect(color = "white"),axis.ticks.y = element_blank(),
        axis.line = element_line(),
        legend.text = element_text(size = 20, color="#222222"),
        legend.title = element_text(size = 20, color="#222222"),
        panel.grid.major.y = element_blank()) +
  scale_y_continuous(breaks = seq(0, 7, 0.5)) +
  # scale_x_discrete(limits = cause_of_death_ordered[seq(1, length(cause_of_death_ordered), by = 2)]) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff",
                               "0.1 to < 0.5" = "#ffeda0",
                               "0.5 to < 1" = "#fed976",
                               "1 to < 2" = "#feb24c",
                               "2 to < 3" = "#fd8d3c",
                               "3 to < 4" = "#fc4e2a",
                               "4 to < 5" = "#e31a1c",
                               "5 to < 6" = "#bd0026",
                               ">= 6" = "#800026")) +
  guides(fill = guide_legend(nrow = 1))

#Figure 3: Potential gain in life expectancy from reducing PM2.5 from 2022 levels to the WHO guideline in provinces of Qatar

# Qatar fs fig 3 data
Qatar_fs_fig3_dataset <- gadm2_aqli_2022 %>%
  filter(country == "Qatar") %>%
  select('country', 'name_1', 'population', 'pm2022', 'llpp_who_2022') %>%
  group_by(name_1) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE),
         pm2022_pop_weighted = pop_weights*pm2022,
         llpp_who_2022_pop_weighted = pop_weights*llpp_who_2022) %>%
  summarise(tot_pop = sum(population, na.rm = TRUE),
            avg_pm2.5_2022 = sum(pm2022_pop_weighted, na.rm = TRUE),
            le_gain = (avg_pm2.5_2022 - who_guideline)*le_constant,
            llpp_who_2022 = sum(llpp_who_2022_pop_weighted, na.rm = TRUE),
            le_gain = ifelse(le_gain < 0 , 0, le_gain)) %>%
  slice_max(tot_pop, n = 10) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2022")

# Qatar fs figure 3
Qatar_fs_fig3 <- Qatar_fs_fig3_dataset %>%
  ggplot() +
  geom_col(mapping = aes(x = reorder(name_1, llpp_who_2022), y = llpp_who_2022, fill = lyl_bucket), width = 0.5) +
  labs(x = "Province", y = "Potential Gain in Life Expectancy (Years)", fill = "Potential gain in life expectancy (Years)") +
  scale_y_continuous(breaks = seq(0, 5, 1), limits = c(0, 5)) +
  scale_fill_manual(values = c("0 to < 0.1" = "#ffffff",
                               "0.1 to < 0.5" = "#ffeda0",
                               "0.5 to < 1" = "#fed976",
                               "1 to < 2" = "#feb24c",
                               "2 to < 3" = "#fd8d3c",
                               "3 to < 4" = "#fc4e2a",
                               "4 to < 5" = "#e31a1c",
                               "5 to < 6" = "#bd0026",
                               ">= 6" = "#800026")) +
  coord_flip() +
  ggthemes::theme_tufte() +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 24, color="#222222"),
        legend.title = element_text(size = 24, color="#222222"),
        plot.title = element_text(hjust = 0.5, size = 16),
        plot.subtitle = element_text(hjust =  0.5, size = 10, face = "italic", margin = margin(b = 0.8, unit = "cm")),
        plot.caption = element_text(size = 8, hjust = 0, face = "italic"),
        legend.box.background = element_rect(color = "black"),
        plot.background = element_rect(color = "white"),axis.ticks.y = element_blank(),
        axis.line = element_line(),
        axis.text = element_text(size = 20, color="#222222"),
        axis.title = element_text(size = 24, color="#222222"),
        axis.title.y = element_text(margin = margin(r = 0.7, unit = "cm")),
        axis.title.x = element_text(margin = margin(t = 0.6, b = 0.6, unit = "cm")),
        axis.ticks = element_blank())



```
