---
title: "top.ten.charts.campaign"
author: "Aarsh"
date: '2022-07-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load-lib-helper-files-data-global-var}

# libraries
library(readr)
library(dplyr)
library(stringr)
library(magrittr)
library(ggplot2)
library(readr)
library(tidytext)
library(tidyr)
library(tidyverse)
library(sf)
library(usethis)
library(devtools)

# load and document to keep things updated
devtools::load_all()
devtools::document()

# read in latest color file
color_2020 <- read_csv("./june.2022/master.dataset/color_2020.csv")

# read in old available color datasets
color_2019 <- read_csv("./june.2022/master.dataset/color_2019.csv")
color_2016 <- read_csv("./june.2022/master.dataset/color_2016.csv")

# GBD final results file (resulting file that we get after applying the steps in the GBD technical appendix)
gbd_results <- read_csv("./june.2022/other.important.calculations.data/estimated_life_expectancy_differences_master_table_final.csv")

# global variables
who_guideline <- 5
le_constant <- 0.098

# global operations
`%notin%` <- Negate(`%in%`)


```

# Chart # 10: Year over Year Change in PM2.5 Levels in 2020, the first year of the Pandemic

```{r}
# Prepare  data set for chart number 10
chart10_dataset <- color_2020 %>%
  group_by(country) %>%
  mutate(pop_weights = population/sum(population, na.rm =TRUE), 
         pm2019_pop_weighted = pop_weights*pm2019,
         pm2020_pop_weighted = pop_weights*pm2020) %>%
  summarise(avg_pm2.5_pop_weighted_2019 = sum(pm2019_pop_weighted, na.rm = TRUE), 
            avg_pm2.5_pop_weighted_2020 = sum(pm2020_pop_weighted, na.rm = TRUE),
            change_pm2.5_2019_to_2020 = avg_pm2.5_pop_weighted_2020 - avg_pm2.5_pop_weighted_2019,
            percent_change_pm2.5_2019_to_2020 = (change_pm2.5_2019_to_2020/avg_pm2.5_pop_weighted_2019)*100,
            total_population = sum(population, na.rm = TRUE)) %>%
  mutate(direction_label = ifelse(change_pm2.5_2019_to_2020 < 0, "Negative", "Positive")) %>%
  slice_max(total_population, n = 20) 

# Save AR chart number 10 dataset as a csv
chart10_dataset %>% 
  write_csv("./june.2022/top.ten.charts.campaign/chart10.data.graph/chart10_dataset.csv")

# Plot chart number 10
chart10 <- chart10_dataset %>%  
  ggplot(mapping = aes(x = fct_reorder(country, percent_change_pm2.5_2019_to_2020), y = percent_change_pm2.5_2019_to_2020, fill = direction_label)) + geom_bar(stat = "identity") +
  geom_hline(mapping = aes(yintercept = 0)) +
  scale_y_continuous(limits = c(-25, 25), breaks = seq(-25, 25, 5)) +
  labs(x = "country", y = "Year over Year change in PM2.5 (%)")+
  ggthemes::theme_clean() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5), legend.position = "none") 


# Save chart number 10
ggsave("./june.2022/top.ten.charts.campaign/chart10.data.graph/chart10.png", chart10)
```


# Chart # 9: Life Expectancy Impacts of Particulate Pollution and Other Health Threats in the Four Most Populous Countries in Central and West Africa

```{r}

# GBD results filtered for relevant cause of death and countries 
chart9_dataset <- gbd_results %>%
  filter(cause_of_death %in% c("PM2.5 relative to WHO",
                               "Malaria", "Unsafe water, sanitation, and handwashing", 
                               "HIV/AIDS"), location %in% c("nigeria", "democratic republic of the congo", "Angola", "ghana", "cameroon"))

# making the 'location' column of type factor
chart9_dataset$location <- factor(chart9_dataset$location, 
                                        levels = c("nigeria", "democratic republic of the congo", "Angola", "ghana", "cameroon"))

# Rename Democratic Republic of the Congo to DRC
chart9_dataset$location <-  str_replace(chart9_dataset$location, 
            "democratic republic of the congo", "DRC")

# Converting 'cause_of_death' to type factor
chart9_dataset$cause_of_death <- as.factor(chart9_dataset$cause_of_death)

# Rearranging 'cause of death' levels
levels(chart9_dataset$cause_of_death) <- c("HIV/AIDS", "Malaria", "PM2.5 relative to WHO", "Unsafe Water, Sanitation and Handwashing")

# wrapping x-axis labels text 
levels(chart9_dataset$cause_of_death) <- str_wrap(levels(chart9_dataset$cause_of_death), 15)

# getting country wise population
country_wise_population <- color_2020 %>%
  group_by(country) %>%
  summarise(population_total = sum(population, na.rm = TRUE)) %>%
  ungroup() %>%
  filter(country %in% c("Cameroon", "Nigeria", "Angola", "Ghana", 
                  "Democratic Republic of the Congo")) %>%
  arrange(desc(population_total))

# reorder within each location as per the total life years lost column
chart9_dataset <- chart9_dataset %>% 
  mutate(cause_of_death = reorder_within(cause_of_death, est_le_diff_vs_actual_aggregate, location))

# clean the "cause of death" column and remove "Angola"
chart9_dataset <- chart9_dataset %>%
  mutate(`Cause of Death` = str_remove(cause_of_death, "___.+")) %>%
  filter(location %notin% "Angola")
  

# plot chart 9 
chart9 <- ggplot(chart9_dataset, mapping = aes(x = cause_of_death, y = est_le_diff_vs_actual_aggregate)) + 
  geom_col(mapping = aes(fill = `Cause of Death`), width = 0.7, color = "white") +
  facet_wrap(~factor(location, levels = c("nigeria", "DRC", "Angola", 
                  "ghana", "cameroon")), scales = "free_x", ncol = 5) +
  scale_fill_manual(values = c("darkcyan", "deepskyblue", "red",
                               "aquamarine")) +
  labs(x = "", y = "Years Lost", title = "Life Expectancy Impacts of PM2.5 & Other Health Threats", 
       subtitle = "Five Most Populous Countries in Central and West Africa") +
  ggthemes::theme_fivethirtyeight() +
  theme(axis.text.x = element_blank(), legend.position = "bottom", axis.ticks = element_blank()) 

# Save chart number 9
ggsave("./june.2022/top.ten.charts.campaign/chart9.data.graph/chart9.png", chart9)


# save chart9 dataset
chart9_dataset %>%
  select(location, cause_of_death, est_le_diff_vs_actual_aggregate) %>%
  rename(life_years_lost = est_le_diff_vs_actual_aggregate) %>%
  mutate(life_years_lost = round(life_years_lost, 1)) %>%
 write_csv("./june.2022/top.ten.charts.campaign/chart9.data.graph/chart9_dataset.csv")

```
