---
title: "Factsheets 2022"
author: "Aarsh"
date: '2022-07-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# get packages, global variables and datasets
```{r load-lib-helper-files-data-global-var}

# libraries
library(readr)
library(dplyr)
library(stringr)
library(magrittr)
library(ggplot2)
library(readr)
library(tidytext)
library(tidyr)
library(tidyverse)
library(sf)
library(usethis)
library(devtools)
library(data.table)

# load and document to keep things updated
devtools::load_all()
devtools::document()

# read in latest color file
color_2020 <- read_csv("./master.dataset/color_2020.csv")

# read in old available color datasets
color_2019 <- read_csv("./master.dataset/color_2019.csv")
color_2016 <- read_csv("./master.dataset/color_2016.csv")

# GBD final results file (resulting file that we get after applying the steps in the GBD technical appendix)
gbd_results <- read_csv("./other.important.calculations.data/estimated_life_expectancy_differences_master_table_final.csv")

# global variables
who_guideline <- 5
le_constant <- 0.098
ncap_midpoint <- 25
nat_stan_india <- 40
nat_stan_sk <- 25
nat_stan_bangladesh <- 15

# global operations
`%notin%` <- Negate(`%in%`)


```

# Nigeria Factsheet

```{r nigeria_fs}

# No National Standard for Nigeria
nat_stan_nigeria <- "No National Standard"

# filtering the color file for Nigeria
color_2020_nigeria <- color_2020 %>%
  filter(country == "Nigeria") %>%
  mutate(region = ifelse(name_1 %in% c("Ekiti", "Lagos", "Ogun", "Ondo", 
                                       "Osun", "Oyo"), "South-West Nigeria", 
                         "All other regions (excluding South-West Nigeria)"))

# nigeria factsheet figure 2 dataset
nigeria_fs_fig2_dataset <-  color_2020_nigeria %>%
  group_by(name_1) %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         pm2020_pop_weighted = pop_weights*pm2020) %>%
  summarise(avg_pm2.5_2020 = sum(pm2020_pop_weighted, na.rm = TRUE), gain_in_life_expectancy = (avg_pm2.5_2020 - who_guideline)*le_constant,
            gain_in_life_expectancy = ifelse(gain_in_life_expectancy < 0,  0, gain_in_life_expectancy),
            tot_pop = sum(population, na.rm = TRUE)) %>%
  slice_max(tot_pop, n = 10)  

# save nigeria fs fig2 dataset
nigeria_fs_fig2_dataset %>%
  write_csv("./factsheets/nigeria/graph.wise.datasets/nigeria_fs_fig2_dataset.csv")

# nigeria fs figure 2
 nigeria_fs_fig2 <- nigeria_fs_fig2_dataset %>% ggplot() +
  geom_col(mapping = aes(x = forcats::fct_reorder(name_1, gain_in_life_expectancy), y = gain_in_life_expectancy, fill = gain_in_life_expectancy)) +
  labs(x = "Region", y = "Average Life Expectancy Gains (Years)") +
  scale_y_continuous(breaks = seq(0, 3, 0.5)) +
   scale_fill_gradient(low = "burlywood1", high = "darkgoldenrod1") +
  coord_flip() +
  ggthemes::theme_clean() +
  theme(legend.position = "none")
 
# save nigeria factsheet figure 2
ggsave("./factsheets/nigeria/graphs/nigeria_fs_fig2.png", nigeria_fs_fig2)


# getting gbd result for Nigeria from the master file
gbd_nigeria <- gbd_results %>%
  filter(location == "nigeria")

# filter out some of the diseases that are already in some* (need to discuss this) way covered in the PM2.5 category
gbd_nigeria_filter <- gbd_nigeria %>%
  filter(cause_of_death %notin% c("Cardiovascular diseases", "Neoplasms", "Tobacco", 
                                  "Lower respiratory infections"))

# choosing the top 6 causes of death, based on "est_le_diff_vs_actual_aggregate" variable
nigeria_fs_fig3_dataset <- gbd_nigeria_filter %>%
  slice_max(est_le_diff_vs_actual_aggregate, n = 6)

# save nigeria fs figure 3 dataset
nigeria_fs_fig3_dataset %>%
  write_csv("./factsheets/nigeria/graph.wise.datasets/nigeria_fs_fig3_dataset.csv")

# nigeria fs figure 3
nigeria_fs_fig3 <- nigeria_fs_fig3_dataset %>%
  ggplot() + 
  geom_col(mapping = aes(x = forcats::fct_reorder(cause_of_death, est_le_diff_vs_actual_aggregate), y = est_le_diff_vs_actual_aggregate, fill = cause_of_death), width = 0.5) +
  labs(x = "Cause of Death", y = "Years Lost") + 
  coord_flip() +
   scale_fill_manual(values = c("royalblue", "royalblue",  
                                "royalblue", "royalblue", "darkred", "royalblue")) +
  ggthemes::theme_clean() +
  theme(legend.position = "none") +
  coord_flip()

# save nigeria factsheet figure 3
ggsave("./factsheets/nigeria/graphs/nigeria_fs_fig3.png", nigeria_fs_fig3)

# nigeria factsheet figure 4 dataset 
nigeria_fs_fig4_dataset <- color_2020_nigeria %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2020_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))), 
         region = "National Average") %>% 
  select(years, region, pop_weighted_avg_pm2.5)

# save nigeria fs figure 4 dataset
nigeria_fs_fig4_dataset %>%
  write_csv("./factsheets/nigeria/graph.wise.datasets/nigeria_fs_fig4_dataset.csv")
  

# nigeria factsheet figure 4 
  nigeria_fs_fig4 <- ggplot(nigeria_fs_fig4_dataset) +
  geom_line(mapping = ggplot2::aes(x = years, y = pop_weighted_avg_pm2.5), lwd = 1.1, 
            color = "darkred") +
    geom_hline(mapping = aes(yintercept = 5), lwd = 0.8) +
  scale_y_continuous(breaks = seq(0, 30, 5), limits = c(0, 30)) +
  scale_x_continuous(breaks = seq(1998, 2020, 2)) +
    scale_color_manual(values = c("National Average" = "darkgrey")) +
  ggthemes::theme_clean() +
  labs(x = "Years", 
       y = expression(paste("Average PM2.5 concentration ( ", mu, "g", "/", m^3, " )"))) +
  theme(legend.position = "bottom", legend.title = element_blank(), 
        legend.text = element_text(size = 7), 
        axis.title.y = element_text(size = 9), 
        axis.title.x = element_text(size = 9)) + 
     geom_text(x = 2003.5, y = 6.5, label = expression(paste("WHO PM2.5 Guideline (last updated: 2021): 5 ", mu, "g","/", m^3, "")))

  
# save nigeria factsheet figure 4
ggsave("./factsheets/nigeria/graphs/nigeria_fs_fig4.png", nigeria_fs_fig4)  

# appendix table nigeria factsheet 

nigeria_appendix_table <- color_2020_nigeria %>%
  group_by(name_1) %>%
   mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         pm2020_pop_weighted = pop_weights*pm2020) %>%
  summarise(total_population_millions = round((sum(population, na.rm = TRUE))/1000000, 1), avg_pm2.5_2020 = round(sum(pm2020_pop_weighted, na.rm = TRUE), 2),
            life_exp_gain_2020_who  = round((avg_pm2.5_2020 - who_guideline)*le_constant, 2), 
            life_exp_gain_2020_30perc_reduce = round(((avg_pm2.5_2020*0.30)*le_constant), 2)) %>%
  ungroup() %>%
  mutate(life_exp_gain_2020_who = ifelse(life_exp_gain_2020_who < 0, 0, life_exp_gain_2020_who)) %>%
  rename(`State` = name_1, `Population (Millions)` = total_population_millions, 
         `PM 2.5 concentration 2020 (µg/m³)` = avg_pm2.5_2020, 
         `From 2020 Concentration to WHO Guideline of 5 µg/m³` = life_exp_gain_2020_who, 
         `From 2020 Concentration reduction by 30 percent` = life_exp_gain_2020_30perc_reduce)

# save nigeria factsheet appendix table
nigeria_appendix_table %>%
   write_csv("./factsheets/nigeria/nigeria_fs_appendix_table_2022.csv")
  

```


# South Korea factsheet

```{r south_korea_fs}

# filter dataset for south korea
color_2020_south_korea <- color_2020 %>%
  filter(country %in% "South Korea")

# south korea factsheet figure 2 dataset
southkorea_fs_fig2_dataset <- color_2020_south_korea %>%
  group_by(name_1) %>% 
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         pm2020_pop_weighted = pop_weights*pm2020) %>%
  summarise(tot_pop = sum(population, na.rm = TRUE), avg_pm2.5_2020 = sum(pm2020_pop_weighted, na.rm = TRUE), 
            le_gain = (avg_pm2.5_2020 - who_guideline)*le_constant, 
            le_gain = ifelse(le_gain < 0 , 0, le_gain)) %>%
  slice_max(tot_pop, n = 10) %>%
  ungroup() 

# save south korea fs figure 2 dataset
southkorea_fs_fig2_dataset %>%
  write_csv("./factsheets/southkorea/graph.wise.datasets/southkorea_fs_fig2_dataset.csv")


# southkorea fs figure 2
southkorea_fs_fig2 <- southkorea_fs_fig2_dataset %>% 
  ggplot() +
  geom_col(mapping = aes(x = forcats::fct_reorder(name_1, le_gain), y = le_gain, fill = le_gain), width = 0.7) +
  labs(x = "Region", y = "Average Life Expectancy Gains (Years)") +
  scale_y_continuous(breaks = seq(0, 3, 0.5)) +
  scale_fill_gradient(low = "burlywood1", high = "darkgoldenrod1") +
  coord_flip() +
  theme_classic() +
  theme(legend.position = "none")

# save southkorea factsheet figure2

ggsave("./factsheets/southkorea/graphs/southkorea_fs_fig2.png", southkorea_fs_fig2) 

# southkorea factsheet figure 3 dataset
southkorea_fs_fig3_dataset <- color_2020_south_korea %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2020_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))), 
         region = "National Average") %>% 
  select(years, region, pop_weighted_avg_pm2.5)


# save south korea fs figure 3 dataset
southkorea_fs_fig3_dataset %>%
  write_csv("./factsheets/southkorea/graph.wise.datasets/southkorea_fs_fig3_dataset.csv")


  southkorea_fs_fig3 <- southkorea_fs_fig3_dataset %>%
    ggplot() +
  geom_line(mapping = ggplot2::aes(x = years, y = pop_weighted_avg_pm2.5), lwd = 1.1, 
            color = "darkred") +
    geom_hline(mapping = aes(yintercept = 5), lwd = 0.8, linetype = "dashed") +
    geom_hline(mapping = aes(yintercept = 25), lwd = 0.8, linetype = "dashed") + 
  scale_y_continuous(breaks = seq(0, 30, 5), limits = c(0, 30)) +
  scale_x_continuous(breaks = seq(1998, 2020, 2)) +
    scale_color_manual(values = c("National Average" = "darkgrey")) +
  ggthemes::theme_clean() +
  labs(x = "Years", 
       y = expression(paste("Average PM2.5 concentration ( ", mu, "g", "/", m^3, " )"))) +
  theme(legend.position = "bottom", legend.title = element_blank(), 
        legend.text = element_text(size = 7), 
        axis.title.y = element_text(size = 9), 
        axis.title.x = element_text(size = 9)) +  geom_text(x = 2003.6, y = 6.3, label = expression(paste("WHO PM2.5 Guideline (last updated: 2021): 5 ", mu, "g","/", m^3, ""))) +
    geom_text(x = 2014, y = 26.3, label = expression(paste("South Korea PM2.5 National Standard: 25 ", mu, "g","/", m^3, "")))
  
  
# save southkorea factsheet figure2
ggsave("./factsheets/southkorea/graphs/southkorea_fs_fig3.png", southkorea_fs_fig3)   

# South Korea fact sheet appendix table
southkorea_fs_appendix_table <- color_2020_south_korea %>%
  mutate(le_gain_who = round((pm2020 - who_guideline)*le_constant, 1), 
         le_gain_who = ifelse(le_gain_who < 0, 0, le_gain_who), 
         le_gain_nat_stan = round((pm2020 - nat_stan_sk)*le_constant, 1), 
         le_gain_nat_stan = ifelse(le_gain_nat_stan < 0, 0, le_gain_nat_stan), 
         change_poll_since_previous_year = pm2020 - pm2019,
         dir_change = ifelse(change_poll_since_previous_year > 0, "Up", "Down"), 
         perc_change = (change_poll_since_previous_year/pm2019)*100, 
         pop_millions = round(population/1000000, 1), 
         pm2020 = round(pm2020, 1)) %>%
  slice_max(population, n = 25) %>%
  select(name_1, name_2, pop_millions, pm2020, 
         le_gain_who, le_gain_nat_stan) %>%
  rename(`Province-level division` = name_1, `Municipal-level division` = name_2, `Population (Millions)` = pop_millions, 
         `PM 2.5 concentration 2020 (µg/m³)` = pm2020, 
         `From 2020 Concentration to WHO Guideline of 5 µg/m³` = le_gain_who, 
         `From 2020 Concentration to the National Standard of 25 µg/m³` = le_gain_nat_stan)

# South Korea factsheet appendix table save
southkorea_fs_appendix_table %>%
  write_csv("./factsheets/southkorea/southkorea_fs_appendix_table.csv")
 


```

# Bangladesh Factsheet

```{r bangladesh_fs}

# filtering color dataset and keeping only bangladesh
color_2020_bangladesh <- color_2020 %>%
  filter(country == "Bangladesh")


# bangladesh fs figure 2 dataset
bangladesh_fs_fig2_dataset <- color_2020_bangladesh %>%
  group_by(name_1) %>% 
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         pm2020_pop_weighted = pop_weights*pm2020) %>%
  summarise(tot_pop = sum(population, na.rm = TRUE), avg_pm2.5_2020 = sum(pm2020_pop_weighted, na.rm = TRUE), 
            le_gain = (avg_pm2.5_2020 - who_guideline)*le_constant, 
            le_gain = ifelse(le_gain < 0 , 0, le_gain)) %>%
  slice_max(tot_pop, n = 10) %>%
  ungroup() 

# save bangladesh fs figure 2 dataset
bangladesh_fs_fig2_dataset %>%
  write_csv("./factsheets/bangladesh/graph.wise.datasets/bangladesh_fs_fig2_dataset.csv")

# bangladesh fs figure 2
bangladesh_fs_fig2 <- bangladesh_fs_fig2_dataset %>%
  ggplot() +
  geom_col(mapping = aes(x = forcats::fct_reorder(name_1, le_gain), y = le_gain, fill = le_gain), width = 0.5) +
  labs(x = "Region", y = "Average Life Expectancy Gains (Years)") +
  scale_y_continuous(breaks = seq(0, 12, 1)) +
  scale_fill_gradient(low = "red", high = "darkred") +
  coord_flip() +
  theme_classic() +
  theme(legend.position = "none")

# save bangladesh factsheet figure 2
ggsave("./factsheets/bangladesh/graphs/bangladesh_fs_figure2.png", bangladesh_fs_fig2)

# filtering out the master GBD file for Bnagladesh
gbd_results_bangladesh <- gbd_results %>% 
  filter(location  == "Bangladesh")

# remove categories that are sort of* already covered under the PM2.5 category
gbd_results_bangladesh_filter <- gbd_results_bangladesh %>%
  filter(cause_of_death %notin% c("Cardiovascular diseases", "Neoplasms", "Tobacco", 
                                "Household air pollution from solid fuels"))

# bangladesh factsheet fig3 dataset
bangladesh_fs_fig3_dataset <- gbd_results_bangladesh_filter %>%
  slice_max(est_le_diff_vs_actual_aggregate, n = 6) 

# save bangladesh fs figure 3 dataset
bangladesh_fs_fig3_dataset %>%
  write_csv("./factsheets/bangladesh/graph.wise.datasets/bangladesh_fs_fig3_dataset.csv")

# bangladesh factsheet figure 3
bangladesh_fs_fig3 <- ggplot(bangladesh_fs_fig3_dataset) + 
  geom_col(mapping = aes(x = forcats::fct_reorder(cause_of_death, est_le_diff_vs_actual_aggregate), y = est_le_diff_vs_actual_aggregate, fill = cause_of_death), width = 0.5) +
  labs(x = "Cause of Death", y = "Years Lost") +
   scale_fill_manual(values = c("royalblue", "royalblue",  
                                "royalblue", "royalblue", "darkred", "royalblue")) +
  scale_y_continuous(breaks = seq(0, 8, 1)) +
  ggthemes::theme_clean() +
  theme(legend.position = "none") +
  coord_flip()  

# save bangladesh factsheet figure 3  
ggsave("./factsheets/bangladesh/graphs/bangladesh_fs_figure3.png", bangladesh_fs_fig3)

# bangladesh factsheet fig4 dataset
bangladesh_fs_fig4_dataset <- color_2020_bangladesh %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2020_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))), 
         region = "National Average") %>% 
  select(years, region, pop_weighted_avg_pm2.5) 

# save bangladesh fs figure 4 dataset
bangladesh_fs_fig4_dataset %>%
  write_csv("./factsheets/bangladesh/graph.wise.datasets/bangladesh_fs_fig4_dataset.csv")

# bangladesh factsheet fig4
bangladesh_fs_fig4 <- bangladesh_fs_fig4_dataset %>%
  ggplot() +
  geom_line(mapping = ggplot2::aes(x = as.integer(years), y = as.double(pop_weighted_avg_pm2.5)), lwd = 1.1, 
            color = "darkred") +
    geom_hline(mapping = aes(yintercept = 5), lwd = 0.8) +
  scale_y_continuous(breaks = seq(0, 80, 5), limits = c(0, 80)) +
  scale_x_continuous(breaks = seq(1998, 2020, 2))  +
  ggthemes::theme_clean() +
  labs(x = "Years", 
       y = expression(paste("Average PM2.5 concentration ( ", mu, "g", "/", m^3, " )"))) +
  theme(legend.position = "bottom", legend.title = element_blank(), 
        legend.text = element_text(size = 7), 
        axis.title.y = element_text(size = 9), 
        axis.title.x = element_text(size = 9)) +
   geom_text(x = 2002.8, y = 8.7, label = expression(paste("WHO PM2.5 Guideline (last updated: 2021): 5 ", mu, "g","/", m^3, "")))

# save bangladesh factsheet figure 4  
ggsave("./factsheets/bangladesh/graphs/bangladesh_fs_figure4.png", bangladesh_fs_fig4)

# bangladesh fs appendix table
bangladesh_fs_appendix_table <- color_2020_bangladesh %>%
  mutate(pm2020 = round(pm2020, 2),
         le_gain_red_to_who = round((pm2020 - who_guideline)*le_constant, 2),
         le_gain_red_to_who = ifelse(le_gain_red_to_who < 0, 0, le_gain_red_to_who),
         le_gain_red_to_nat = round((pm2020 - nat_stan_bangladesh)*le_constant, 2),
         le_gain_red_to_nat = ifelse(le_gain_red_to_nat < 0, 0, le_gain_red_to_nat),
         le_gain_red_by_30_percent = round((pm2020*0.3)*le_constant, 2), 
         pop_millions = round(population/1000000, 2)) %>%
  select(name_2, pop_millions, pm2020, le_gain_red_to_who, le_gain_red_to_nat, 
         le_gain_red_by_30_percent) %>%
  ungroup() %>%
  slice_max(pop_millions, n = 25) %>%
    rename(Region = name_2, 
         `Population (Millions)` = pop_millions, 
         `PM2.5 Concentration, 2020 (µg/m³)` = pm2020,
         `Years of LE Gain through reducing PM2.5 from 2020 concentration to WHO guideline of 5 µg/m³` = le_gain_red_to_who,
         `Years of LE Gain through reducing PM2.5 from 2020 concentration to National Standard of 15 µg/m³` = le_gain_red_to_nat, 
         `Years of LE Gain through reducing PM2.5 from 2020 concentration by 30 percent` = le_gain_red_by_30_percent) 


# save bangladesh factsheet appendix table
bangladesh_fs_appendix_table %>%
  write_csv("./factsheets/bangladesh/bangladesh_fs_appendix_table.csv")
```


# Nepal Factsheet

```{r nepal_fs}

# filtering the color dataset for Nepal
color_2020_nepal <- color_2020 %>%
  filter(country == "Nepal")

# nepal factsheet figure 2 dataset
nepal_fs_fig2_dataset <- color_2020_nepal %>%
  group_by(name_1) %>% 
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         pm2020_pop_weighted = pop_weights*pm2020) %>%
  summarise(tot_pop = sum(population, na.rm = TRUE), avg_pm2.5_2020 = sum(pm2020_pop_weighted, na.rm = TRUE), 
            le_gain = (avg_pm2.5_2020 - who_guideline)*le_constant, 
            le_gain = ifelse(le_gain < 0 , 0, le_gain)) %>%
  slice_max(tot_pop, n = 10) %>%
  ungroup() 

# save nepal factsheet figure 2 dataset
nepal_fs_fig2_dataset %>%
  write_csv("./factsheets/nepal/graph.wise.datasets/nepal_fs_fig2_dataset.csv")

# nepal fs figure 2
 nepal_fs_fig2 <- nepal_fs_fig2_dataset %>% 
   ggplot() +
  geom_col(mapping = aes(x = forcats::fct_reorder(name_1, le_gain), y = le_gain, fill = le_gain), width = 0.5) +
  labs(x = "Region", y = "Average Life Expectancy Gains (Years)") +
  scale_y_continuous(breaks = seq(0, 12, 1)) +
  coord_flip() +
   scale_fill_gradient(low = "red", high = "darkred") +
  theme_classic() +
  theme(legend.position = "none")
 
 # save nepal fs figure 2
 ggsave("./factsheets/nepal/graphs/nepal_fs_fig2.png", nepal_fs_fig2)



# filtering gbd results for Nepal
gbd_results_nepal <- gbd_results %>%
  filter(location == "Nepal")

# filtering out those causes of death that are sort of* covered under PM2.5 in some broad way
gbd_results_nepal_filter <- gbd_results_nepal %>%
  filter(cause_of_death %notin% c("Cardiovascular diseases", "Neoplasms", "Tobacco", 
                                "Household air pollution from solid fuels"))

nepal_fs_fig3_dataset <- gbd_results_nepal_filter %>%
  slice_max(est_le_diff_vs_actual_aggregate, n = 6)

# save nepal factsheet figure 3 dataset
nepal_fs_fig3_dataset %>%
  write_csv("./factsheets/nepal/graph.wise.datasets/nepal_fs_fig3_dataset.csv")

# nepal factsheet figure 3
nepal_fs_fig3 <- nepal_fs_fig3_dataset %>%
  ggplot() + 
  geom_col(mapping = aes(x = forcats::fct_reorder(cause_of_death, est_le_diff_vs_actual_aggregate), y = est_le_diff_vs_actual_aggregate, fill = cause_of_death), width = 0.5) +
  labs(x = "Cause of Death", y = "Years Lost") +
   scale_fill_manual(values = c("royalblue", "royalblue",  
                                "royalblue", "royalblue", "darkred", "royalblue")) +
  ggthemes::theme_clean() +
  theme(legend.position = "none") +
  coord_flip()  

 # save nepal fs figure 3
 ggsave("./factsheets/nepal/graphs/nepal_fs_fig3.png", nepal_fs_fig3)



# nepal factsheet figure 4 dataset
nepal_fs_fig4_dataset <- color_2020_nepal %>%
  mutate(pop_weights = population/sum(population, na.rm = TRUE), 
         mutate(across(starts_with("pm"), ~.x*pop_weights, .names = "{col}_weighted"))) %>%
  summarise(across(ends_with("weighted"), sum)) %>%
  pivot_longer(cols = pm1998_weighted:pm2020_weighted, names_to = "years", 
               values_to = "pop_weighted_avg_pm2.5") %>%
  mutate(years = as.integer(unlist(str_extract(years, "\\d+"))), 
         region = "National Average") %>% 
  select(years, region, pop_weighted_avg_pm2.5) 

# save nepal factsheet figure 4 dataset
nepal_fs_fig4_dataset %>%
  write_csv("./factsheets/nepal/graph.wise.datasets/nepal_fs_fig4_dataset.csv")

# nepal factsheet figure 4
 nepal_fs_fig4 <- nepal_fs_fig4_dataset %>%
   ggplot() +
  geom_line(mapping = ggplot2::aes(x = as.integer(years), y = as.double(pop_weighted_avg_pm2.5)), lwd = 1.1, 
            color = "darkred") +
    geom_hline(mapping = aes(yintercept = 5), lwd = 0.8) +
  scale_y_continuous(breaks = seq(0, 100, 5), limits = c(0, 60)) +
  scale_x_continuous(breaks = seq(1998, 2020, 2))  +
  ggthemes::theme_clean() +
  labs(x = "Years", 
       y = expression(paste("Average PM2.5 concentration ( ", mu, "g", "/", m^3, " )"))) +
  theme(legend.position = "bottom", legend.title = element_blank(), 
        legend.text = element_text(size = 7), 
        axis.title.y = element_text(size = 9), 
        axis.title.x = element_text(size = 9)) +
   geom_text(x = 2003.5, y = 8.7, label = expression(paste("WHO PM2.5 Guideline (last updated: 2021): 5 ", mu, "g","/", m^3, "")))
 
  # save nepal fs figure 4
 ggsave("./factsheets/nepal/graphs/nepal_fs_fig4.png", nepal_fs_fig4)

 
# Nepal Factsheet Appendix Table 
nepal_fs_appendix_table <- color_2020_nepal %>%
  mutate(pm2020 = round(pm2020, 2),
         le_gain_red_to_who = round((pm2020 - who_guideline)*le_constant, 2),
         le_gain_red_to_who = ifelse(le_gain_red_to_who < 0, 0, le_gain_red_to_who),
         le_gain_red_by_30_percent = round((pm2020*0.3)*le_constant, 2), 
         pop_millions = round(population/1000000, 2)) %>%
  select(name_2, pop_millions, pm2020, le_gain_red_to_who, 
         le_gain_red_by_30_percent) %>%
  ungroup() %>%
  slice_max(pop_millions, n = 25) %>%
    rename(Region = name_2, 
         `Population (Millions)` = pop_millions, 
         `PM2.5 Concentration, 2020 (µg/m³)` = pm2020,
         `Years of LE Gain through reducing PM2.5 from 2020 concentration to WHO guideline of 5 µg/m³` = le_gain_red_to_who, 
         `Years of LE Gain through reducing PM2.5 from 2020 concentration by 30 percent` = le_gain_red_by_30_percent) 


# save nepal factsheet appendix table
nepal_fs_appendix_table %>%
  write_csv("./factsheets/nepal/nepal_fs_appendix_table.csv")
```

